    Table table = new Table();
    TableRow tblRow;
    TableCell tblCell;
    tblRow= new TableRow();
    tblRow.TableSection = TableRowSection.TableHeader;
    tblCell= new TableCell();
    tblCell.Text = "Header";
    tblRow.Cells.Add(tblCell);
    table.Rows.Add(tableRow);
    tblRow= new TableRow();
    tblRow.TableSection = TableRowSection.TableBody;
    tblCell= new TableCell();
    tblCell.Text = "Body";
    tblRow.Cells.Add(tblCell);
    table.Rows.Add(tblRow);
    tblRow= new TableRow();
    tblRow.TableSection = TableRowSection.TableFooter;
    tblCell= new TableCell();
    tblCell.Text = "Footer";
    tblRow.Cells.Add(tblCell);
    table.Rows.Add(tblRow);
    WebForm.Controls.Add(table);
