    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Xml;
    using System.Xml.Linq;
    namespace ConsoleApplication48
    {
        class Program
        {
            static void Main(string[] args)
            {
                //<?xml version="1.0" encoding="UTF-8"?>
                //<!--Sample XML file generated by XMLSpy v2013 (http://www.altova.com)-->
                //<ftc:FATCA_OECD version="2.0" xsi:schemaLocation="urn:oecd:ties:fatca:v2 FatcaXML_v2.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ftc="urn:oecd:ties:fatca:v2" xmlns:sfa="urn:oecd:ties:stffatcatypes:v2">
                //    <ftc:MessageSpec>
                //        <sfa:SendingCompanyIN>S519K4.99999.SL.392</sfa:SendingCompanyIN>
                //        <sfa:TransmittingCountry>JP</sfa:TransmittingCountry>
                //        <sfa:ReceivingCountry>US</sfa:ReceivingCountry>
                //        <sfa:MessageType>FATCA</sfa:MessageType>
                //        <sfa:MessageRefId>DBA6455E-8454-47D9-914B-FEE48E4EF3AA</sfa:MessageRefId>
                //        <sfa:ReportingPeriod>2016-12-31</sfa:ReportingPeriod>
                //        <sfa:Timestamp>2017-01-17T09:30:47Z</sfa:Timestamp>
                //    </ftc:MessageSpec>
                //</ftc:FATCA_OECD>
                string header =
                    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                    "<ftc:FATCA_OECD" +
                       " version=\"2.0\" xsi:schemaLocation=\"urn:oecd:ties:fatca:v2 FatcaXML_v2.0.xsd\"" +
                       " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"" +
                       " xmlns:ftc=\"urn:oecd:ties:fatca:v2\" xmlns:sfa=\"urn:oecd:ties:stffatcatypes:v2\">" +
                    "</ftc:FATCA_OECD>";
                XDocument doc = XDocument.Parse(header);  //use parse instead if input is a string
                XElement FATCA_OECD = (XElement)doc.FirstNode;
                XNamespace ftcNS = FATCA_OECD.GetNamespaceOfPrefix("ftc");
                XNamespace sfaNS = FATCA_OECD.GetNamespaceOfPrefix("sfa");
                XElement MessageSpec = new XElement(ftcNS + "MessageSpec", new object[] {
                   new XElement(sfaNS + "SendingCompanyIN", "S519K4.99999.SL.392"),
                   new XElement(sfaNS + "TransmittingCountry", "JP"),
                   new XElement(sfaNS + "ReceivingCountry", "US"),
                   new XElement(sfaNS + "MessageType", "FATCA"),
                   new XElement(sfaNS + "MessageRefId", "DBA6455E-8454-47D9-914B-FEE48E4EF3AA"),
                   new XElement(sfaNS + "ReportingPeriod", "2016-12-31"),
                   new XElement(sfaNS + "Timestamp", "2017-01-17T09:30:47Z"),
                });
                
                
                
                FATCA_OECD.Add(MessageSpec);
                
     
            }
        }
    }
