                StringBuilder postData = new StringBuilder();
                postData.Append("login=" + HttpUtility.UrlEncode("username") + "&");
                postData.Append("password=" + HttpUtility.UrlEncode("password") + "&");
                postData.Append("Submit=" + HttpUtility.UrlEncode("Login"));
                ASCIIEncoding ascii = new ASCIIEncoding();
                byte[] postBytes = ascii.GetBytes(postData.ToString());
                CookieContainer cc = new CookieContainer();
                HttpWebRequest webReq = (HttpWebRequest)WebRequest.Create("http://squirlytraffic.com/members.php");
                webReq.Method = "POST";
                webReq.ContentType = "application/x-www-form-urlencoded";
                webReq.ContentLength = postBytes.Length;
                webReq.UserAgent = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)";
                webReq.CookieContainer = cc;
                Stream postStream = webReq.GetRequestStream();
                postStream.Write(postBytes, 0, postBytes.Length);
                postStream.Flush();
                postStream.Close();
                HttpWebResponse res = (HttpWebResponse)webReq.GetResponse();
                HttpWebRequest ImgReq = (HttpWebRequest)WebRequest.Create("http://squirlytraffic.com/surficon.php?ts=1491591235");
                ImgReq.Method = "GET";
                ImgReq.UserAgent = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)";
                ImgReq.CookieContainer = cc;
                HttpWebResponse ImgRes = (HttpWebResponse)ImgReq.GetResponse();
                Stream Img = ImgRes.GetResponseStream();
