    Microsoft.VisualStudio.Web.BrowserLink
    Microsoft.Extensions.FileProviders.Physical
    Microsoft.Extensions.FileSystemGlobbing
    Microsoft.AspNetCore.Hosting.Abstractions
    Microsoft.Extensions.Hosting.Abstractions
    Microsoft.AspNetCore.Hosting.Server.Abstractions
    Microsoft.Extensions.Configuration.Abstractions
    Microsoft.AspNetCore.DataProtection.Abstractions
    Microsoft.AspNetCore.Cryptography.Internal
    Microsoft.Extensions.WebEncoders
    Microsoft.AspNetCore.Authentication.Core
    Microsoft.AspNetCore.Http.Extensions
    Microsoft.Extensions.FileProviders.Abstractions
    Microsoft.AspNetCore.Http
    Microsoft.Extensions.ObjectPool
    Microsoft.AspNetCore.WebUtilities
    Microsoft.Net.Http.Headers
    Microsoft.AspNetCore.Authentication.Abstractions
    Microsoft.Extensions.Options
    Microsoft.Extensions.Logging.Abstractions
    Microsoft.Extensions.DependencyInjection.Abstractions
    System.ComponentModel.Annotations
    Microsoft.Extensions.Primitives
    Microsoft.AspNetCore.Http.Abstractions
    Microsoft.AspNetCore.Http.Features
    Microsoft.Extensions.Primitives
