        private void autogeneratedocno()
        {
            string str1 = txtdate.Text;
            string[] s1 = str1.Split('/');
            str1 = s1[1].ToString() + "/" + s1[0].ToString() +
            "/" + s1[2].ToString();
            string yy = s1[2].ToString();
            string mm = s1[1].ToString();
            string dd = s1[0].ToString();
            int y = Convert.ToInt32(yy);
            int m = Convert.ToInt32(mm);
            string z = yy.Substring(2,2);
            string sqlno =" selectisnull(max(substring
            (doc_no,3,5)),0)+1 from complaint where
            substring(doc_no,1,2) = '"+z+"'";
            con.Open();
            SqlCommand cmd = new SqlCommand(sqlno, con);
            string getno =
            Convert.ToString(cmd.ExecuteScalar());
            con.Close();
            string Inquiry_code = yy.Substring(2, 2) +
            getno.ToString().PadLeft(5, '0');
            txtdocno.Text = Inquiry_code;
        }
