    partial class MainPage : Page {
        public MainPage() {
            InitializeComponent();
    
            // add a handler to be called when the home page has been loaded
            this.Loaded += OnPageLoaded;             
        }
    
        async void OnPageLoaded(object sender, RoutedEventArgs e) {
            var listenkeyViewModel = new ListenkeyViewModel();
            await listenkeyViewModel.GetKey();
            listenkey = listenkeyViewModel.Listenkey;
        }
    
        // Shown for demonstration purposes only.
        // This is typically autogenerated by Visual Studio.
        private void InitializeComponent() {
        }
    }
