    partial class MainPage : Page {
        ListenkeyViewModel listenkeyViewModel;
        string listenkey;
        public MainPage() {
            InitializeComponent();
            listenkeyViewModel = new ListenkeyViewModel();
            // add a handler to be called when the page has been loaded
            this.Loaded += OnPageLoaded;             
        }
    
        async void OnPageLoaded(object sender, RoutedEventArgs e) {            
            await listenkeyViewModel.GetKey();
            listenkey = listenkeyViewModel.Listenkey;
        }
    
        // Shown for demonstration purposes only.
        // This is typically autogenerated by Visual Studio.
        private void InitializeComponent() {
        }
    }
