	class base<T>{
	    ....
	    public virtual T name();
	    ....
	}
	class deriveda : base<string>{
	    ....
	    public override string name();
	    ....
	}
	class derivedb : base<string>{
	    ....
	    public override string name();
	    ....
	}
	class derivedc : base<foo>{
	    ....
	    public override foo name();
	    ....
	}
