            DT = (DataTable)ViewState["Stop"];
            String id = StopID.Text;
            String name = StopName.Text;
            String location = StopLocation.Text;
            String Rid = RouteDropDown.SelectedItem.Value.ToString().Trim();
            DataRow row = DT.NewRow();
            row["id"] = id;
            row["name"] = name;
            row["location"] = location;
            row["routeId"] = Rid;
            DT.Rows.Add(row);
            StopListBox.DataSource = DT;
            StopListBox.DataTextField = "id";
            StopListBox.DataValueField = "id";
            StopListBox.DataBind();
            StopID.Text = "";
            StopName.Text = "";
            StopLocation.Text = "";
            ViewState["Stop"] = DT;
