    public virtual string Select(IClassMapper classMap, IPredicate predicate, IList<ISort> sort, IDictionary<string, object> parameters)
    {
        ......
        ......
        StringBuilder sql = new StringBuilder(string.Format("SELECT {0} FROM {1}",
        ......
        ......
		DapperExtensions.LastGeneratedQuery = sql.ToString();
        return sql.ToString();
    }
