    DatabaseReference db = FirebaseDatabase.DefaultInstance.RootReference;
    // Get the user id
    string userId = GameManager.Instance.User.UserId;
    // Get a reference to the profiles
	var profiles = db.Child("profiles");
    // Create a new serializable profile
	Profile profile = new Profile {
		userId = userId,
		name = "Bo Mortensen",
		age = 34,
		gender = "M"
	};				
    // Serialize profile to JSON
    string json = JsonUtility.ToJson (profile);		
    // Push a new document to the database
	var profileKey = profiles.Push ().Key;
    // Set JSON for this document
	profiles.Child (profileKey).SetRawJsonValueAsync (json, 1).ContinueWith (t => {
		if (t.IsCompleted) {
		    // Assign the profile key (unique key generated by Firebase) to the profile
			profile.profileKey = profileKey;
            // Set the Firebase server timestamp on the datetime object
            profiles.Child(profileKey).UpdateChildrenAsync(new Dictionary<string, object> { { "utcCreatedUnix", ServerValue.Timestamp } });
		}
	});
