    public partial class Form2 : Form
    {
        // ...
        private string ValueToHold { get; set; }
        // ...
        public void Form2_Load(object sender, EventArgs e)
        {
            // ...
            ValueToHold = "something";
            // ...
        }
        public void button1_Click(object sender, EventArgs e)
        {
            // ...
            // Use the ValueToHold here!
            // ...
        }
    }
