                EmployeeController empRepo = null;
                JobTitleController jtRepo = null;
                Department idept = new Department() { DepartmentName = "Department One", CreateDate = DateTime.Now };
                DepartmentController deptRepo = new DepartmentController();
                deptRepo.Add(idept);
                Employee emp = new Employee() { ParentDepartment = idept, SSN = "111111111", CreateDate = DateTime.Now, HireDate = DateTime.Now, LastName = "Smith", FirstName = "John" };
                JobTitle jtDev = new JobTitle() { JobTitleName = "Developer", CreateDate = DateTime.Now };
                JobTitle jtProjectManager = new JobTitle() { JobTitleName = "Project Manager", CreateDate = DateTime.Now };
                JobTitle jtDba = new JobTitle() { JobTitleName = "DBA", CreateDate = DateTime.Now };
                jtRepo = new JobTitleController();
                jtRepo.Add(jtDev);
                jtRepo.Add(jtProjectManager);
                empRepo = new EmployeeController();
                empRepo.AddEmployee(emp);
                EmployeeToJobTitleMatchLink link1ToAddThruJobTitleObject = new EmployeeToJobTitleMatchLink();
                link1ToAddThruJobTitleObject.TheEmployee = emp;
                link1ToAddThruJobTitleObject.TheJobTitle = jtDba;
                link1ToAddThruJobTitleObject.JobStartedOnDate = DateTime.Now.AddDays(-1);
                link1ToAddThruJobTitleObject.PriorityRank = 5;
                jtDba.AddEmployeeLink(link1ToAddThruJobTitleObject);
                jtRepo.Add(jtDba);
                EmployeeToJobTitleMatchLink link1ToAddThruEmployeeObject = new EmployeeToJobTitleMatchLink();
                link1ToAddThruEmployeeObject.TheEmployee = emp;
                link1ToAddThruEmployeeObject.TheJobTitle = jtDev;
                link1ToAddThruEmployeeObject.JobStartedOnDate = DateTime.Now.AddHours(-1);
                link1ToAddThruEmployeeObject.PriorityRank = 1;
                EmployeeToJobTitleMatchLink link2ToAddThruEmployeeObject = new EmployeeToJobTitleMatchLink();
                link2ToAddThruEmployeeObject.TheEmployee = emp;
                link2ToAddThruEmployeeObject.TheJobTitle = jtProjectManager;
                link2ToAddThruEmployeeObject.JobStartedOnDate = DateTime.Now.AddYears(5);
                link2ToAddThruEmployeeObject.PriorityRank = 2;
                emp.AddJobTitleLink(link1ToAddThruEmployeeObject);
                emp.AddJobTitleLink(link2ToAddThruEmployeeObject);
                empRepo.Upsert(emp);
