     public void ConfigureServices(IServiceCollection services)
            {
                ...
                services.AddScoped<ILogin, UserManager>();
                services.AddScoped<IRegister, UserManager>();
                ...
                services.AddMvc();
                ...
