            Microsoft.Office.Interop.Excel.Application xlexcel;
            Microsoft.Office.Interop.Excel.Workbook xlWorkBook;
            Microsoft.Office.Interop.Excel.Worksheet xlWorkSheet;
            object misValue = System.Reflection.Missing.Value;
            xlexcel = new Excel.Application();
            xlexcel.Visible = true;
            xlWorkBook = xlexcel.Workbooks.Add(misValue);
            xlWorkSheet = (Excel.Worksheet)xlWorkBook.Worksheets.get_Item(1);
            xlWorkBook.Application.ScreenUpdating = false;
            Excel.Range CR = (Excel.Range)xlWorkSheet.Cells[1, 1];
            CR.Select();
            xlWorkSheet.PasteSpecial(CR, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing, true);
            Excel.Range DR = (Excel.Range)xlWorkSheet.Columns["A:A"];
            DR.Select();
            DR.Delete();
            Excel.Range ACol = (Excel.Range)xlWorkSheet.Columns["A:A"];
            Excel.Range Ronge = ACol.SpecialCells(Excel.XlCellType.xlCellTypeBlanks);
            Ronge.EntireRow.Delete();
            Excel.Range A1 = (Excel.Range)xlWorkSheet.Cells[1, 1];
            A1.Select();
            xlWorkBook.Application.ScreenUpdating = true;
