    var array = new[] { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
    var count = 3;
    var deletedTest1 = 0;
    var test1 = array.Where(x => ++deletedTest1 > count).ToList();
    Console.WriteLine("Test 1");
    Console.WriteLine($"{{{String.Join(", ", test1)}}}");
    Console.WriteLine($"{{{String.Join(", ", test1)}}}");
    var deletedTest2 = 0;
    var test2 = array.Where(x => ++deletedTest2 > count).AsEnumerable();
    Console.WriteLine("Test 2");
    Console.WriteLine($"{{{String.Join(", ", test2)}}}");
    Console.WriteLine($"{{{String.Join(", ", test2)}}}");
    var deletedTest3 = 0;
    var test3 = array.Where(x => ++deletedTest3 > count);
    Console.WriteLine("Test 3");
    Console.WriteLine($"{{{String.Join(", ", test3)}}}");
    Console.WriteLine($"{{{String.Join(", ", test3)}}}");
    var deletedTest4 = 0;
    var test4 = array.Where(x => ++deletedTest4 > count).ToArray();
    Console.WriteLine("Test 4");
    Console.WriteLine($"{{{String.Join(", ", test4)}}}");
    Console.WriteLine($"{{{String.Join(", ", test4)}}}");
