    Grid g = new Grid();
    ColumnDefinition cd1 = new ColumnDefinition();
    ColumnDefinition cd2 = new ColumnDefinition();
    ColumnDefinition cd3 = new ColumnDefinition();
    cd1.Width = new GridLength(15, GridUnitType.Pixel);
    cd2.Width = new GridLength(200, GridUnitType.Pixel);
    cd3.Width = new GridLength(15, GridUnitType.Pixel);
    g.ColumnDefinitions.Add(cd1);
    g.ColumnDefinitions.Add(cd2);
    g.ColumnDefinitions.Add(cd3);
    RowDefinition rd1 = new RowDefinition();
    RowDefinition rd2 = new RowDefinition();
    RowDefinition rd3 = new RowDefinition();
    rd1.Height = new GridLength(15, GridUnitType.Pixel);
    rd2.Height = new GridLength(100, GridUnitType.Pixel);
    rd3.Height = new GridLength(15, GridUnitType.Pixel);
    g.RowDefinitions.Add(rd1);
    g.RowDefinitions.Add(rd2);
    g.RowDefinitions.Add(rd3);
    Border border = new Border();
    border.BorderThickness = new Thickness(2, 2, 2, 2);
    border.BorderBrush = Brushes.Red;
    border.CornerRadius = new CornerRadius(15, 15, 15, 15);
    Grid.SetColumn(border, 0);
    Grid.SetRow(border, 0);
    Grid.SetColumnSpan(border, 3);
    Grid.SetRowSpan(border, 3);
    Grid contentGrid = new Grid();
    contentGrid.Background = Brushes.Yellow;
    Grid.SetColumn(contentGrid, 1);
    Grid.SetRow(contentGrid, 1);
    g.Children.Add(border);
    g.Children.Add(contentGrid);
    root.Children.Add(g);
