    async void Button_Click(object sender, RoutedEventArgs e) // wpf event handler
    {
        ...
        await Task.Delay(1000); // pause 1 second
        ...
        while (someCondition)
        {
            ...
            await Task.Delay(1000);
            ...
        }
    }
