    class Program
    {
        static string[,] GAArr; // define in the class, but outside of the functions
        // ...
        static void World()
        {
            // ...
            GAArr = new string[GAWidth, GAHeight]; // create
            // ...
        }
        // ...
    }
