    Application.ThreadException += ...
    Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);
    AppDomain.CurrentDomain.UnhandledException += ...
    // tasks exceptions, add in app.config:
    //  <runtime>
    //      <ThrowUnobservedTaskExceptions enabled="true"/>
    //  </runtime>
    TaskScheduler.UnobservedTaskException += ...
