    System.Diagnostics.Process process = new System.Diagnostics.Process();
    System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
    startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
    startInfo.RedirectStandardOutput = true;
    startInfo.RedirectStandardInput = true;
    startInfo.UseShellExecute = false;
    startInfo.FileName = "cmd.exe";
    startInfo.Arguments = arguments;
    process.StartInfo = startInfo;
    process.Start();
