            Document document = new Document();
            Paragraph p1 = document.Paragraphs.Add();
            Table t1 = p1.Range.Tables.Add(p1.Range, 2, 1, Missing.Value, Missing.Value);
            t1.Range.Font.Size = 11;
            //t1.Style = style;
            t1.Rows[1].Alignment = WdRowAlignment.wdAlignRowCenter;
            t1.Cell(1, 1).Range.Select();
            document.Application.Selection.TypeText("void ");
            document.Application.Selection.MoveLeft(WdUnits.wdCharacter, "void ".Length, true);
            document.Application.Selection.Font.Color = WdColor.wdColorSkyBlue;
            document.Application.Selection.Collapse(WdCollapseDirection.wdCollapseEnd);
            document.Application.Selection.TypeText("item.FullName");
            document.Application.Selection.MoveLeft(WdUnits.wdCharacter, "item.FullName".Length, true);
            document.Application.Selection.Font.Color = WdColor.wdColorRed;
            document.Application.Selection.Collapse(WdCollapseDirection.wdCollapseEnd);
            t1.Cell(2, 1).Range.Select();
            document.Application.Selection.TypeText("item.swca_description");            
            document.Application.Selection.MoveLeft(WdUnits.wdCharacter, "swca_description".Length, true);
            document.Application.Selection.Font.Color = WdColor.wdColorBlack;
            document.Application.Selection.Collapse(WdCollapseDirection.wdCollapseEnd);
            t1.Cell(2, 1).Range.Bold = 0;
            document.SaveAs(@"D:\Test.docx");
