    public class MyDbContext : DbContext
    {
        // ...
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // ...
            modelBuilder.Entity<Contact>();
            // ...
        }
        // ...
    }
