    public class Inputhandler : ICommand
    {
        ...
        public class Execute(object Data)
        {
            ...
                mainViewModel.ShowWindow(MyCommands.ShowOPHome);
            ...
        }
        ...
    }
