        dataset.Tables.Add("OutputResults");
        dataset.Tables["OutputResults"].Columns.Add("OutputName", typeof(string));
        dataset.Tables["OutputResults"].Columns.Add("OutputValue", typeof(string));
        var value1Row = dataset.Tables["OutputResults"].NewRow();
        value1Row["OutputName"] = "Value1";
        value1Row["OutputValue"] = command.Parameters["@Value1"].Value;
        var value2Row = dataset.Tables["OutputResults"].NewRow();
        value2Row["OutputName"] = "Value2";
        value2Row["OutputValue"] = command.Parameters["@Value2"].Value;
        var value3Row = dataset.Tables["OutputResults"].NewRow();
        value3Row["OutputName"] = "Value3";
        value3Row["OutputValue"] = command.Parameters["@Value3"].Value;
        var value4Row = dataset.Tables["OutputResults"].NewRow();
        value4Row["OutputName"] = "Value4";
        value4Row["OutputValue"] = command.Parameters["@Value4"].Value;
        dataset.Tables["OutputResults"].Rows.Add(value1Row);
        dataset.Tables["OutputResults"].Rows.Add(value2Row);
        dataset.Tables["OutputResults"].Rows.Add(value3Row);
        dataset.Tables["OutputResults"].Rows.Add(value4Row);
