    // Generated by XSD.exe
    namespace A
    {
      partial class GeneratedRootXML 
      {
          public string Header {get;set;}
          ....
      }
    }
    
    // Generated by XSD.exe
    namespace B
    {
      partial class GeneratedRootXML 
      {
          public string Header {get;set;}
          ....
      }
    }
    
    // Your code
    interface IMyRootXML
    {
       public string Header {get;set;}
    }
    
    namespace A
    {
      partial class GeneratedRootXML : IMyRootXML
      {
      }
    }
    
    namespace B
    {
      partial class GeneratedRootXML : IMyRootXML
      {
      }
    }
