    public partial class YourAutoGeneratedClient
    {
        partial void CustomInitialize()
        {
            var retryPolicy = new RetryPolicy<TransientErrorIgnoreStrategy>(0);
            SetRetryPolicy(retryPolicy);
        }
    }
