    DataTable dt = new DataTable("habbo_items_TBL");
        dt.Columns.Add("base_item", typeof(string));
        dt.Columns.Add("user_id", typeof(int));
        dt.Columns.Add("room_id", typeof(int));
        dt.Rows.Add("base item1", 1, 2);
        dt.Rows.Add("base item2", 1, 2);
        dt.Rows.Add("base item3", 2, 3);
        SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["conStr"].ConnectionString);
        SqlCommand cmd = new SqlCommand("sp_save", conn);
        cmd.CommandType = CommandType.StoredProcedure;
        cmd.Parameters.AddWithValue("@habbo_items_TBL", dt);
        SqlParameter outPutParameter = new SqlParameter();
        outPutParameter.ParameterName = "@result";
        outPutParameter.SqlDbType = System.Data.SqlDbType.Int;
        outPutParameter.Direction = System.Data.ParameterDirection.Output;
        cmd.Parameters.Add(outPutParameter);
        conn.Open();
        cmd.ExecuteNonQuery();
        Int32 result = Convert.ToInt32(outPutParameter.Value);
