    FrameworkElement.SizeChanged  
    FrameworkElement.Loaded  
    FrameworkElement.Unloaded  
    ToolTipService.ToolTipOpening  
    ToolTipService.ToolTipClosing  
    UIElement.PreviewMouseLeftButtonDown  
    UIElement.MouseLeftButtonDown  
    UIElement.PreviewMouseLeftButtonUp  
    UIElement.MouseLeftButtonUp  
    UIElement.PreviewMouseRightButtonDown  
    UIElement.MouseRightButtonDown  
    UIElement.PreviewMouseRightButtonUp  
    UIElement.MouseRightButtonUp  
    Mouse.MouseEnter  
    Mouse.MouseLeave  
    Stylus.StylusEnter  
    Stylus.StylusLeave  
    Touch.TouchEnter  
    Touch.TouchLeave  
    Control.PreviewMouseDoubleClick  
    Control.MouseDoubleClick  
    Calendar.SelectedDatesChanged  
    DatePicker.SelectedDateChanged  
    VirtualizingStackPanel.CleanUpVirtualizedItemEvent
