            DataTable table = new DataTable();
            table.Columns.Add("Name", typeof(string));
            table.Columns.Add("Subject", typeof(string));
            table.Columns.Add("Score", typeof(string));
            table.Rows.Add("Brian", "English", 0.6);
            table.Rows.Add("Sarah", "English", 0.6);
            table.Rows.Add("Jim", "English", 0.6);
            table.Rows.Add("Brian", "Math", 0.6);
            table.Rows.Add("Sarah", "Math", 0.6);
            table.Rows.Add("Jim", "Math", 0.6);
            table.Rows.Add("Brian", "Science", 0.6);
            table.Rows.Add("Sarah", "Science", 0.6);
            table.Rows.Add("Jim", "Science", 0.6);
