    public ActionResult Products_Create([DataSourceRequest]DataSourceRequest request, ProductViewModel product)
    {
        if (ModelState.IsValid)
        {
            using (var northwind = new NorthwindEntities())
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new Product
                {
                    ProductName = product.ProductName,
                    UnitsInStock = product.UnitsInStock
                };
                // Add the entity
                northwind.Products.Add(entity);
                // Insert the entity in the database
                northwind.SaveChanges();
                // Get the ProductID generated by the database
                product.ProductID = entity.ProductID;
            }
        }
        // Return the inserted product. The grid needs the generated ProductID. Also return any validation errors.
        return Json(new[] { product }.ToDataSourceResult(request, ModelState));
    }
