    var excelSettingsManager = new ApplicationSettingsManager(AddinModule.CurrentInstance.ExcelApp);
    //store all settings you are going to tamper with...
    excelSettingsManager.SaveSetting("EnableEvents");
    excelSettingsManager.SaveSetting("ScreenUpdating");
    //change excel setting and do your thing...
    //...
    //when done, restore settings
    excelSettingsManager.RestoreAllSettings();
