    protected static DatabaseAccessor.GetDataFromDatabase(...)
    protected static DatabaseAccessor.UpdateSomething(...)
    protected static ServerCache.GetFromCacheOrGetFresh(...)
    protected static ServerCache.InvalidateCache(...)
    public static DepartmentsService.Read()
    public static DepartmentsService.Update(string id)
    public static DepartmentsService.Create(...)
