    protected DatabaseAccessor.GetDataFromDatabase(...)
    protected DatabaseAccessor.UpdateSomething(...)
    protected ServerCache.GetFromCacheOrGetFresh(...)
    protected ServerCache.InvalidateCache(...)
    public DepartmentsService.Read()
    public DepartmentsService.Update(string id)
    public DepartmentsService.Create(...)
