    var cb = new FixedLengthClassBuilder("Customer");
    cb.AddField("BirthDate", 8, typeof(DateTime));
    cb.LastField.Converter.Kind = ConverterKind.Date;
    cb.LastField.Converter.Arg1 = "ddMMyyyy";
    cb.LastField.FieldNullValue = DateTime.Now;
    cb.AddField("Name", 3, typeof(string));
    cb.AddField("Age", 3, typeof(int));
    cb.LastField.TrimMode = TrimMode.Both;
    Type recordClass = cb.CreateRecordClass();
    dynamic customer1 = Activator.CreateInstance(recordClass);
    customer1.BirthDate = new DateTime(1972, 8, 14);
    customer1.Name = "Joe";
    customer1.Age = 42;
    dynamic customer2 = Activator.CreateInstance(recordClass);
    customer2.BirthDate = new DateTime(1971, 9, 15);
    customer2.Name = "Tina";
    customer2.Age = 43;
    var list = new List<object>();
    list.Add(customer1);
    list.Add(customer2);
    var engine = new FileHelperEngine(recordClass);
    engine.WriteFile(filename, list);
