        ....
        ....
        if(membersName.Any(x => x == "Text"))
        {
            PropertyInfo propInfo = type.GetProperty("Text");
            propInfo.SetValue(obj, ass.Text, null);
        }
        ....
        ....
