    EQGraph.Series.Add("Front Left");
    EQGraph.ChartAreas[0].AxisX.Maximum = 20000;
    EQGraph.ChartAreas[0].AxisX.Minimum = 10;
    EQGraph.ChartAreas[0].AxisX.IsLogarithmic = true;
    EQGraph.ChartAreas[0].AxisX.MinorGrid.Interval = 1;
    EQGraph.ChartAreas[0].AxisX.MinorGrid.Enabled = true;
    EQGraph.ChartAreas[0].AxisY.Maximum = 20;
    EQGraph.ChartAreas[0].AxisY.Minimum = -50;
    EQGraph.ChartAreas[0].AxisY.Interval = 5;
    EQGraph.ChartAreas[0].AxisX.MinorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.DashDotDot;
    EQGraph.ChartAreas[0].AxisY.MajorGrid.LineDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.DashDotDot;
    EQGraph.ChartAreas[0].AxisX.LabelStyle.Font = new System.Drawing.Font("Trebuchet MS", 10F, System.Drawing.FontStyle.Bold);
    EQGraph.ChartAreas[0].AxisY.LabelStyle.Font = new System.Drawing.Font("Trebuchet MS", 10F, System.Drawing.FontStyle.Bold);
    EQGraph.ChartAreas[0].AxisX.Title = "Frequency(Hz)";
    EQGraph.ChartAreas[0].AxisY.Title = "Gain";
    int[] xValuesFrontLeft = { 10, 100, 1000, 5000, 4200, 8499 };
    int[] yValuesFrontLeft = { 16, 10, -5, -10, 35, -40 };
    EQGraph.Series["Front Left"].Points.DataBindXY(xValuesFrontLeft, yValuesFrontLeft);
    EQGraph.Series["Front Left"].ChartType =SeriesChartType.Spline;
