            XmlDocument doc = new XmlDocument();
            doc.LoadXml(xml);
            XmlNode mercedes = doc.SelectSingleNode("//Mercedes");
            XmlNode attr1 = doc.CreateNode(XmlNodeType.Element, "", "Attr", "");
            XmlAttribute name1 = doc.CreateAttribute("Name");
            name1.Value = "Wheels";
            XmlAttribute value1 = doc.CreateAttribute("Value");
            value1.Value = "true";
            attr1.Attributes.Append(name1);
            attr1.Attributes.Append(value1);
            mercedes.AppendChild(attr1);
            XmlNode attr2 = doc.CreateNode(XmlNodeType.Element, "", "Attr", "");
            XmlAttribute name2 = doc.CreateAttribute("Name");
            name2.Value = "Lights";
            XmlAttribute value2 = doc.CreateAttribute("Value");
            value2.Value = "false";
            attr2.Attributes.Append(name2);
            attr2.Attributes.Append(value2);
            mercedes.AppendChild(attr2);
