    var col = new DataGridTemplateColumn {Header = "Actions"};
    var dt = new DataTemplate();
    var stkpnl = new FrameworkElementFactory(typeof(StackPanel));
    stkpnl.SetValue(StackPanel.OrientationProperty, Orientation.Horizontal);
    var btn1 = new FrameworkElementFactory(typeof(Button));
    btn1.SetValue(ContentProperty, "Delete");
    btn1.AddHandler(ButtonBase.ClickEvent, new RoutedEventHandler(btnDelete_Click));
    btn1.SetValue(MarginProperty, new Thickness(0, 0, 10, 0));
    stkpnl.AppendChild(btn1);
    var btn2 = new FrameworkElementFactory(typeof(Button));
    btn2.SetValue(ContentProperty, "Edit");
    btn2.AddHandler(ButtonBase.ClickEvent, new RoutedEventHandler(btnEdit_Click));
    stkpnl.AppendChild(btn2);
    dt.VisualTree = stkpnl;
    col.CellTemplate = dt;
    DgEmp.Columns.Add(col);
