    public class Data
    {
        public bool SmartCursorToggle { get; set; }
        public bool MapEnabled { get; set; }
        public int InvasionBarMode { get; set; }
        public bool AutoSave { get; set; }
        public bool AutoPause { get; set; }
        public int Language { get; set; }
        public bool PlacementPreview { get; set; }
        public bool GoreVisualsAllowed { get; set; }
        public float VolumeSound { get; set; }
        public float VolumeAmbient { get; set; }
        public float VolumeMusic { get; set; }
        public string KeyUp { get; set; }
        public string KeyDown { get; set; }
        public string KeyLeft { get; set; }
        public string KeyRight { get; set; }
        public string KeyJump { get; set; }
        public string KeyThrowItem { get; set; }
        public string KeyInventory { get; set; }
        public string KeyQuickHeal { get; set; }
        public string KeyQuickMana { get; set; }
        public string KeyQuickBuff { get; set; }
        public string KeyUseHook { get; set; }
        public string KeyAutoSelect { get; set; }
        public string KeySmartCursor { get; set; }
        public string KeyMount { get; set; }
        public string KeyMapStyle { get; set; }
        public string KeyFullscreenMap { get; set; }
        public string KeyMapZoomIn { get; set; }
        public string KeyMapZoomOut { get; set; }
        public string KeyMapAlphaUp { get; set; }
        public string KeyMapAlphaDown { get; set; }
        public bool Fullscreen { get; set; }
        public bool WindowMaximized { get; set; }
        public int DisplayWidth { get; set; }
        public int DisplayHeight { get; set; }
        public int GraphicsQuality { get; set; }
        public bool BackgroundEnabled { get; set; }
        public bool FrameSkip { get; set; }
        public int LightingMode { get; set; }
        public int LightingThreads { get; set; }
        public int MouseColorR { get; set; }
        public int MouseColorG { get; set; }
        public int MouseColorB { get; set; }
        public float Parallax { get; set; }
        public bool ShowItemText { get; set; }
        public int LastLaunchedVersion { get; set; }
        public string ClientUUID { get; set; }
        public bool UseSmartCursorForCommonBlocks { get; set; }
        public bool UseSmartAxeAfterSmartPickaxe { get; set; }
        public bool UseSmartWallReplacement { get; set; }
        public bool DisableLeftShiftTrashCan { get; set; }
        public bool HighlightNewItems { get; set; }
        public bool HidePasswords { get; set; }
        public bool ThickMouseEdges { get; set; }
        public long ThickMouseEdgesPackedColor { get; set; }
        public bool ReverseUpDownForArmorSetBonuses { get; set; }
        public bool CloudSavingDefault { get; set; }
    }
