    private void grid_AutoGeneratedColumns(object sender, EventArgs e)
            {
                var columnsToReplace = new List<DataGridTextColumn>();
    
                foreach (var col in this.grid.Columns)
                {
                    var textCol = col as DataGridTextColumn;
                    if (textCol != null)
                    {
                        columnsToReplace.Add(textCol);                  
                    }
                }
    
                foreach(var col in columnsToReplace)
                {
                    this.ReplaceColumn(col, CopyColumn(col));
                }
            }
    
    
            private void ReplaceColumn(DataGridBoundColumn originalColumn, DataGridBoundColumn newColumn)
            {
                this.grid.Columns.Add(newColumn);
    
                this.grid.Columns.Remove(originalColumn);
            }
            private DataGridTextColumn CopyColumn(DataGridTextColumn originalColumn)
            {
                var newCol = new DataGridTextColumnEx();
    
                newCol.Binding = originalColumn.Binding;
                newCol.Header = originalColumn.Header;
    
                return newCol;
            }
