    using Microsoft.Win32.Interop;
    ...
    ...
    try {
        ...
        ...
    } catch (HttpListenerException e) {
        if (e.ErrorCode == WinError.ERROR_OPERATION_ABORTED) {
            // Do something
        }
    }
