     using System.Web.Configuration;
     ..............
     ..............
    var blockedCountries =  WebConfigurationManager.AppSettings["BlockedCountries"].Split(',',StringSplitOptions.RemoveEmptyEntries);
    var result =  model.countries.Where(x=> !blockedCountries.Contains(x.Key)).ToArray();
