    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    namespace Cssd.IT.PortalIntegration.DataAccess.HR.Dao
    {
        using System;
        using System.Collections.Generic;
        
        public partial class CCS_DEPT_TBL
        {
            // This table in SQL Server does not have a primary key, it just has an index
            public string DEPTID { get; set; }
            public string DESCR { get; set; }
            public System.DateTime EFFDT { get; set; }
            public string EFF_STATUS { get; set; }
            public Nullable<System.DateTime> LASTUPDDTTM { get; set; }
        }
    }
