    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    namespace Cssd.IT.PortalIntegration.DataAccess.HR.Dao
    {
        using System;
        using System.Data.Entity;
        using System.Data.Entity.Infrastructure;
        
        public partial class HRADDbContext : DbContext
        {
            public HRADDbContext()
                : base("name=HRADDbContext")
            {
            }
        
            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                //throw new UnintentionalCodeFirstException();
            }
        
            public virtual DbSet<CCS_DEPT_TBL> CCS_DEPT_TBL { get; set; }
            public virtual DbSet<CCS_HR_AD_SYNC> CCS_HR_AD_SYNC { get; set; }
        }
    }
