    TcpListener server = new TcpListener(System.Net.IPAddress.Loopback, 8080);
    server.Start();
    Console.WriteLine("Wait for clients");
    TcpClient client = server.AcceptTcpClient();
    Console.WriteLine("Writing content");
    string content = "Goodbye World!";
    System.IO.StreamWriter writer = new System.IO.StreamWriter(client.GetStream());
    writer.Write("HTTP/1.0 200 OK");
    writer.Write(Environment.NewLine);
    writer.Write("Content-Type: text/plain; charset=UTF-8");
    writer.Write(Environment.NewLine);
    writer.Write("Content-Length: "+ content.Length);
    writer.Write(Environment.NewLine);
    writer.Write(Environment.NewLine);
    writer.Write(content);
    writer.Flush();
    Console.WriteLine("Disconnecting");
    client.Close();
    server.Stop();
    Console.ReadKey();
