     [assembly: AssemblyTitle("TApplciation Name")]
        [assembly: AssemblyDescription("")]
        [assembly: AssemblyConfiguration("")]
        [assembly: AssemblyCompany("")]
        [assembly: AssemblyProduct("")]
        [assembly: AssemblyCopyright("Copyright ©  2015")]
        [assembly: AssemblyTrademark("")]
        [assembly: AssemblyCulture("")]
        [assembly: AssemblyVersion("5.8.3")]
        [assembly: AssemblyFileVersion("5.8.3")]
