                DataSet carprofileDs = new DataSet("carprofile");
                DataTable carInfoTable = new DataTable("Carinfo");
                carprofileDs.Tables.Add(carInfoTable);
                DataTable codingsTable = new DataTable("Codings");
                carprofileDs.Tables.Add(codingsTable);
                carInfoTable.Columns.Add("Series", typeof(string));
                carInfoTable.Columns.Add("Chassis", typeof(string));
                carInfoTable.Columns.Add("Car", typeof(string));
                carInfoTable.Columns.Add("Type", typeof(string));
                carInfoTable.Columns.Add("Year", typeof(string));
                carInfoTable.Columns.Add("Owner", typeof(string));
                carInfoTable.Columns.Add("Vin", typeof(string));
                carInfoTable.Columns.Add("Milage", typeof(string));
                carInfoTable.Columns.Add("Line", typeof(string));
                carInfoTable.Columns.Add("Package", typeof(string));
                carInfoTable.Columns.Add("Color", typeof(string));
                codingsTable.Columns.Add("Applied-codings", typeof(string));
                carprofileDs.WriteXml("filename", XmlWriteMode.WriteSchema);
                carprofileDs = new DataSet();
                carprofileDs.ReadXml("filename");
