    SmtpClient client = new SmtpClient("real.server.on.the.internet");
    MailMessage mail = new MailMessage("Flattiverse <info@flattiverse.com>", "Ghostie <matthias.lukaseder.test@gmail.com>");
    mail.BodyEncoding = System.Text.Encoding.UTF8;
    mail.SubjectEncoding = System.Text.Encoding.UTF8;
    LinkedResource image = new LinkedResource("test.png", "image/png");
    image.ContentId = "test.png@71236720.91827344";
    image.TransferEncoding = System.Net.Mime.TransferEncoding.Base64;
    image.ContentType.Name = "test.png@71236720.91827344";
    image.ContentLink = new Uri("cid:test.png@71236720.91827344");
    AlternateView plainView = AlternateView.CreateAlternateViewFromString("Please view as HTML-Mail.", System.Text.Encoding.UTF8, "text/plain");
    plainView.TransferEncoding = System.Net.Mime.TransferEncoding.QuotedPrintable;
    AlternateView htmlView = AlternateView.CreateAlternateViewFromString("Image there?<br /><img src=\"cid:test.png@71236720.91827344\" /><br />Hope so!", System.Text.Encoding.UTF8, "text/html");
    htmlView.LinkedResources.Add(image);
    htmlView.TransferEncoding = System.Net.Mime.TransferEncoding.QuotedPrintable;
    mail.AlternateViews.Add(plainView);
    mail.AlternateViews.Add(htmlView);
    mail.Subject = "15";
    client.UseDefaultCredentials = false;
    client.Credentials = new System.Net.NetworkCredential("working_username", "working_password");
    client.Send(mail);
