            Runspace runSpace = RunspaceFactory.CreateRunspace();
            runSpace.Open();
            PSSnapInException psex;
            runSpace.RunspaceConfiguration.AddPSSnapIn("Citrix.*.Admin.V*", out psex);
            Pipeline pipeline = runSpace.CreatePipeline();
            Command getSession = new Command("Get-BrokerSession");
            getSession.Parameters.Add("AdminAddress");
            getSession.Parameters.Add("SERVERNAME");
            pipeline.Commands.Add(getSession);
            Collection<PSObject> output = pipeline.Invoke();
