    [Serializable]
    public class Account, ICloneable, ...
    {
        ...
        public override object Clone()
        {
            var entity = base.Clone() as Account;
            entity.Roles = ... (clone roles)
            ...
            return entity;
        }
        ...
