    foreach (StringWrapper characteristic in viewModel.Characteristics)
    {
        // ...
        binding.Path = new PropertyPath("Characteristics[\"" + characteristic.Value + "\"]");
        //...
    }
