    string constr = @"Provider=Microsoft.ACE.OLEDB.12.0; Data Source=" + dbPath;
    string cmdstr = "select * from serverManagerTable";
    OleDbConnection con = new OleDbConnection(constr);
    OleDbCommand com = new OleDbCommand(cmdstr, con);
    con.Open();
    //OleDbDataReader reader = com.ExecuteReader();
    //reader.Read();
    DataSet data = new DataSet();
    OleDbDataAdapter da = new OleDbDataAdapter(com);
    da.Fill(data);
    int i = data.Tables[0].Rows.Count;
    MessageBox.Show(i.ToString());
