    this.button1.Click += new System.EventHandler(this.button_Click); //notice the event name is the same
    ....
    this.button2.Click += new System.EventHandler(this.button_Click); //notice the event name is the same
    ....
    this.button36.Click += new System.EventHandler(this.button_Click); //notice the event name is the same
