    public string Protect(AuthenticationTicket data) {
       ...
       var issued = data.Properties.IssuedUtc;
       ...
       var token = new JwtSecurityToken(_issuer, audienceId, data.Identity.Claims,
           issued.Value.UtcDateTime, expires.Value.UtcDateTime, signingKey);
       ...
    }
