    PdfPTable linkTable = new PdfPTable(2);
    PdfPCell linkCell = new PdfPCell();
    Anchor linkAnchor = new Anchor("Click here to go to top of next page.");
    linkAnchor.Reference = "#target";
    Paragraph linkPara = new Paragraph();
    linkPara.Add(linkAnchor);
    linkCell.AddElement(linkPara);
    linkTable.AddCell(linkCell);
    linkTable.AddCell(new PdfPCell(new Phrase("cell 2")));
    linkTable.AddCell(new PdfPCell(new Phrase("cell 3")));
    linkTable.AddCell(new PdfPCell(new Phrase("cell 4")));
    doc.Add(linkTable);
    doc.NewPage();
    Anchor destAnchor = new Anchor("top");
    destAnchor.Name = "target";
    PdfPTable destTable = new PdfPTable(1);
    PdfPCell destCell = new PdfPCell();
    Paragraph destPara = new Paragraph();
    destPara.Add(destAnchor);
    destCell.AddElement(destPara);
    destTable.AddCell(destCell);
    destTable.AddCell(new PdfPCell(new Phrase("cell 2")));
    destTable.AddCell(new PdfPCell(new Phrase("cell 3")));
    destTable.AddCell(new PdfPCell(new Phrase("cell 4")));
    doc.Add(destTable);
