    string name = "John Edward Jr.";
            string surname = "Pascal Einstein W. Alfi";
            string school = "St. John";
            string s = "";
            int charWidth = 0;
            int width = 60 - name.Count();
            charWidth = name.Count();
            s = s + string.Format("{0,-" + width + "}" + "{1," + charWidth + "}", "Name: " + name, "AAA: ");
            Console.WriteLine(s);
            s = "";
            width = 60 - surname.Count();
            charWidth = surname.Count();
            s = s + string.Format("{0,-" + width + "}" + "{1," + charWidth + "}", "Surname: " + surname, "BBB: ");
            Console.WriteLine(s);
            s = "";
            width = 60 - school.Count();
            charWidth = school.Count();
            s = s + string.Format("{0,-" + width + "}" + "{1," + charWidth + "}", "School: " + school, "CCC: ");
            Console.WriteLine(s);
