    ...
        Global.hostWindow.Closing += hostWindow_Closing;
    ...
        private void hostWindow_Closing(object sender, EventArgs e)
        {
            Global.Closing = true;
        }
    ...
        while (Nodes.Count > 0 && Global.Closing == false)
        {
        ...
        }
