    public void MyMethod()
    {
        ...
        ...
        {
            var o = new MyObject();
            var otherReferenceToSameObject = o;
            var s = "my string";
            ...
            ...
            ...
            ...
            
            otherReferenceToSameObject = o = null;
            s = null;
        }
        ...
        ...
    }
