    public ActionResult Stuff(){
        //MyEntityFrameworkClass is an autogenerated Entity Framework 
        //object that represents a table in your database
        List<MyEntityFrameworkClass> items = db.MyEntityFrameworkClass.ToList();
        Return Json(items);
    }
