            Binding bind = null;
            for (int r = 1; r <= rows; r++)
            {
                bind = new Binding("Description");
                bind.Source = payments[r - 1];
                TextBlock col = new TextBlock();
                BindingOperations.SetBinding(col, TextBlock.TextProperty, bind);
                col.TextAlignment = TextAlignment.Left;
                col.VerticalAlignment = VerticalAlignment.Center;
                col.Width = 240;
                bdr = new Border();
                bdr.BorderBrush = System.Windows.Media.Brushes.Black;
                bdr.BorderThickness = new Thickness(2);
                Grid.SetColumn(bdr, 0);
                Grid.SetRow(bdr, r);
                bdr.Child = col;
                grdPayments.Children.Add(bdr);
                bind = new Binding("Due");
                bind.Source = payments[r - 1];
                bind.Converter = new MbcsCentral.CurrencyPaddingConverter();
                bind.ConverterParameter = "10";
                col = new TextBlock();
                BindingOperations.SetBinding(col, TextBlock.TextProperty, bind);
                col.TextAlignment = TextAlignment.Right;
                col.VerticalAlignment = VerticalAlignment.Center;
                col.HorizontalAlignment = HorizontalAlignment.Left;
                col.Width = 100;
                bdr = new Border();
                bdr.BorderBrush = System.Windows.Media.Brushes.Black;
                bdr.BorderThickness = new Thickness(2);
                Grid.SetColumn(bdr, 1);
                Grid.SetRow(bdr, r);
                bdr.Child = col;
                grdPayments.Children.Add(bdr);
                NumberEntry vi = new NumberEntry();
                bind = new Binding("Paid");
                bind.Source = payments[r - 1];
                bind.StringFormat = "######0.00";
                BindingOperations.SetBinding(vi, NumberEntry.TextProperty, bind);
                vi.MaxLength = 10;
                vi.Decimals = 2;
                vi.Width = 100;
                vi.LostFocus += NumberEditor_LostFocus;
                vi.PreviewKeyDown += PaidBlock_PreviewKeyDown;
                bdr = new Border();
                bdr.BorderBrush = System.Windows.Media.Brushes.Black;
                bdr.BorderThickness = new Thickness(2);
                Grid.SetColumn(bdr, 2);
                Grid.SetRow(bdr, r);
                bdr.Child = vi;
                grdPayments.Children.Add(bdr);
            }
