    var TheQuery = MyDC.SomeTable
                .OrderByDescending(....
                .Where(.....
                .GroupBy(s => s.SomeColumnID)
                .Select(items => items.FirstOrDefault(i => i.SomeOtherColumnId == someId)).ToList();
