    var TheQuery = MyDC.SomeTable
                .OrderByDescending(....
                .Where(.....
                .GroupBy(s => s.SomeColumnID)
                .SelectMany(items => items.Where(i => i.SomeOtherColumnId == someId).Take(10));
