    public class Item1 : IItem
    {
        ...
        public string Type { get; }
        ...
    }
    public class Item2 : IItem
    {
        ...
        public string Type { get; }
        ...
    }
