    public class PlayerChanger : MonoBehaviour {
         public RaycastController myRC;
         ...
         ...
         ...
         //whenever you need to use it...
         myRC.jumpableCollisionMask = 11;
