    public void ConfigureServices(IServiceCollection services)
    {
        //...
        services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>, MyUserClaimsPrincipalFactory>();
        //...
    }
