    public class Company {
        // ...
        public List<Feature> CompanyFeatures;
        // ...
    }
    public class Division {
        public Company Company;  // The company to which the division belongs
        // ...
        public List<Feature> DivisionFeatures;
        // ...
    }
