    ....
    public static ISessionFactory CreateSessionFactory(string connectionString) {
       if (_sessionFactory == null){ 
        _sessionFactory = Fluently.Configure()
                    .Database(MsSqlConfiguration ...
                        ... 
                        //custom configuration settings
                        ...
                        cfg.SetListener(ListenerType.PostInsert, new AuditListener());
                    })
                    .BuildSessionFactory();
        }
        return _sessionFactory;
    }
    ....
