    private void Form1_Load(object sender, EventArgs e) {
        ...
        ...
        MAPCodeList MAPCode = new MAPCodeList(xyz);
        MAPComboBox1.DataSource = MAPCode.List;
        ...
        ...
    }
