    <DataGrid AutoGeneratedColumns="DataGrid_AutoGeneratedColumns">
        <DataGrid.Columns>
            <my:DataGrid.Columns>
                <my:DataGridTemplateColumn Header="Edit">
                    <my:DataGridTemplateColumn.CellTemplate>
                        <DataTemplate>
                            <... />
                        </DataTemplate>
                    </my:DataGridTemplateColumn.CellTemplate> 
                </my:DataGridTemplateColumn> 
            </my:DataGrid.Columns>
        </DataGrid.Columns>
    </DataGrid>
