    <GroupedCustomers>
      <Male>
        <Customer>
          <Name>John</Name>
          <Age>30</Age>
          <Order>
            <Id>123</Id>
            <Price>200.00</Price>
          </Order>
        </Customer>
        <Customer>
          <Name>Jack</Name>
          <Age>34</Age>
          <Order>
            <Id>126</Id>
            <Price>475.00</Price>
          </Order>
        </Customer>
      </Male>
      <Female>
        <Customer>
          <Name>Jane</Name>
          <Age>28</Age>
          <Order>
            <Id>124</Id>
            <Price>100.00</Price>
          </Order>
        </Customer>
        <Customer>
          <Name>Jill</Name>
          <Age>37</Age>
          <Order>
            <Id>125</Id>
            <Price>350.00</Price>
          </Order>
        </Customer>
      </Female>
    </GroupedCustomers>
