    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.4952
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://confluence.atlassian.com/rpc/soap-axis/confluenceservice-v1", ConfigurationName="ConfluenceSoapService")]
    public interface ConfluenceSoapService
    {
        // CODEGEN: Generating message contract since the wrapper namespace (http://soap.rpc.confluence.atlassian.com) of message getPermissionsRequest does not match the default value (http://confluence.atlassian.com/rpc/soap-axis/confluenceservice-v1)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        getPermissionsResponse getPermissions(getPermissionsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://soap.rpc.confluence.atlassian.com) of message searchRequest does not match the default value (http://confluence.atlassian.com/rpc/soap-axis/confluenceservice-v1)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RemoteException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RemotePermission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RemoteNodeStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RemotePageHistory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RemoteContentPermission))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRemotePageSummary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RemoteSpaceSummary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RemoteSearchResult))]
        searchResponse search(searchRequest request);
