    string test = "foo.txt";
            var sw = new System.IO.StreamWriter(new System.IO.FileStream(test, System.IO.FileMode.Open, System.IO.FileAccess.Write, System.IO.FileShare.Read));
            var sr = new System.IO.StreamReader(new System.IO.FileStream(test, System.IO.FileMode.Open, System.IO.FileAccess.Read, System.IO.FileShare.ReadWrite)); 
            var res = sr.ReadLine(); 
            res = sr.ReadLine();
            sw.WriteLine("g");
            sw.Flush(); 
            res = sr.ReadLine(); 
            res = sr.ReadLine();
            sw.WriteLine("h"); 
            sw.Flush(); 
            sw.WriteLine("i");
            sw.Flush(); 
            sw.WriteLine("j");
            sw.Flush(); 
            sw.WriteLine("k"); 
            sw.Flush(); 
            res = sr.ReadLine(); 
            res = sr.ReadLine(); 
            res = sr.ReadLine();
            res = sr.ReadLine();
            res = sr.ReadLine();
            res = sr.ReadLine();
