    switch(GetStringHeader(s))
    {
        case StringHeader.ABC: ...
        case StringHeader.QWERTY: ...
        ...
    }
    StringHeader GetStringHeader(string s)
    {
        if (s.StartsWith("ABC")) return StringHeader.ABC;
        ...
    }
    enum StringHeader { ABC, QWERTY, ... }
