    // When saving to the cache, use a MemoryStream to save off the bitmap as an array of bytes
    using (MemoryStream ms = new MemoryStream()) {
        bitmap.Save(ms, bitmap.RawFormat);
        context.Cache.Insert(key, (byte[])ms.ToArray(), ...
        ...
    }
    
    ...
    
    // When retrieving, create a new Bitmap based on the bytes retrieved from the cached array
    if (context.Cache[key] != null) {
        using (MemoryStream ms = new MemoryStream((byte[])context.Cache[key])) {
            using (Bitmap bmp = new Bitmap(ms)) {
                bmp.Save(context.Response.OutputStream ...
    ...
