    <Job>
      <Process>
         <Name>something.exe</Name>
         <RelatedProcess>
           <Process>
              <Name>somethingelse.exe</Name>
              <RelatedProcess>
                 <Process>
                  <Name>recursive.exe</Name>
                 </Process>
              </RelatedProcess>
           </Process>
           <Process>
              <Name>OneMorething.exe</Name>
           </Process>
        </RelatedProcess>
      </Process>
    </Job>
