    using System;
    
    namespace ProjectEuler
    {
        class Question2
        {
            //Project Euler - Question 2
            //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            //Find the sum of all the even-valued terms in the sequence which do not exceed four million
            static void Main()
            {
                int sum = 0;
    
                int currentNumber = 1;
    	    int lastNumber = 0;
    
                while (currentNumber <= 500)
                {
                    if (currentNumber % 2 == 0)
                    {
                        sum += currentNumber;
                    }
    
    		int nextNumber = lastNumber + currentNumber;
    		lastNumber = currentNumber;
    		currentNumber = nextNumber;
                }
    
                Console.WriteLine("Project Euler - Question 2\n\nAnswer: " + sum);
                Console.ReadLine();
            }
        }
    }
