    // Autogenerated stub provides the rest of the code
    public partial class Order
    {
        public override string ToString()
        {
            return string.Format("{0} - {1}", Name, Quantity);
        }
    }
