    class GridDisplayRow:UserControl
    {
       public event EventHandler<System.EventArgs> SomethingHappened;
       protected void Page_Load(object sender, EventArgs e)
       {
           //Initialize the drop down with something;
       }
       //this is where we handle internal events generated by children controls.
       //Eg: the drop down's index changed.
       protected void DDLProperty2_OnSelectedIndexChanged(object sender, EventArgs e)
       {
           //we update some other child control in this...
           this.TxtProperty1.Text = this.DDLProperty2.Value;
           //and maybe we want to signal the page that some event happened
           if(SomethingHappened != null)
           {
              //Notify the page that SomethingHappened event occured
              SomethingHappened(this, EventArgs.Empty);
           } 
       }
    
       //This is where the binding happens
       public object BindingObject
       {
          set
          {
               Foo temp = (Foo)value;
               this.TxtProperty1.Text = temp.Bar1;
               this.DDLProperty2.Value = temp.Bar2;
               this.RadProperty3.Value = temp.Bar3;
    
               this.ViewState["Foo"] = temp;   
          }
       }
    }
