    public static Type GeneratePersonSerializer(XmlAttributeOverrides overrides) {
        //here compile a class to generate a Type inheriting from IXmlSerializable
        //the serializer logic in this class should be generated by taking into
        //account the given XmlAttributeOverrides
        //the type returned should be the Type passed into new XmlSerializer(Type type)
    }
