    protected void GridView1_RowBound(object sender, GridViewRowEventArgs e)
    {
        if (e.Row.RowType == DataControlRowType.Header)
        {
            //add new header
            TableCell tc = new TableCell();
            tc.Text = "Groovy Link";
            e.Row.Cells.Add(tc);
            //hide original column that has been autobound - skip column we just added
            for (int i = 0; i < e.Row.Cells.Count - 1; i++)
            {
                BoundField field = (BoundField)((DataControlFieldCell)e.Row.Cells[i]).ContainingField;
                if (field.DataField == "AutoGeneratedColumnName")
                    field.Visible = false;
            }
        }
        else if (e.Row.RowType == DataControlRowType.DataRow)
        {
            //create new tablecell
            TableCell tc = new TableCell();
            if (DataBinder.Eval(e.Row.DataItem, "AutoGeneratedColumnName").ToString().StartsWith("<a") == true)
            {
                //create hyperlink
                HyperLink hyp = new HyperLink();
                hyp.NavigateUrl = DataBinder.Eval(e.Row.DataItem, "AutoGeneratedColumnName").ToString();
                hyp.Text = "click here";
                tc.Controls.Add(hyp);
            }
            else
            {
                //just text
                tc.Text = DataBinder.Eval(e.Row.DataItem, "AutoGeneratedColumnName").ToString()
            }
            //add tablecell to row
            e.Row.Cells.Add(tc);
            //hide original column that has been autobound
            for (int i = 0; i < e.Row.Cells.Count - 1; i++)
            {
                BoundField field = (BoundField)((DataControlFieldCell)e.Row.Cells[i]).ContainingField;
                if (field.DataField == "AutoGeneratedColumnName")
                    field.Visible = false;
            }
        }
    }
