     private static readonly char[] Delimiters = { ',', ' ', ';' };
     // Alternatively, if you find it more readable...
     // private static readonly char[] Delimiters = ", ;".ToCharArray();
     ...
     String[] toList = test.Split(Delimiters, StringSplitOptions.RemoveEmptyEntries);
