			ObservableCollection<StopBlock> data = new ObservableCollection<StopBlock>();
			StopBlock block1 = new StopBlock();
			block1.Departures.Add(new Departure());
			block1.Departures.Add(new Departure());
			block1.Departures.Add(new Departure());
			block1.Departures.Add(new Departure());
			block1.Departures.Add(new Departure());
			StopBlock block2 = new StopBlock();
			block2.Departures.Add(new Departure());
			block2.Departures.Add(new Departure());
			block2.Departures.Add(new Departure());
			block2.Departures.Add(new Departure());
			block2.Departures.Add(new Departure());
			StopBlock block3 = new StopBlock();
			block3.Departures.Add(new Departure());
			block3.Departures.Add(new Departure());
			block3.Departures.Add(new Departure());
			block3.Departures.Add(new Departure());
			block3.Departures.Add(new Departure());
			data.Add(block1);
			data.Add(block2);
			data.Add(block3);
			Data = data;
