			List<BusStop> data = new List<BusStop>();
			BusStop busStop1 = new BusStop("Some Stop", "123");
			busStop1.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			busStop1.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			busStop1.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			busStop1.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			BusStop busStop2 = new BusStop("Other Stop", "42");
			busStop2.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			busStop2.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			busStop2.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			busStop2.Depatures.Add(new Depature("Nils Eriksson Term", 5, 15));
			BusStop busStop3 = new BusStop("Not A Stop", "0");
			busStop3.Depatures.Add(new Depature("Void", 5, 15));
			busStop3.Depatures.Add(new Depature("Void", 5, 15));
			busStop3.Depatures.Add(new Depature("Void", 5, 15));
			busStop3.Depatures.Add(new Depature("Void", 5, 15));
			data.Add(busStop1);
			data.Add(busStop2);
			data.Add(busStop3);
			Data = data;
