    using System.Data.SqlTypes;
    ...
    public static void CKTransfrom(out SqlString resultXML, SqlString inputXML, SqlString transformXSL)
    ...
    using (StringReader sr = new StringReader(transformXSL.Value))
    ...
    using (StringReader sr = new StringReader(inputXML.Value))
    ...
