    public class WSField : Attribute {
      // ...
      internal string xmlField; // you can also make it a property with an internal setter...
      public WSField(string tableField, string xmlField = null) {
    
    ...
    public class FieldDefinition {
      public FieldDefinition(FieldInfo fieldInfo) {
        // ...
        if (this.wsField.xmlField == null) this.wsField.xmlField = fieldInfo.Name;
      }
    
    ...
