    using(var msg = new MailMessage())
    {
        ...
        ...
        var attachment = new Attachment(strMem, filename,contentType);
        msg.Attachments.Add(attachment);
        ...
        ...             
        msg.Send();
    }
