    List<string> dinosaurs = new List<string>();    
    dinosaurs.Add("Compsognathus");
    dinosaurs.Add("Amargasaurus");
    dinosaurs.Add("Deinonychus");
    Console.WriteLine("Count: {0}", dinosaurs.Count);
    Console.WriteLine("Capacity: {0}", dinosaurs.Capacity);
    dinosaurs.Clear();
    Console.WriteLine("\nClear()");
    Console.WriteLine("\nCount: {0}", dinosaurs.Count);
    Console.WriteLine("Capacity: {0}", dinosaurs.Capacity);
