    using (var context = new MyDataContext())
    {
        var pm = new Product_Master(); // Type generated by the LINQ designer.
        pm.Property1 = "foo";
        pm.Property2 = 123;
        //...
        context.Product_Master.InsertOnSubmit(pm);
        context.SubmitChanges();
    }
