    using System.Web.Script.Serialization;
    ...
    Dictionary<int,List<int>> MyObj = new Dictionary<int,List<int>>();
    //Populate it here...
    string myJsonString = (new JavaScriptSerializer()).Serialize(MyObj);
