          ...
          dataAdapter.Fill(dt);
          ...
          System.Data.DataColumn pkCol = dt.Columns[0]; // something like dt.Columns["Id"]
          pkCol.Unique = true;
          dt.PrimaryKey = new DataColumn[] {pkCol };
          ...
          OleDbCommandBuilder c = new OleDbCommandBuilder(dataAdapter);
          ...
