    internal class System.Net.ContextAwareResult
    internal class System.Net.ListenerClientCertAsyncResult
    internal class System.Net.ListenerAsyncResult
    internal class System.Net.HttpRequestStream/HttpRequestStreamAsyncResult
    internal class System.Net.HttpResponseStreamAsyncResult
    internal class System.Net.NestedMultipleAsyncResult
    internal class System.Net.NestedSingleAsyncResult
    internal class System.Net.WorkerAsyncResult
    internal class System.Net.Cache.CombinedReadStream/InnerAsyncResult
    internal class System.Net.Cache.ForwardingReadStream/InnerAsyncResult
    internal class System.Net.BufferAsyncResult
    internal class System.Net.Base64Stream/ReadAsyncResult
    internal class System.Net.Base64Stream/WriteAsyncResult
    internal class System.Net.BufferedReadStream/ReadAsyncResult
    internal class System.Net.Mime.MimeBasePart/MimePartAsyncResult
    internal class System.Net.Mime.MultiAsyncResult
    internal class System.Net.Mime.QuotedPrintableStream/WriteAsyncResult
    internal class System.Net.Mail.SmtpConnection/ConnectAndHandshakeAsyncResult
    internal class System.Net.Mail.SmtpReplyReaderFactory/ReadLinesAsyncResult
    internal class System.Net.Mail.SendMailAsyncResult
