    string filename = "<your LaTeX source file>.tex";
    Process p1 = new Process();
    p1.StartInfo.FileName = "<your path to>\pdflatex.exe";
    p1.StartInfo.Arguments = filename;
    p1.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
    p1.StartInfo.RedirectStandardOutput = true;
    p1.StartInfo.UseShellExecute = false;
    Process p2 = new Process();
    p2.StartInfo.FileName = "<your path to>\bibtex.exe";
    p2.StartInfo.Arguments = Path.GetFileNameWithoutExtension(filename);
    p2.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
    p2.StartInfo.RedirectStandardOutput = true;
    p2.StartInfo.UseShellExecute = false;
    p1.Start();
    var output = p1.StandardOutput.ReadToEnd();
    p1.WaitForExit();
    p2.Start();
    output = p2.StandardOutput.ReadToEnd();
    p2.WaitForExit();
    p1.Start();
    output = p1.StandardOutput.ReadToEnd();
    p1.WaitForExit();
    p1.Start();
    output = p1.StandardOutput.ReadToEnd();
    p1.WaitForExit();
