    int tfeid = 222;
            string fileName = "myFile";
            string fullFileName = @"C:\myFile.pdf";
            FileStream fs = new FileStream(fullFileName, FileMode.OpenOrCreate, FileAccess.Read);
            byte[] MyData = new byte[fs.Length];
            fs.Read(MyData, 0, System.Convert.ToInt32(fs.Length));
            fs.Close();
            DbProviderFactory MFactory = DbProviderFactories.GetFactory("MySql.Data.MySqlClient");
            DbConnection Mconnect = MFactory.CreateConnection();
            Mconnect.ConnectionString = ConfigurationManager.ConnectionStrings["ConnexionMySql"].ConnectionString;
            Mconnect.Open();
            DbCommand Mcommand = Mconnect.CreateCommand();
            Mcommand.CommandText = "UPDATE tfe_abstract SET pdf = ?paramImg, pdfnom = \"" + fileName + "\" WHERE tfeid = " + tfeid;
            DbParameter parametre = Mcommand.CreateParameter();
            parametre.ParameterName = "paramImg";
            parametre.Value = MyData;
            Mcommand.Parameters.Add(parametre);
            int result = Mcommand.ExecuteNonQuery();
            Mconnect.Close();
