    // <auto-generated />
    using Microsoft.Phone.Controls;
    
    namespace MyAppNamespace
    {
        public partial class MainPage : PhoneApplicationPage
        {
            private static string[] AllFilesInImagesFolder()
            {
                return new[] {
                               "images/image1.png",
                               "images/image2.png",
                               "images/image3.png",
                               "images/image4.png",
                               "images/image5.png",
                            };
            }
        }
    }
