    <#@ template debug="false" hostspecific="true" language="C#" #>
    <#@ output extension=".gen.cs" #>
    <#@ import namespace="System.IO"#>
    // <auto-generated />
    using Microsoft.Phone.Controls;
    
    namespace MyAppNamespace
    {
        public partial class MainPage : PhoneApplicationPage
        {
            private static string[] AllFilesInImagesFolder()
            {
                return new[] {
    <#
                DirectoryInfo directoryInfo = new DirectoryInfo(Path.Combine(Path.GetDirectoryName(Host.TemplateFile), "images"));
    
                foreach(FileInfo file in directoryInfo.GetFiles("*.*", SearchOption.AllDirectories))
                {
    				if (!file.FullName.Contains(@"\."))
    				{#>
                               "<#= file.FullName.Substring(file.FullName.IndexOf("images")).Replace(@"\", "/") #>",
    <#          	}
    			}
    #>
                            };
            }
        }
    }
