    Timer CreateTimer(object unitID)
    {
        object   row      = ...
        TimeSpan dueTime  = ...
        TimeSpan interval = ...
        return new Timer(x => DatabaseTransfer (x, unitID), row, dueTime, interval);
    }
    static void DatabaseTransfer(object row, object unitID)
    {
        ....
    }
