&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;configuration&gt;
   &lt;configSections&gt;
      &lt;sectionGroup name=&quot;applicationSettings&quot; 
                    type=&quot;System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
           &lt;section name=&quot;<b><i>YourProjectName</b></i>.Properties.Settings&quot; 
                    type=&quot;System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; 
                    requirePermission=&quot;false&quot; /&gt;
    &lt;/sectionGroup&gt;
&lt;/configSections&gt;
