    public class Foo{
	object Col1 {get;set;}
	object Col2 {get;set;}
	object Col50 {get;set;}
	NestedFoo[] NestedData {get;set;}}
    public class NestedFoo{
	object NestedCol1 {get;set;}
	object NestedCol2 {get;set;}
	object NestedCol50 {get;set;}}
