    class programmer {
     name ...
     email ...
     seat location ...
    }
    
    class html_coder extends programmer {
     canCodeHTML ...
    }
    
    class script_coder extends programmer {
     canCodeHTML ...
     canCodeJavascript ...
    }
    
    class senior_developer extends programmer {
     canCodeHTML ...
     canCodeJavascript ...
     canAccessDatabase ...
     canEditProjectArchitectureFiles ...
     canWearTennisShoesToWork...
    }
