     public class MyServiceType : //....
     {
          private static readonly Object _lockObject = new Object();
          // ....
          lock(_lockObject)
          {
               ....
          }
