    If(!IsPostBack) 
    {
      DataList binding code goes here......
      ...........................
    }
    protected void DropDownList2_SelectedIndexChanged(object sender, EventArgs e)
    {
        // Bind the DataList here....
    }
