    MyCompany.Castle v1.1.0.3
       Castle.Windsor v2.5.3
          Castle.Core v2.5.2
          MyCompany.Common v1.1.0.6
             CommonServiceLocator v1.0
                MyCompany.Enum v1.1.0.7
       MyCompany.Common v1.1.0.6
          CommonServiceLocator v1.0
             MyCompany.Enum v1.1.0.7
          MyCompany.Enum v1.1.0.7
             MyCompany.Versioning v1.3
                Castle.Core v2.5.2
                   Castle.Windsor v2.5.3
                      Castle.Core v2.5.2
                      CommonServiceLocator v1.0
                         NUnit v2.5.10.11092
                            RhinoMocks v3.6
