    SQLiteConnection conn = new SQLiteConnection("data source=:memory:");
    conn.Open();
    var command = conn.CreateCommand();
    command.CommandText = "create table a (b integer primary key autoincrement, c text)";
    command.ExecuteNonQuery();
    var tran1 = conn.BeginTransaction();
    var tran2 = conn.BeginTransaction();
    var command1 = conn.CreateCommand();
    var command2 = conn.CreateCommand();
    command1.Transaction = tran1;
    command2.Transaction = tran2;
    command1.CommandText = "insert into a VALUES (NULL, 'bla1')";
    command2.CommandText = "insert into a VALUES (NULL, 'bla2')";
    command1.ExecuteNonQuery();
    command2.ExecuteNonQuery();
    tran1.Commit();
    tran2.Commit();
    command.CommandText = "select count(*) from a";
    Console.WriteLine(command.ExecuteScalar());
