    using SharpDX;
    using SharpDX.Direct3D11;
    using SharpDX.DXGI;
    using System;
    using System.Diagnostics;
    using System.Drawing;
    using System.Drawing.Imaging;
    using System.IO;
    using System.Threading.Tasks;
