    Console.WriteLine(a); // 1
    Console.WriteLine(b); // 2
    Console.WriteLine(c); // 3
    Console.WriteLine(d); // 4
    Console.WriteLine(e); // 1
    Console.WriteLine(f); // 2
    Console.WriteLine(g); // 3
    Console.WriteLine(h); // 4
    Console.WriteLine(i); // 5
    Console.WriteLine(j); // 0
