    public static string TabbedMenu(this HtmlHelper html, string area, bool IsAuthenticated)
    {
         ...
         if(IsAuthenticated)
             print something...
         else
             print something else...
         ...
    }
