            public async Task<HashSet<StateProvince>> GetAllStates()
        {
            var states = new HashSet<StateProvince>()
            {
                new StateProvince() { StateCode = "AL", StateName = "Alabama" },
                new StateProvince() { StateCode = "AK", StateName = "Alaska" },
                new StateProvince() { StateCode = "AZ", StateName = "Arizona" }, 
                new StateProvince() { StateCode = "AR", StateName = "Arkansas" },
                new StateProvince() { StateCode = "CA", StateName = "California" },
                new StateProvince() { StateCode = "CO", StateName = "Colorado" },
                new StateProvince() { StateCode = "CT", StateName = "Connecticut" },
                new StateProvince() { StateCode = "DE", StateName = "Delaware" },
                new StateProvince() { StateCode = "DC", StateName = "District Of Columbia" },
                new StateProvince() { StateCode = "FL", StateName = "Florida" },
                new StateProvince() { StateCode = "GA", StateName = "Georgia" },
                new StateProvince() { StateCode = "HI", StateName = "Hawaii" },
                new StateProvince() { StateCode = "ID", StateName = "Idaho" },
                new StateProvince() { StateCode = "IL", StateName = "Illinois" },
                new StateProvince() { StateCode = "IN", StateName = "Indiana" },
                new StateProvince() { StateCode = "IA", StateName = "Iowa" },
                new StateProvince() { StateCode = "KS", StateName = "Kansas" },
                new StateProvince() { StateCode = "KY", StateName = "Kentucky" },
                new StateProvince() { StateCode = "LA", StateName = "Louisiana" },
                new StateProvince() { StateCode = "ME", StateName = "Maine" },
                new StateProvince() { StateCode = "MD", StateName = "Maryland" },
                new StateProvince() { StateCode = "MA", StateName = "Massachusetts" },
                new StateProvince() { StateCode = "MN", StateName = "Minnesota" },
                new StateProvince() { StateCode = "MS", StateName = "Mississippi" },
                new StateProvince() { StateCode = "MO", StateName = "Missouri" },
                new StateProvince() { StateCode = "NE", StateName = "Nebraska" },
                new StateProvince() { StateCode = "NV", StateName = "Nevada" },
                new StateProvince() { StateCode = "NH", StateName = "New Hampshire" },
                new StateProvince() { StateCode = "NJ", StateName = "New Jersey" },
                new StateProvince() { StateCode = "NM", StateName = "New Mexico" },
                new StateProvince() { StateCode = "NY", StateName = "New York" },
                new StateProvince() { StateCode = "ND", StateName = "North Dakota"},
                new StateProvince() { StateCode = "OH", StateName = "Ohio" },
                new StateProvince() { StateCode = "OK", StateName = "Oklahoma" },
                new StateProvince() { StateCode = "OR", StateName = "Oregon" },
                new StateProvince() { StateCode = "PA", StateName = "Pennsylvania" },
                new StateProvince() { StateCode = "RI", StateName = "Rhode Island" },
                new StateProvince() { StateCode = "SC", StateName = "South Carolina" },
                new StateProvince() { StateCode = "SD", StateName = "South Dakota" },
                new StateProvince() { StateCode = "TN", StateName = "Tennessee" },
                new StateProvince() { StateCode = "TX", StateName = "Texas" },
                new StateProvince() { StateCode = "UT", StateName = "Utah" },
                new StateProvince() { StateCode = "VT", StateName = "Vermont" },
                new StateProvince() { StateCode = "VA", StateName = "Virginia" },
                new StateProvince() { StateCode = "WA", StateName = "Washington" },
                new StateProvince() { StateCode = "WV", StateName = "West Virginia" },
                new StateProvince() { StateCode = "WI", StateName = "Wisconsin" },
                new StateProvince() { StateCode = "WY", StateName = "Wyoming" }
            };
            return states;
        }
