    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.237
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    namespace MyNamespace {
        using System;
        using System.Linq.Expressions;
        
        
        public class MyNewClass<TWheel> : TestInterface<TWheel>, TestBaseClass<TWheel>
         {
            
            public MyNamespace.ICar Drive<TCar>(Expression<Func<TWheel, bool>> wheels, int miles)
             {
                return base.Drive(wheels, miles);
            }
        }
    }
