    AllTypes.FromAssemblyContaining<UserService>()
        .Where(type => type.Name.EndsWith("Service")
            && typeof(IUserService).IsAssignableFrom(type))
        .WithService.DefaultInterface()
        .Configure(c => c.LifeStyle.Singleton)
