    ICollideablePlayer:ICollideable
    {
       //DependenciesHere
       HandlePlayerCollision(ICollideable)
       { 
           HandleDifferently
           {
           }
           ICollideable
           {
               //DependenciesHere
               HandleCollision(ICollideable)
           }
        }
    }
