	    public class ClassName
        {
            ........
            ........
            private IHubContext _hub;
            public BulletinSenderController(IConnectionManager connectionManager)
            {
                _hub = connectionManager.GetHubContext<McpHub>();
                ........
                ........
            }
            ............
            ............
        }
