    for()
    {
        if(!email)
        {
            Alert();
        }
        else
        {
            EnterUserDetailsInTable();
        }
        if(!group)
        {
            Alert();
        }
        else
        {
            EnterGroupDetailsInTable();
        }
    }
    if(email && group)
    {
        PushToServer();
    }
