        public class myClass
        {
            ....
            ....
            public object this[string propertyname]
            {
                get { /*use reflection to return property value, so Object*/ }
               
            }
            ....
            ....
        }
