    using System;
    using System.IO;
    using System.Xml;
    using System.Xml.Schema;
    class Script
    {
    	public static void Main()
    	{
    		// Enter your code below
    		// Generated by QTAssistant (http://www.paschidev.com)
    		XmlSchemaSet xset = new XmlSchemaSet();
    		
    		// One way of doing using an XmlReader - it'll work with relative URIs.
    		using(XmlReader reader = XmlReader.Create(@"D:\...\...\Redefine.xsd"))
    		{
    			xset.Add(XmlSchema.Read(reader, null));
    		}
    		
    		// The other way, using stream, requires all external URIs - xsd:include,     xsd:import and xsd:redefine 
    		// to be absolute
    		//xset.Add(XmlSchema.Read(File.Open(@"D:\...\...\Redefine.xsd", FileMode.Open), null));
    		
    		xset.Compile();
    		Console.WriteLine(xset.IsCompiled);
    		foreach(XmlSchemaType type in xset.GlobalTypes.Values) 
    		{
    			Console.WriteLine("QN: {0}, SourceUri: {1}", type.QualifiedName,     type.SourceUri);
    		}
    	}
    }
