	<#+
		public string GenerateInterfaceDataObject(sqlTable table)
		{
			string ifaceName = "I" + table.ObjectName;
			if (table.GenerateInterfaceObjectAsBase)
			{
				ifaceName += "Base";
			}
	#>
	using System;
	namespace <#= InterfaceNamespace #>
	{
		public interface <#= ifaceName #>
		{
	<#+
			foreach(sqlColumn col in table.Columns)
			{
	#>
			<#= GetColumnCSharpDataType(col) #> <#= col.FieldName #> { get; }
	<#+
			}
	#>
		}
	}
	<#+
			return RootPath + @"\AutoGenerated\" + ifaceName + ".cs";
		}
	#>
