            int a = Int32.MaxValue;
            Console.WriteLine(a);
            a++;
            Console.WriteLine(a);
            short b = Int16.MaxValue;
            Console.WriteLine(b);
            b++;
            Console.WriteLine(b);
            long c = Int64.MaxValue;
            Console.WriteLine(c);
            c++;
            Console.WriteLine(c);
