                ListBox lb = new ListBox();
                lb.Margin = new Thickness(0, 0, -12, 0);
                TextBlock tb = new TextBlock();
                tb.Text = App.Accounts.Items[i].Description;
                tb.FontSize = 32;
                tb.TextAlignment = TextAlignment.Center;
                tb.Width = 455;
                ToggleSwitch signOn = new ToggleSwitch();
                signOn.Tag = i.ToString();
                signOn.Header = "Signed On";
                signOn.IsChecked = App.Accounts.Items[i].SignedOn;
                signOn.Checked += new EventHandler<RoutedEventArgs>(signOn_Checked);
                signOn.Unchecked += new EventHandler<RoutedEventArgs>(signOn_Unchecked);
                signOn.Width = 455;
                ToggleSwitch invisLogin = new ToggleSwitch();
                invisLogin.Tag = i.ToString();
                invisLogin.Header = "Invisible Login";
                invisLogin.IsChecked = App.Accounts.Items[i].InvisibileLogin;
                invisLogin.Checked += new EventHandler<RoutedEventArgs>(invisLogin_Checked);
                invisLogin.Unchecked += new EventHandler<RoutedEventArgs>(invisLogin_Unchecked);
                invisLogin.Width = 455;
                ToggleSwitch wpLogin = new ToggleSwitch();
                wpLogin.Tag = i.ToString();
                wpLogin.Header = "Show as Windows Phone 7";
                wpLogin.IsChecked = App.Accounts.Items[i].InvisibileLogin;
                wpLogin.Checked += new EventHandler<RoutedEventArgs>(wpLogin_Checked);
                wpLogin.Unchecked += new EventHandler<RoutedEventArgs>(wpLogin_Unchecked);
                wpLogin.Width = 455;
                lb.Items.Add(tb);
                lb.Items.Add(signOn);
                lb.Items.Add(invisLogin);
                lb.Items.Add(wpLogin);
                pvItem.Content = lb;
