    var result = new TableName();
    using(var db = new EFObjectContext)
    {
        var query = db.TableName;
        query = value1 == null 
            ? query.Where(tbl => tbl.entry1 == null) 
            : query.Where(tbl => tbl.entry1 == value1);
        query = value2 == null 
            ? query.Where(tbl => tbl.entry2 == null) 
            : query.Where(tbl => tbl.entry2 == value2);
        
        result = query
            .Select(tbl => tbl)
            .FirstOrDefault();
       // Inspect the value of the trace variable below to see the sql generated by EF
       var trace = ((ObjectQuery<REF_EQUIPMENT>) query).ToTraceString();
    }
    return result;
