        private static bool AreWordFilesSame(byte[] wordA, byte[] wordB)
        {
            using (var streamA = new MemoryStream(wordA))
            using (var streamB = new MemoryStream(wordB))
            using (var zipA = new ZipArchive(streamA))
            using (var zipB = new ZipArchive(streamB))
            {
                streamA.Seek(0, SeekOrigin.Begin);
                streamB.Seek(0, SeekOrigin.Begin);
                
                for(int i = 0; i < zipA.Entries.Count; ++i)
                {
                    Assert.AreEqual(zipA.Entries[i].Name, zipB.Entries[i].Name);
                    if (zipA.Entries[i].Name.EndsWith(".rels")) //These are some weird word files with autogenerated hashes
                    {
                        continue;
                    }
                    var streamFromA = zipA.Entries[i].Open();
                    var streamFromB = zipB.Entries[i].Open();
                    using (var readerA = new StreamReader(streamFromA))
                    using (var readerB = new StreamReader(streamFromB))
                    {
                        var bytesA = readerA.ReadToEnd();
                        var bytesB = readerB.ReadToEnd();
                        if (bytesA != bytesB || bytesA.Length == 0)
                        {
                            return false;
                        }
                    }
                }
                return true;
            }
        }
