    /// <summary>
    /// Performs a custom action: ...
    /// </summary>
    /// <param name="x">
    /// An integer representing the ...
    /// </param>
    /// <param name="y">
    /// A boolean representing the ...
    /// </param>
    public void MyMethod(int x, bool y) {
        //...
    }
