java
db.Book.aggregate({
    "$geoNear": {
        "near": {
            "type": "Point",
            "coordinates": [
                48.857908,
                2.295243
            ]
        },
        "distanceField": "SearchResult.DistanceKM",
        "spherical": true,
        "maxDistance": NumberInt("20000"),
        "includeLocs": "SearchResult.Location"
    }
})
the above query was generated by the following MongoDB.Entities code:
csharp
using MongoDB.Driver;
using MongoDB.Entities;
using System.Collections.Generic;
namespace StackOverflow
{
    public class Program
    {
        public class Book : Entity
        {
            public string Title { get; set; }
            public List<City> CitiesInBook { get; set; } = new List<City>();
            public SearchResult SearchResult { get; set; }
        }
        public class City
        {
            public string Name { get; set; }
            public Coordinates2D Location { get; set; }
        }
        public class SearchResult
        {
            public Coordinates2D Location { get; set; }
            public double DistanceKM { get; set; }
        }
        static void Main(string[] args)
        {
            //connect to mongodb
            new DB("test");
            //create a geo2dsphere index with key "CitiesInBook.Location"
            DB.Index<Book>()
              .Key(x => x.CitiesInBook[-1].Location, KeyType.Geo2DSphere)
              .Create();
            //create 3 locations
            var paris = new City
            {
                Name = "paris",
                Location = new Coordinates2D(48.8539241, 2.2913515)
            };
            var versailles = new City
            {
                Name = "versailles",
                Location = new Coordinates2D(48.796964, 2.137456)
            };
            var poissy = new City
            {
                Name = "poissy",
                Location = new Coordinates2D(48.928860, 2.046889)
            };
            //create a book and add two cities to it
            var book = new Book { Title = "the power of now" };
            book.CitiesInBook.Add(paris);
            book.CitiesInBook.Add(poissy);
            book.Save();
            var eiffelTower = new Coordinates2D(48.857908, 2.295243);
            //find all books that have places within 20km of eiffel tower.
            var books = DB.GeoNear<Book>(
                            NearCoordinates: eiffelTower,
                            DistanceField: b => b.SearchResult.DistanceKM,
                            IncludeLocations: b => b.SearchResult.Location,
                            MaxDistance: 20000)
                          .ToList();
        }
    }
}
