    DataTable dt = new DataTable();
    dt.Columns.Add("Student");
    dt.Columns.Add("Course1");
    dt.Columns.Add("Course2");
    dt.Columns.Add("Course3");
    dt.Columns.Add("Course4");
    dt.Columns.Add("Course5");
    DataRow dr = dt.NewRow();
    object[] rowarray = new object[6];
    rowarray[0] = "Paul";
    rowarray[1] = 8;
    rowarray[2] = 2;
    rowarray[3] = 10;
    rowarray[4] = 10;
    rowarray[5] = 4;
    dr.ItemArray = rowarray;
    int[] i_test = max_min_rowvalue(dr);
    Debug.WriteLine(i_test[0]);
    Debug.WriteLine(i_test[1]);
