    public partial class MyForm : Form
    {
        // Constructor (normally generated by Visual Studio)
        public MyForm()
        {
            InitializeComponent();
        }
        // Create, and initialize the variable outside the method.
        private int _numberOfHuts = 0;
  
        // When clicking the button, the variable is incremented
        // and the label is updated with the new value.
        private void Button1_Click(object sender, EventArgs e) 
        {
            _numberOfHuts++;
            label1.Text = numberOfHuts.ToString();
        }
    }
