    public List<CharEquipGenre> equipment_genres => new List<CharEquipGenre>(GetComponents<CharEquipGenre>());
Although a slightly "better" design would be exposing `IEnumerable`:
    public IEnumerable<CharEquipGenre> EquipmentGenres => ...
    // or
    public IEnumerable<CharEquipGenre> GetEquipmentGenres() => ...
