    /// <auto-generated />
    public partial class MyClass
    {
        public int Num1 { get; set; }
        
        public int Num2 { get; set; }
        
        public string Str1 { get; set; }
        
        public string Str2 { get; set; }
    }
