    <DataGrid ItemsSource="{Binding Path=TableView}" CanUserAddRows="False"
              AutoGeneratedColumns="DataGrid_AutoGeneratedColumns">
        <DataGrid.Columns>
            <DataGridTemplateColumn Header="Add">
                <DataGridTemplateColumn.CellTemplate>
                    <DataTemplate>
                        <Button Command="{Binding RelativeSource={RelativeSource AncestorType={x:Type DataGrid}}, Path=DataContext.AddItemCommand}" >Add</Button>
                    </DataTemplate>
                </DataGridTemplateColumn.CellTemplate>
            </DataGridTemplateColumn>
        </DataGrid.Columns>
    </DataGrid>
