    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Data;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;
    using System.Windows.Forms;
    using System.Xml;
    namespace Dynamic.Script_8D737880D773F26
    {
        // Script generated by Pega Robotics Studio 8.0.2032.0
        // Please use caution when modifying class name, namespace or attributes
        [OpenSpan.TypeManagement.DynamicTypeAttribute()]
        [OpenSpan.Design.ComponentIdentityAttribute("Script-8D737880D773F26")]
        public sealed class Script
        {
            [DllImport("user32.dll", EntryPoint = "FindWindow", SetLastError = true)]
            static extern IntPtr FindWindowByCaption(IntPtr zeroOnly, string lpWindowName);
        } // << Your class ends here
        { // << Opened brackets without declaring a class
            public bool ScriptErrorVisible()
            {
                if (FindWindowByCaption(IntPtr.Zero, "Script Error") != IntPtr.Zero)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        } // << This would close the class, but you haven't declared one
    } // << This ends the namespace
