    public void ConfigureServices(IServiceCollection services)
    {
        ...   
        services.TryAddEnumerable(ServiceDescriptor.Transient<IApplicationModelProvider, ProduceResponseTypeModelProvider>());
        ...
    }
