    static public explicit operator T(Variable<T> value)
    static public explicit operator Variable<T>(T value)
    public bool Equals(Variable<T> value)
    static public bool operator ==(Variable<T> v1, Variable<T> v2)
    static public bool operator ==(Variable<T> v1, object v2)
    static public bool operator ==(object v1, Variable<T> v2)
    static public bool operator !=(Variable<T> v1, Variable<T> v2)
    static public bool operator !=(Variable<T> v1, object v2)
    static public bool operator !=(object v1, Variable<T> v2)
