    static public explicit operator T(Variable value)
    static public explicit operator Variable(T value)
    public override int GetHashCode()
    public virtual object Clone()
    public override bool Equals(object value)
    public bool Equals(T value)
    public bool Equals(Variable value)
    public bool ToBoolean(IFormatProvider provider)
    public byte ToByte(IFormatProvider provider)
    public char ToChar(IFormatProvider provider)
    public DateTime ToDateTime(IFormatProvider provider)
    public decimal ToDecimal(IFormatProvider provider)
    public double ToDouble(IFormatProvider provider)
    public short ToInt16(IFormatProvider provider)
    public int ToInt32(IFormatProvider provider)
    public long ToInt64(IFormatProvider provider)
    public sbyte ToSByte(IFormatProvider provider)
    public float ToSingle(IFormatProvider provider)
    public string ToString(IFormatProvider provider)
    public object ToType(Type conversionType, IFormatProvider provider)
    public ushort ToUInt16(IFormatProvider provider)
    public uint ToUInt32(IFormatProvider provider)
    public ulong ToUInt64(IFormatProvider provider)
    public TypeCode GetTypeCode()
    static public bool operator ==(Variable v1, Variable v2)
    static public bool operator ==(Variable v1, object v2)
    static public bool operator ==(object v1, Variable v2)
    static public bool operator !=(Variable v1, Variable v2)
    static public bool operator !=(Variable v1, object v2)
    static public bool operator !=(object v1, Variable v2)
    public virtual int CompareTo(object obj)
    static public bool operator <(Variable v1, Variable v2)
    static public bool operator <(Variable v1, T v2)
    static public bool operator <(T v1, Variable v2)
    static public bool operator >(Variable v1, Variable v2)
    static public bool operator >(Variable v1, T v2)
    static public bool operator >(T v1, Variable v2)
    static public bool operator <=(Variable v1, Variable v2)
    static public bool operator <=(Variable v1, T v2)
    static public bool operator <=(T v1, Variable v2)
    static public bool operator >=(Variable v1, Variable v2)
    static public bool operator >=(Variable v1, T v2)
    static public bool operator >=(T v1, Variable v2)
    static public Variable operator +(Variable v1, Variable v2)
    static public Variable operator +(Variable v1, T v2)
    static public Variable operator +(T v1, Variable v2)
    static public Variable operator -(Variable v1, Variable v2)
    static public Variable operator -(Variable v1, T v2)
    static public Variable operator -(T v1, Variable v2)
    static public Variable operator *(Variable v1, Variable v2)
    static public Variable operator *(Variable v1, T v2)
    static public Variable operator *(T v1, Variable v2)
    static public Variable operator /(Variable v1, Variable v2)
    static public Variable operator /(Variable v1, T v2)
    static public Variable operator /(T v1, Variable v2)
