            SqlDataSource dsDepartment = new SqlDataSource();
            dsDepartment.ID = "dsDepartment";
            this.Page.Controls.Add(dsDepartment);
            dsDepartment.ConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            dsDepartment.SelectCommand = "SELECT [DEPARTMENT_CODE], [DEPARTMENT_NAME] FROM [TV_DEPTNAME]";
            drpDepartment.DataSource = dsDepartment;
            drpDepartment.DataTextField = "DEPARTMENT_NAME";
            drpDepartment.DataValueField = "DEPARTMENT_CODE";
            drpDepartment.DataBind();
            SqlDataSource dsCharge = new SqlDataSource();
            dsCharge.ID = "dsCharge";
            this.Page.Controls.Add(dsCharge);
            dsCharge.ConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            dsCharge.SelectCommand = "SELECT [OFFENSE_CODE], [OFFENSE_DESCRIPTION] FROM [TV_OFFENSE]";
            drpCharge.DataSource = dsCharge;
            drpCharge.DataTextField = "OFFENSE_DESCRIPTION";
            drpCharge.DataValueField = "OFFENSE_CODE";
            drpCharge.DataBind();
            SqlDataSource dsRecentCases = new SqlDataSource();
            dsRecentCases.ID = "dsRecentCases";
            this.Page.Controls.Add(dsRecentCases);
            dsRecentCases.ConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;
            dsRecentCases.SelectCommand = "SELECT TOP 10 C.CASE_KEY, C.DEPARTMENT_CASE_NUMBER,D.DEPARTMENT_NAME, O.OFFENSE_DESCRIPTION AS CHARGE, LAB_CASE, OFFENSE_DATE FROM TV_LABCASE C INNER JOIN TV_DEPTNAME D ON C.DEPARTMENT_CODE = D.DEPARTMENT_CODE  INNER JOIN TV_OFFENSE O ON C.OFFENSE_CODE = O.OFFENSE_CODE ORDER BY CASE_DATE";
            grdRecentCases.DataSource = dsRecentCases;
            grdRecentCases.DataBind();
