        public void ConfigureServices(IServiceCollection services)
        {
                services.AddControllers();
                ...
                ...
                //
                services.Configure<ApiSettings>(Configuration);
                services.AddTransient<IInfraApp, InfraApp>();
                ...
                ...
                //get instance of infraapp:
                var provider = services.BuildServiceProvider();
                var infraapp = provider.GetService<IInfraApp>();
                //
                ...
                ...
        }
