    Encoding enc = Encoding.GetEncoding("utf-8");
    ...
    using (WebResponse Serviceres = request.GetResponse())
    {
      using (StreamReader rd = new StreamReader(Serviceres.GetResponseStream(), enc))
      {
        string ServiceResult = rd.ReadToEnd();
        ...
        ...
        ...
      }
    }
    ...
