    public class B {
    
        public A myA { get; } // This should be public
    
        public B(A a) {
            myA = a;
        }
    }
    
    public class A {
    
        public B myB { get; } // I don't get the point of having a private autogenerated property
    
        public A() {
            myB = new B(this);
        }
    }
