    class B <InnerType>
    {
     ...
        public T1<InnerType> Sub1 { get; set; }
     ...
    }
    class T1 <InnerType>
    {
     ...
        public T2<InnerType> Sub2 { get; set; }
     ...
    }
    class T2<InnerType>
    {
     ...
        public InnerType Sub3 { get; set; }
     ...
    }
