    private static void MyRoutine() {
      //TODO: Extracted business logic here
      ... 
    }
    ...
    private static void Main(string[] args) {
      ...
      MyRoutine();
      ...
    }
   
    ...
    private static void MyOtherMethod() {
      ...
      MyRoutine();
      ...
    } 
 
