    using System.Linq;
    ...
    private static void Main(string[] args) {
      ...
    } 
    ...
    private static void MyOtherMethod() {
      ...
      // Call Main with the same arguments as OS has done it
      Main(Environment.GetCommandLineArgs().Skip(1).ToArray());
      ...
    }
