    public async Task<Foo> DoSomethingElse(CancellationToken token) {
        ...
        if (token.IsCancellationRequested) {
            // stop what you are doing...
            // I can't tell you how to implement this without seeing how DoSomethingElse is implemented
        }
        ...
    }
