                                            year = receiveMessage[4];
                                            month = receiveMessage[5];
                                            day = receiveMessage[6];
                                            hour = receiveMessage[7];
                                            minute = receiveMessage[8];
                                            second = receiveMessage[9];
                                            date = new DateTime(2000 + year, month, day, hour, minute, second);
                                            WriteDBMessageLocation locationMessage = new WriteDBMessageLocation();
                                            locationMessage.message = DATABASE_MESSAGE_TYPE.LOCATION;
                                            locationMessage.trackTime = date;
                                            locationMessage.currTime = DateTime.Now;
                                            locationMessage.lattitude = new byte[4];
                                            Array.Copy(receiveMessage, 11, locationMessage.lattitude, 0, 4);
                                            locationMessage.longitude = new byte[4];
                                            Array.Copy(receiveMessage, 15, locationMessage.longitude, 0, 4);
                                            locationMessage.speed = receiveMessage[19];
                                            locationMessage.courseStatus = new byte[2];
                                            Array.Copy(receiveMessage, 20, locationMessage.courseStatus, 0, 2);
                                            locationMessage.IMEI = byteState.Value.IMEI;
                                            WriteDBAsync.ReadWriteFifo(WriteDBAsync.Mode.WRITE, locationMessage);
