    public class DynamicRepositories 
    {
        public static Command<IDispatchingRepository> Dispatching= (o) => ....
        public static Command<IDispatchingRepository> Scheduling = (o) => ....
    }
