            DateTime now = DateTime.Now;
            string firstPart = now.ToString("yyyy-MM-dd");
            string hours = now.ToString("HH");
            string minutes = now.ToString("mm");
            string seconds = now.ToString("ss");
            Console.Write("Current Date and Time is ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write(":");
            Console.ResetColor();
            Console.Write(firstPart + " ");
            Console.Write(hours);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write(":");
            Console.ResetColor();
            Console.Write(minutes);
            Console.BackgroundColor = ConsoleColor.Red;
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write(":");
            Console.ResetColor();
            Console.Write(seconds);
            Console.ReadLine();
