    public class DataContextA : IDataContext
    {
         public async Task<string> Get<string>() => ...
         public async Task Delete() => ...
    }
    
    public class DataContextB : IDataContext
    {
        public async Task<int> Get<int>() => ...
        public async Task Delete() => ...
    }
