    var containerGroup = azure.ContainerGroups.Define(containerGroupName)
        .WithRegion(azureRegion)
        .WithExistingResourceGroup(resourceGroupName)
        .WithLinux()
        .WithPublicImageRegistryOnly()
        .WithoutVolume()
        .DefineContainerInstance(containerGroupName)
             .WithImage(containerImage)
             .WithExternalTcpPort(80)
             .WithCpuCoreCount(1.0)
             .WithMemorySizeInGB(1)
             .Attach()
        .WithDnsPrefix(containerGroupName)
        .Create();
