    questionTimer.Start(); //Start question timer...
    Console.Write("What is 5+5? "); //Ask the question...
    string ans = Console.ReadLine(); //Get the user input...
    if (ans == "10")
    {
        //If it's correct stop timing...
        Console.WriteLine("Correct!");
        questionTimer.Stop();
    }
