        public ActionResult actionEditStuff(....parameters...)
        {
                ...
                ...do your magic ...
                return PartialView("~/Views/_PartialViewThatShowsSomething.cshtml", ...pass model...);
        }
