    public void ConfigureServices(IServiceCollection services)
    {
        ...
        ...
        services.AddApplicationInsightsTelemetry();
    
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        services.AddSingleton<ITelemetryInitializer, TelemetryEnrichment>();
        ...
        ...
    }
