    // ...
    using (SqlCeCommand com = 
        new SqlCeCommand("SELECT Result FROM RamResults WHERE Date = @date", con))
    {
        com.Parameters.Add(new SqlParameter("date", Form1.date));
        // ...
    }
    // ...
