    // ... as the application is closing ...
    // Store the state of the check box
    System.IO.File.WriteAllText(@"C:\AppFile.txt", this.CheckBox1.IsChecked.ToString());
    // ...
    // ... as the application is being initialized ...
    // Read the state of the check box
    string value = System.IO.File.ReadAllText(@"C:\AppFile.txt");
    this.CheckBox1.IsChecked = bool.Parse(value);
