    SmtpClient client = new SmtpClient();
	client.Port =  587;
	client.Host = "smtp.gmail.com";
	client.EnableSsl = true;
	client.Timeout = 10000;
	client.DeliveryMethod = SmtpDeliveryMethod.Network;
	client.UseDefaultCredentials = false;
	client.Credentials = new System.Net.NetworkCredential("<me>@gmail.com", "<my pw>");
	MailMessage mm = new MailMessage(from_addr_text, to_addr_text, msg_subject, msg_body);
	mm.BodyEncoding = UTF8Encoding.UTF8;
	mm.DeliveryNotificationOptions = DeliveryNotificationOptions.OnFailure;
	client.Send(mm);
