    Action                'public delegate void Action()
    Action<T>             'public delegate void Action<T>(T obj)
    Action<T1,T2>         'public delegate void Action<T1,T2>(T1 arg1, T2 arg2)
    Action<T1,T2,T3>      'public delegate void Action<T1,T2,T3>(T1 arg1, T2 arg2, T3 arg3)
    Action<T1,T2,T3,T4>   'public delegate void Action<T1,T2,T3,T4>(T1 arg1, T2 arg2, T3 arg3, T4 arg4)
