    System.Type
      System.RuntimeType
      System.ReflectionOnlyType
      System.Reflection.Emit.EnumBuilder
      System.Reflection.Emit.GenericTypeParameterBuilder
      System.Reflection.Emit.SymbolType
      System.Reflection.Emit.TypeBuilder
      System.Reflection.Emit.TypeBuilderInstantiation
      System.Reflection.TypeDelegator
