    public class ClientGroupDetails
    {
        public DateTime? Col2;
        ...    
        public ClientGroupDetails(DateTime? m_Col2, ...
        {
            Col2 = m_Col2;
            ...
        }   
        ...
    }
