    protected override void Draw(GameTime cGameTime) 
    {
            GraphicsDevice.SetRenderTarget(null); 
            GraphicsDevice.Clear(Color.Black); 
            ....
            ....
            ....
