	class AutoGeneratedShipData
	{
		public AutoGeneratedShipData(XmlDocument xmlDoc)
		{
			// Code initialization like in your sample
		}
		public string Name ...
		public string Base_type ...
		public string GFX ...
	}
