    foreach (string sendTo in emailList)
    {
        // construct email fields ...
        // ...
        foreach (string sendAttachments in attachList)
        {
            mail.Attachments.Add(new Attachment(sendAttachments));
        }
        // send email ...
        // ...
    }
