    var items = LoadItemsFromUnderlyingDataStore();
    itemsDataGrid.ItemsSource = items;
    private void ItemsDataGridExportButton_Click(object sender, EventArgs e) {
        var filename = AutoGenerateDateTimedFileName();
        using (var csv = new FileStream(filename)) {
            // if you want any column header in your Excel file, uncomment line below.            
            //csv.WriteLine("Column1,Column2,Column3,Column4");
            items.ForEach(item => 
                csv.WriteLine("{0},{1},{2},{3}"
                    , item.PropertyFromFirstColumn
                    , item.PropertyFromSecondColumn
                    , item.PropertyFromThirdColumn
                    , item.PropertyFromFourthColumn);
            try { csv.Flush(); }
            catch(IOException ex) { 
                // Handle error (log, whatever...)
                throw; // If you need to let the exception bubble up...
            }
        }
    }
    private string AutoGenerateDateTimedFileName() {
        return string.Format("DataGridExport_{0}_{1}.csv"
            , DataTime.Today.ToShortDateString()
            , DateTime.Now.ToLongTimeString());
    }
