    public TweetSearchCache() : base(CreateAuth()) {
    // ...
    }
    
    public static SingleUserAuthorizer CreateAuth() {
        SingleUserAuthorizer createdAuth = ...
        // ...
        return createdAuth;
    }
