    Foo foo;
    if (dictionary.TryGetValue(key, out foo))
    {
       return foo;  // cache hit
    }
    
    foo = GenerateNewObject(); 
    
    if (!ValidateFoo(foo))
    {
       // Generate a valid foo some other way? 
    }
    return dictionary.GetOrAdd(key, foo); // Potential to use the validated value generated by another thread.  
