    //Other half is autogenerated by EF in models folder
    public partial class Question
    {
        public List<QuestionExtendedProp> TemporaryExtendedProperties { get; set; }
    }
    //Other half is autogenerated by EF in models folder
    public partial class QuestionExtendedProp
    {
        public string DictionaryKeyValue { get; set; }
    }
