    <root>
      <Group>
        <TimeAdded>2012-04-27T10:23:50.7153613+01:00</TimeAdded>
        <GroupName>Group</GroupName>
        <GroupHeader>Header</GroupHeader>
        <GroupMessages>
          <Message>
            <MessageID>1</MessageID>
            <GroupMessage>Message</GroupMessage>
            <MessageGroup/>
          </Message>
        </GroupMessages>
      </Group>
      <Group>
        <TimeAdded>2012-04-27T10:23:50.7153613+01:00</TimeAdded>
        <GroupName>Group</GroupName>
        <GroupHeader>Header</GroupHeader>
        <GroupMessages>
          <Message>
            <MessageID>1</MessageID>
            <GroupMessage>Message</GroupMessage>
            <MessageGroup/>
          </Message>
        </GroupMessages>
      </Group>
    </root>
