    public class ObjectResult
    {
        //...
        public static ObjectResult From<T>(T arg) { return new ObjectResult<T>(arg); }
        //...
    }
    public class ObjectResult<T> : ObjectResult
    {
        //...
        public ObjectResult(T obj) { /* ... some implementation ... */ }
        //...
    }
