    Red Small Cotton
    Red Small Silk
    Red Med Cotton
    Red Med Silk
    Red Large Cotton
    Red Large Silk
    Blue Small Cotton
    Blue Small Silk
    Blue Med Cotton
    Blue Med Silk
    Blue Large Cotton
    Blue Large Silk
    Green Small Cotton
    Green Small Silk
    Green Med Cotton
    Green Med Silk
    Green Large Cotton
    Green Large Silk
