    [Flags]
    public enum COURSECOMPONENT_T : int
    {
        Everything = -1,
        Nothing = 0,
        AttendanceRegisters = 1,
        Checklists = 2 * AttendanceRegisters,
        Competencies = 2 * Checklists,
        Content = 2 * Competencies,
        CourseFiles = 2 * Content,
        Discussions = 2 * CourseFiles,
        DisplaySettings = 2 * Discussions,
        Dropbox = 2 * DisplaySettings,
        Faq = 2 * Dropbox,
        Forms = 2 * Faq,
        Glossary = 2 * Forms,
        Grades = 2 * Glossary,
        GradesSettings = 2 * Grades,
        Groups = 2 * GradesSettings,
        Homepages = 2 * Groups,
        IntelligentAgents = 2 * Homepages,
        Links = 2 * IntelligentAgents,
        LtiLink = 2 * Links,
        LtiTP = 2 * LtiLink,
        Navbars = 2 * LtiTP,
        News = 2 * Navbars,
        QuestionLibrary = 2 * News,
        Quizzes = 2 * QuestionLibrary,
        ReleaseConditions = 2 * Quizzes,
        Rubrics = 2 * ReleaseConditions,
        Schedule = 2 * Rubrics,
        SelfAssessments = 2 * Schedule,
        Surveys = 2 * SelfAssessments,
        ToolNames = 2 * Surveys,
        Widgets = 2 * ToolNames,
    }
