        <View>
            <Name>Microsoft.Exchange.Management.RecipientTasks.MailboxAcePresentationObject</Name>
            <ViewSelectedBy>
                <TypeName>Microsoft.Exchange.Management.RecipientTasks.MailboxAcePresentationObject</TypeName>
            </ViewSelectedBy>
            <TableControl>
                <TableHeaders>
                    <TableColumnHeader>
                        <Label>Identity</Label>
                        <Width>20</Width>
                    </TableColumnHeader>
                    <TableColumnHeader>
                        <Label>User</Label>
                        <Width>20</Width>
                    </TableColumnHeader>
                    <TableColumnHeader>
                        <Label>AccessRights</Label>
                    </TableColumnHeader>
                    <TableColumnHeader>
                        <Label>IsInherited</Label>
            <Width>11</Width>
                    </TableColumnHeader>
                    <TableColumnHeader>
                        <Label>Deny</Label>
                        <Width>5</Width>
                    </TableColumnHeader>
                </TableHeaders>
                <TableRowEntries>
                    <TableRowEntry>
                        <TableColumnItems>
                            <TableColumnItem>
                                <PropertyName>Identity</PropertyName>
                            </TableColumnItem>
                            <TableColumnItem>
                                <PropertyName>User</PropertyName>
                            </TableColumnItem>
                            <TableColumnItem>
                                <PropertyName>AccessRights</PropertyName>
                            </TableColumnItem>
                            <TableColumnItem>
                                <PropertyName>IsInherited</PropertyName>
                            </TableColumnItem>
                            <TableColumnItem>
                                <PropertyName>Deny</PropertyName>
                            </TableColumnItem>
                        </TableColumnItems>
                    </TableRowEntry>
                </TableRowEntries>
            </TableControl>
        </View>
