    public class Patient
    {
        ...    
        public virtual ICollection<Hospital> Hospitals { get; set; }    
        ...
    }
    public class Hospital
    {
        ...    
        public virtual ICollection<Patient> Patients { get; set; }    
        ...
    }
