       TestRootObject testRootObject = new TestRootObject();
        ......................
        ..............YOUR CODE..............
        ..................
        System.Web.Script.Serialization.JavaScriptSerializer oSerializer = 
                 new System.Web.Script.Serialization.JavaScriptSerializer();
        return oSerializer.Serialize(testRootObject);
