                DataTable studentInfo = new DataTable("studentinfo");
            DataColumn StudentID = new DataColumn("studentID");
            StudentID.DataType = typeof(int);
            StudentID.Caption = "StudentID";
            StudentID.AutoIncrement = true;
            StudentID.AutoIncrementSeed = 1;
            StudentID.AutoIncrementStep = 1;
            DataColumn Name = new DataColumn("StudentName", typeof(string));
            Name.MaxLength = 50;
            Name.AllowDBNull = false;
            Name.Caption = "StudentName";
            DataColumn Roll = new DataColumn("StudentRoll", typeof(int));
            Roll.Caption = "StudnetRoll";
            studentInfo.Columns.Add(StudentID);
            studentInfo.Columns.Add(Name);
            studentInfo.Columns.Add(Roll);
            studentInfo.PrimaryKey = new DataColumn[] { StudentID };
            DataSet ds = new DataSet("dataset");
            ds.Tables.Add(studentInfo);
            var rw = ds.Tables[0].NewRow();
            rw["StudentName"] = "Badhon";
            rw["StudentRoll"] = 004;
            ds.Tables[0].Rows.Add(rw);
            MessageBox.Show(ds.Tables[0].Rows.Count.ToString());
            dataGridView1.DataSource = ds.Tables[0];
