    Syntax.CompilationUnit()
    .WithMembers(
        Syntax.List<MemberDeclarationSyntax>(
            Syntax.NamespaceDeclaration(
                Syntax.IdentifierName(
                    Syntax.Identifier(
                        @"ACO",
                        Syntax.TriviaList(
                            Syntax.Space,
                            Syntax.CarriageReturnLineFeed))))
            .WithNamespaceKeyword(
                Syntax.Token(
                    SyntaxKind.NamespaceKeyword,
                    Syntax.TriviaList(
                        Syntax.Space)))
            .WithOpenBraceToken(
                Syntax.Token(
                    SyntaxKind.OpenBraceToken,
                    Syntax.TriviaList(
                        Syntax.Space,
                        Syntax.CarriageReturnLineFeed)))
            .WithMembers(
                Syntax.List<MemberDeclarationSyntax>(
                    Syntax.ClassDeclaration(
                        Syntax.Identifier(
                            @"MainForm",
                            Syntax.TriviaList(
                                Syntax.Space)))
                    .WithModifiers(
                        Syntax.TokenList(
                            Syntax.Token(
                                Syntax.TriviaList(
                                    Syntax.Whitespace(
                                        @"    ")),
                                SyntaxKind.PublicKeyword,
                                Syntax.TriviaList(
                                    Syntax.Space))))
                    .WithKeyword(
                        Syntax.Token(
                            SyntaxKind.ClassKeyword,
                            Syntax.TriviaList(
                                Syntax.Space)))
                    .WithBaseList(
                        Syntax.BaseList(
                            Syntax.SeparatedList<TypeSyntax>(
                                Syntax.QualifiedName(
                                    Syntax.QualifiedName(
                                        Syntax.QualifiedName(
                                            Syntax.IdentifierName(
                                                Syntax.Identifier(
                                                    @"System")),
                                            Syntax.IdentifierName(
                                                Syntax.Identifier(
                                                    @"Windows")))
                                        .WithDotToken(
                                            Syntax.Token(
                                                SyntaxKind.DotToken)),
                                        Syntax.IdentifierName(
                                            Syntax.Identifier(
                                                @"Forms")))
                                    .WithDotToken(
                                        Syntax.Token(
                                            SyntaxKind.DotToken)),
                                    Syntax.IdentifierName(
                                        Syntax.Identifier(
                                            @"Form",
                                            Syntax.TriviaList(
                                                Syntax.Space,
                                                Syntax.CarriageReturnLineFeed))))
                                .WithDotToken(
                                    Syntax.Token(
                                        SyntaxKind.DotToken))))
                        .WithColonToken(
                            Syntax.Token(
                                SyntaxKind.ColonToken,
                                Syntax.TriviaList(
                                    Syntax.Space))))
                    .WithOpenBraceToken(
                        Syntax.Token(
                            Syntax.TriviaList(
                                Syntax.Whitespace(
                                    @"    ")),
                            SyntaxKind.OpenBraceToken,
                            Syntax.TriviaList(
                                Syntax.Space,
                                Syntax.CarriageReturnLineFeed)))
                    .WithMembers(
                        Syntax.List<MemberDeclarationSyntax>(
                            Syntax.PropertyDeclaration(
                                Syntax.QualifiedName(
                                    Syntax.QualifiedName(
                                        Syntax.QualifiedName(
                                            Syntax.IdentifierName(
                                                Syntax.Identifier(
                                                    @"System")),
                                            Syntax.IdentifierName(
                                                Syntax.Identifier(
                                                    @"Windows")))
                                        .WithDotToken(
                                            Syntax.Token(
                                                SyntaxKind.DotToken)),
                                        Syntax.IdentifierName(
                                            Syntax.Identifier(
                                                @"Forms")))
                                    .WithDotToken(
                                        Syntax.Token(
                                            SyntaxKind.DotToken)),
                                    Syntax.IdentifierName(
                                        Syntax.Identifier(
                                            @"Timer",
                                            Syntax.TriviaList(
                                                Syntax.Space))))
                                .WithDotToken(
                                    Syntax.Token(
                                        SyntaxKind.DotToken)),
                                Syntax.Identifier(
                                    @"Ticker",
                                    Syntax.TriviaList(
                                        Syntax.Space)))
                            .WithModifiers(
                                Syntax.TokenList(
                                    Syntax.Token(
                                        Syntax.TriviaList(
                                            Syntax.Whitespace(
                                                @"    ")),
                                        SyntaxKind.PublicKeyword,
                                        Syntax.TriviaList(
                                            Syntax.Space))))
                            .WithAccessorList(
                                Syntax.AccessorList(
                                    Syntax.List<AccessorDeclarationSyntax>(
                                        Syntax.AccessorDeclaration(
                                            SyntaxKind.GetAccessorDeclaration)
                                        .WithKeyword(
                                            Syntax.Token(
                                                SyntaxKind.GetKeyword))
                                        .WithSemicolonToken(
                                            Syntax.Token(
                                                SyntaxKind.SemicolonToken,
                                                Syntax.TriviaList(
                                                    Syntax.Space))),
                                        Syntax.AccessorDeclaration(
                                            SyntaxKind.SetAccessorDeclaration)
                                        .WithKeyword(
                                            Syntax.Token(
                                                SyntaxKind.SetKeyword))
                                        .WithSemicolonToken(
                                            Syntax.Token(
                                                SyntaxKind.SemicolonToken))))
                                .WithOpenBraceToken(
                                    Syntax.Token(
                                        SyntaxKind.OpenBraceToken))
                                .WithCloseBraceToken(
                                    Syntax.Token(
                                        SyntaxKind.CloseBraceToken,
                                        Syntax.TriviaList(
                                            Syntax.Space,
                                            Syntax.CarriageReturnLineFeed)))),
                            Syntax.MethodDeclaration(
                                Syntax.PredefinedType(
                                    Syntax.Token(
                                        SyntaxKind.VoidKeyword,
                                        Syntax.TriviaList(
                                            Syntax.Space))),
                                Syntax.Identifier(
                                    @"Main"))
                            .WithAttributes(
                                Syntax.List<AttributeDeclarationSyntax>(
                                    Syntax.AttributeDeclaration(
                                        Syntax.SeparatedList<AttributeSyntax>(
                                            Syntax.Attribute(
                                                Syntax.IdentifierName(
                                                    Syntax.Identifier(
                                                        @"STAThread")))))
                                    .WithOpenBracketToken(
                                        Syntax.Token(
                                            Syntax.TriviaList(
                                                Syntax.Space,
                                                Syntax.CarriageReturnLineFeed,
                                                Syntax.Whitespace(
                                                    @"        ")),
                                            SyntaxKind.OpenBracketToken))
                                    .WithCloseBracketToken(
                                        Syntax.Token(
                                            SyntaxKind.CloseBracketToken,
                                            Syntax.TriviaList(
                                                Syntax.Space,
                                                Syntax.CarriageReturnLineFeed)))))
                            .WithModifiers(
                                Syntax.TokenList(
                                    Syntax.Token(
                                        Syntax.TriviaList(
                                            Syntax.Whitespace(
                                                @"        ")),
                                        SyntaxKind.PublicKeyword,
                                        Syntax.TriviaList(
                                            Syntax.Space))))
                            .WithParameterList(
                                Syntax.ParameterList()
                                .WithOpenParenToken(
                                    Syntax.Token(
                                        SyntaxKind.OpenParenToken))
                                .WithCloseParenToken(
                                    Syntax.Token(
                                        SyntaxKind.CloseParenToken,
                                        Syntax.TriviaList(
                                            Syntax.Space,
                                            Syntax.CarriageReturnLineFeed))))
                            .WithBody(
                                Syntax.Block()
                                .WithOpenBraceToken(
                                    Syntax.Token(
                                        Syntax.TriviaList(
                                            Syntax.Whitespace(
                                                @"        ")),
                                        SyntaxKind.OpenBraceToken,
                                        Syntax.TriviaList(
                                            Syntax.Space,
                                            Syntax.CarriageReturnLineFeed)))
                                .WithCloseBraceToken(
                                    Syntax.Token(
                                        Syntax.TriviaList(
                                            Syntax.Whitespace(
                                                @"        ")),
                                        SyntaxKind.CloseBraceToken,
                                        Syntax.TriviaList(
                                            Syntax.Space,
                                            Syntax.CarriageReturnLineFeed))))))
                    .WithCloseBraceToken(
                        Syntax.Token(
                            Syntax.TriviaList(
                                Syntax.Whitespace(
                                    @"    ")),
                            SyntaxKind.CloseBraceToken,
                            Syntax.TriviaList(
                                Syntax.Space,
                                Syntax.CarriageReturnLineFeed)))))
            .WithCloseBraceToken(
                Syntax.Token(
                    SyntaxKind.CloseBraceToken,
                    Syntax.TriviaList(
                        Syntax.Space,
                        Syntax.CarriageReturnLineFeed)))))
    .WithEndOfFileToken(
        Syntax.Token(
            SyntaxKind.EndOfFileToken))
