    public class XmlManager
    {
        private XDocument _document1;
        private XDocument _document2;
        private string _autogenerated;
        private string _manual;
        private string _target;
        public XmlManager()
        {
            Initialize();
        }
        private void Initialize()
        {
            _autogenerated = @"c:\AutogeneratedResource.xml";
            _manual = @"c:\ManualResource.xml";
            
            XmlDocument doc = new XmlDocument();
            doc.Load(_autogenerated);
            _document1 = XDocument.Parse(doc.InnerXml);
            
            doc.Load(_manual);
            _document2 = XDocument.Parse(doc.InnerXml);
            
            _target = @"c:\Target.xml";
        }
        public void Save()
        {
            if (_document2.Root != null)
            {
                IEnumerable<XElement> elements = _document2.Root.Elements("data");
                if (_document1.Root != null)
                    _document1.Root.Add(elements);
                _document1.Save(new StreamWriter(_target));
            }
        }
    }
