    return string.Format("{0}-{1}-{2}-{3}-{4}-{5}-{6}-{7}-{8}",
                         CategoryId,
                         Size ?? "null", 
                         Colour ?? "null",
                         LowerPrice.NullStringIfZero(),
                         HigherPrice.NullStringIfZero(),
                         SortExpression ?? "null",
                         PageNumber.NullStringIfZero(),
                         PageSize.NullStringIfZero(),
                         OnlyClearance);
