    private void Form1_Load(object sender, EventArgs e)
    {
      // Transparent background...  
      pictureBoxOverlay.BackColor = Color.Transparent;
      // Change parent for overlay PictureBox...
      pictureBoxOverlay.Parent    = pictureBoxMain;
     // Change overlay PictureBox position in new parent...
     // pictureBoxOverlay.Location  = new Point(0, 0);
    }
