    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.5448
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    namespace DesignerHostSample
    {
        using System;
        using System.ComponentModel;
        using System.Windows.Forms;
        
        
        public class Form1 : System.Windows.Forms.Form
        {
            
            private System.Windows.Forms.Label label1;
            
            public Form1()
            {
                this.InitializeComponent();
            }
            
            private void InitializeComponent()
            {
                this.label1 = new System.Windows.Forms.Label();
                this.SuspendLayout();
                // 
                // label1
                // 
                this.label1.Location = new System.Drawing.Point(0, 0);
                this.label1.Name = "label1";
                this.label1.Size = new System.Drawing.Size(100, 23);
                this.label1.TabIndex = 0;
                this.label1.Text = "TEST!!!!";
                // 
                // Form1
                // 
                this.ClientSize = new System.Drawing.Size(284, 262);
                this.Name = "Form1";
                this.ResumeLayout(false);
            }
        }
    }
