    public class OrderDTO
    {
        ...
        public IList<OrderLineDTO> Lines { get; set; }
        ...
    }
    public class OrderLineDTO
    {
        public int ProductID { get; set; }
        ...
        [Range(0, 1000)]
        public int Quantity { get; set; }
        ...
    }
    ...
    @for (int i = 0; i < Model.Lines.Count; ++i)
    {
      ...
      @Html.EditorFor(x => x.Lines[i].Quantity)
      ...
    }
    ...
