            ClientContext ctx = new ClientContext("http://SiteUrl");
            Web web = ctx.Web;
            List list = web.Lists.GetByTitle("My Task List");
            ListItem listitem = list.GetItemById(1);
            listitem["Completed"] = false;
            listitem["PercentComplete"] = 1;
            listitem["Status"] = "Rejected";
            listitem["WorkflowOutcome"] = "Rejected";
            listitem.Update();
            ctx.ExecuteQuery();
