    DataGridTemplateColumn templateColumn = new DataGridTemplateColumn() { Header 
    ...
    CellTemp.Append("<CheckBox  x:Name='" + "checkBoxHeader" + "' Margin='4'  IsChecked="{Binding MyProperty, Mode=TwoWay}"/>");
    ...            
    ftrDataGrid.Columns.Add(templateColumn);
