    <#@ template debug="true" hostSpecific="true" #>
    <#@ output extension=".cs" #>
    <#
    
    	var IsParent = true; // setting to false prevents Parent code from being generated
    	var IsChild = true; // setting to false prevents Child code from being generated
    
    	GenHeader();
    
    	if (IsParent)
    		GenParentProperties();
    
    	if (IsChild)
    		GenChildProperties();
    
    	GenFooter();
    	
    #>
    
    <#+
    	void GenHeader()
    	{
    #>
    // Code generated by a template
    
    using System;
    
    namespace StackOverflow
    {
    	public class Person
    	{
    		string Name;
    		int Age;
    <#+
    	}
    #>
    
    
    <#+
    	void GenParentProperties()
    	{
    #>
    		Person[] Childs;
    <#+
    	}
    #>
    
    <#+
    	void GenChildProperties()
    	{
    #>
    		Person Father;
    		Person Mother;
    <#+
    	}
    #>
    
    <#+
    	void GenFooter()
    	{
    #>
    	}
    }
    <#+
    	}
    #>
