    <details>
     <Classes>
          <Class>
            <class>5</class>
            <section>A</class>
            <student>
             <firstname>Avijeet</firstname>
             <lastname>Roy</lastname>
             <roll>01</roll>
           </student>
           <student>
            <firstname>Saurav</firstname>
            <lastname>Das</lastname>
            <roll>02</roll>
          </student>
          </Class>
        
           <Class>
            <class>10</class>
            <section>A</class>
            <student>
             <firstname>Saumitra</firstname>
             <lastname>Bain</lastname>
             <roll>10</roll>
           </student>
           <student>
            <firstname>Tarun</firstname>
            <lastname>Sing</lastname>
            <roll>11</roll>
          </student>
          </Class>
      </Classes> 
    </details>
