    public partial class Form1: Form
    {
    ....
    	internal SaveFileDialog SaveFileDialog1;
    ....
    
    	public Form1() : base()
    	{   
                    ....
                    this.SaveFileDialog1 = new SaveFileDialog();
                    ....
