    .... Form_Loaded....
    {
     .....
          mypanel=new Panel();
          mypanel.Tag= new IntervalComparer(2); // 2 * 100ms
     .....
    }
    .... Timer_Tick....
    {
       ....
       (mypanel.Tag as IntervalComparer).TickMe();
        if((mypanel.Tag as IntervalComparer).CanIUpdate())
         {
           UpdateMyPanel();//your update method 
           (mypanel.Tag as IntervalComparer).ResetMe();
         }
       ....
    }
