    var tblA = new DataTable();
    tblA.Columns.Add("c1", typeof(int));
    tblA.Columns.Add("c2", typeof(int));
    tblA.Columns.Add("c3", typeof(string));
    tblA.Columns.Add("c4", typeof(char));
    var tblB = new DataTable();
    tblB.Columns.Add("c1", typeof(int));
    tblB.Columns.Add("c5", typeof(int));
    tblB.Columns.Add("c6", typeof(string));
    tblB.Columns.Add("c7", typeof(char));
    var tblC = new DataTable();
    tblC.Columns.Add("c1", typeof(int));
    tblC.Columns.Add("c8", typeof(int));
    tblC.Columns.Add("c9", typeof(string));
    tblC.Columns.Add("c10", typeof(char));
    tblA.Rows.Add(1, 8500, "abc", 'A');
    tblA.Rows.Add(2, 950, "cde", 'B');
    tblA.Rows.Add(3, 150, "efg", 'C');
    tblA.Rows.Add(4, 850, "ghi", 'D');
    tblA.Rows.Add(5, 50, "ijk", 'E');
    tblB.Rows.Add(1, 7500, "klm", 'F');
    tblB.Rows.Add(2, 900, "mno", 'G');
    tblB.Rows.Add(3, 150, "opq", 'H');
    tblB.Rows.Add(4, 850, "qrs", 'I');
    tblB.Rows.Add(5, 50, "stu", 'J');
    tblC.Rows.Add(1, 7500, "uvw", 'K');
    tblC.Rows.Add(2, 900, "wxy", 'L');
    tblC.Rows.Add(3, 150, "yza", 'M');
    tblC.Rows.Add(4, 850, "ABC", 'N');
    tblC.Rows.Add(5, 50, "CDE", 'O');
