            var uriBuilder = new UriBuilder("test.php", "test");
            var httpClient = new HttpClient();
            var httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, uriBuilder.ToString());
            httpRequestMessage.Headers.Add("Host", "test.com");
            httpRequestMessage.Headers.Add("Connection", "keep-alive");
         //   httpRequestMessage.Headers.Add("Content-Length", "138");
            httpRequestMessage.Headers.Add("Pragma", "no-cache");
            httpRequestMessage.Headers.Add("Cache-Control", "no-cache");
            httpRequestMessage.Headers.Add("Origin", "test.com");
            httpRequestMessage.Headers.Add("Upgrade-Insecure-Requests", "1");
        //    httpRequestMessage.Headers.Add("Content-Type", "application/x-www-form-urlencoded");
            httpRequestMessage.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36");
            httpRequestMessage.Headers.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8");
            httpRequestMessage.Headers.Add("Referer", "http://www.translationdirectory.com/");
            httpRequestMessage.Headers.Add("Accept-Encoding", "gzip, deflate");
            httpRequestMessage.Headers.Add("Accept-Language", "en-GB,en-US;q=0.9,en;q=0.8");
            httpRequestMessage.Headers.Add("Cookie", "__utmc=266643403; __utmz=266643403.1537352460.3.3.utmccn=(referral)|utmcsr=google.co.uk|utmcct=/|utmcmd=referral; __utma=266643403.817561753.1532012719.1537357162.1537361568.5; __utmb=266643403; __atuvc=0%7C34%2C0%7C35%2C0%7C36%2C0%7C37%2C48%7C38; __atuvs=5ba2469fbb02458f002");
            var httpResponseMessage = httpClient.SendAsync(httpRequestMessage).Result;
            var httpContent = httpResponseMessage.Content;
            string result = httpResponseMessage.Content.ReadAsStringAsync().Result;
