    private AutoResetEvent f1 = new AutoResetEvent(false);
    private AutoResetEvent f2 = new AutoResetEvent(false);
    ...
    void Elapsed(object s, ElapsedEventArgs e)
    {
        ...
        Parallel.Invoke(() => { f1.WaitOne(); Function1(); f1.Set(); },
                        () => { f2.WaitOne(); Function2(); f2.Set(); }
                        ...
        ...
    }
