    <dictionary>
      <item>
        <key>
          <string>key1</string>
        </key>
        <value>
          <string>value1</string>
        </value>
      </item>
      <item>
        <key>
          <string>key1</string>
        </key>
        <value>
          <string>value2</string>
        </value>
      </item>
    </dictionary>
