                StreamWriter Sw = null;
                StreamReader Sr = null;
                string sUsername = "aUsername";
                string sPassword = "aValidPass";
                string data = string.Format("name={0}&password={1}", sUsername, sPassword);
                HttpWebRequest Req = (HttpWebRequest)WebRequest.Create("http://ts14.travian.com.sa/dorf1.php");
                Req.Method = "POST";
                Req.KeepAlive = true;
                ASCIIEncoding encoding = new ASCIIEncoding();
                byte[] byte1 = encoding.GetBytes(data);
                Req.ContentType = "application/x-www-form-urlencoded";
                Req.ContentLength = byte1.Length;
                Stream newStream = Req.GetRequestStream();
                newStream.Write(byte1, 0, byte1.Length);
                newStream.Close();
                Sr = new StreamReader(((HttpWebResponse)Req.GetResponse()).GetResponseStream());
                sResponse = Sr.ReadToEnd();
                int cookieCount = cookieJar.Count;
                Sr.Close();
                Sw = null;
