    System.IO.MemoryStream ms = new System.IO.MemoryStream(insuranceClaim.Signature, 0, insuranceClaim.Signature.Length);
    System.Net.Mime.ContentType contentType = new System.Net.Mime.ContentType();
    contentType.MediaType = System.Net.Mime.MediaTypeNames.Image.Jpeg;
    contentType.Name = "signature.jpg";
    System.Net.Mail.Attachment imageAttachment = new System.Net.Mail.Attachment(ms, contentType);
    mailMessage.Attachments.Add(imageAttachment);
    System.IO.MemoryStream embeddedMs = new System.IO.MemoryStream(insuranceClaim.Signature, 0, insuranceClaim.Signature.Length);
    System.Net.Mail.LinkedResource signature = new System.Net.Mail.LinkedResource(embeddedMs, new System.Net.Mime.ContentType("image/jpeg"));
    signature.ContentId = "CustomerSignature";
    System.Net.Mail.AlternateView aView = System.Net.Mail.AlternateView.CreateAlternateViewFromString(mailMessage.Body, new System.Net.Mime.ContentType("text/html"));
    aView.LinkedResources.Add(signature);
    mailMessage.AlternateViews.Add(aView);
