    public interface IAmAGenericEntity { }
    public class Entity<T> where T : IAmAGenericEntity, new()
    // ...
    public class Category : Entity<T>, IAmAGenericEntity
    // ....
    var list = new List<IAmAGenericEntity>();
    // ...
