        StringBuilder sbSQL = new StringBuilder();
        sbSQL.AppendLine(" SET DATEFORMAT DMY");
        sbSQL.AppendLine(" SELECT");
        sbSQL.AppendLine("      TillPayment.TillPaymentId As Id");
        sbSQL.AppendLine("    , TillPayment.TransactionGuid As TransactionCode");
        sbSQL.AppendLine("    , TillPayment.Amount As Price");
        sbSQL.AppendLine("    , TillPayment.DiscountPercentage");
        sbSQL.AppendLine("    , TillPayment.Processed As ProcessedDate");
        sbSQL.AppendLine("    , PaymentType.Name As PaymentType");
        sbSQL.AppendLine("    , TillPayment.ItemType As Item");
        sbSQL.AppendLine("    , TillUser.LoginCode As Login");
        sbSQL.AppendLine("    , TillUser.Name As UserName");
        sbSQL.AppendLine("    , TillPayment.TillName As Till");
        sbSQL.AppendLine(" FROM");
        sbSQL.AppendLine("    [tblTillPayment] TillPayment");
        sbSQL.AppendLine("    INNER JOIN [tblPaymentType] PaymentType ON TillPayment.PaymentTypeId = PaymentType.PaymentTypeId");
        sbSQL.AppendLine("    INNER JOIN [tblTillUser] TillUser ON TillPayment.TillLoginCode = TillUser.LoginCode");
        int SelectedMonthFrom = GetMonthAsNumber(CboMonthReportMonth.SelectedItem.Text);
        int SelectedYearFrom = int.Parse(CboMonthReportYear.SelectedItem.Text);
        int SelectedMonthTo = SelectedMonthFrom == 12 ? 1 : SelectedMonthFrom + 1;
        int SelectedYearTo = SelectedMonthTo == 1 ? SelectedYearFrom + 1: SelectedYearFrom;
        sbSQL.AppendLine(" WHERE");
        sbSQL.AppendLine("    Processed >= '01-" + SelectedMonthFrom + "-" + SelectedYearFrom + " 00:00'");
        sbSQL.AppendLine("    AND Processed < '01-" + SelectedMonthTo + "-" + SelectedYearTo + " 00:00'");
        sbSQL.AppendLine(" AND NOT(TillUser.LoginCode = '2503' or TillUser.LoginCode = '1453')");
        sbSQL.AppendLine(" ORDER BY");
        sbSQL.AppendLine("    Till");
        sbSQL.AppendLine("    , Processed");
        DataTable DtReport = DBGetDataTable(sbSQL.ToString());
