    double a = BitConverter.ToDouble(new byte[] { 49, 51, 51, 51, 51, 51, 211, 63, }, 0);
    double b = BitConverter.ToDouble(new byte[] { 50, 51, 51, 51, 51, 51, 211, 63, }, 0);
    double c = BitConverter.ToDouble(new byte[] { 51, 51, 51, 51, 51, 51, 211, 63, }, 0);
    double d = BitConverter.ToDouble(new byte[] { 52, 51, 51, 51, 51, 51, 211, 63, }, 0);
    double e = BitConverter.ToDouble(new byte[] { 53, 51, 51, 51, 51, 51, 211, 63, }, 0);
    Console.WriteLine("using G:");
    Console.WriteLine(a.ToString());
    Console.WriteLine(b.ToString());
    Console.WriteLine(c.ToString());
    Console.WriteLine(d.ToString());
    Console.WriteLine(e.ToString());
    Console.WriteLine("using F40:");
    Console.WriteLine(a.ToString("F40"));
    Console.WriteLine(b.ToString("F40"));
    Console.WriteLine(c.ToString("F40"));
    Console.WriteLine(d.ToString("F40"));
    Console.WriteLine(e.ToString("F40"));
    Console.WriteLine("using R:");
    Console.WriteLine(a.ToString("R"));
    Console.WriteLine(b.ToString("R"));
    Console.WriteLine(c.ToString("R"));
    Console.WriteLine(d.ToString("R"));
    Console.WriteLine(e.ToString("R"));
