    string file = @"C:\Temp\temp.dat";
    string[] _symbol = { "Hello", "the", "man" };
    string _source = "\"Hello, Hello,\" the man said.\n\"Hello,\" the woman replied.";
    string _expect = "\"\xF3, \xF3,\" \xF2 \xF1 said.\n\"\xF3,\" \xF2 wo\xF1 replied.";
    byte[] tblix = { 0xF3 };
    string _repl, _dest;
    Encoding e1252 = Encoding.GetEncoding(1252);
    _repl = e1252.GetString(tblix);
    _dest = _source.Replace(_symbol[0], _repl);
    tblix[0]--;
    _repl = e1252.GetString(tblix);
    _dest = _dest.Replace(_symbol[1], _repl);
    tblix[0]--;
    _repl = e1252.GetString(tblix);
    _dest = _dest.Replace(_symbol[2], _repl);
    bool check = (_dest == _expect);
    TextWriter tw = new StreamWriter(file, false, e1252);
    tw.Write(_dest);
    tw.Close();
