            Canvas pnel = new Canvas();
            var btntab = new Button();
            var tbGoToNextTab1 = new TextBlock();
            var tbGoToNextTab2 = new TextBlock();
            var tbGoToNextTab3 = new TextBlock();
            tbGoToNextTab1.Text = "Please ";
            tbGoToNextTab2.Text = "Click Here";
            tbGoToNextTab3.Text = " to go to next Page.";
            tbGoToNextTab1.Margin = new Thickness(0, 0, 0, 0);
            btntab.Margin = new Thickness(40, 0, 0, 0);
            tbGoToNextTab3.Margin = new Thickness(95, 0, 0, 0);
            tbGoToNextTab1.Foreground = new SolidColorBrush(Colors.Black);
            tbGoToNextTab2.Foreground = new SolidColorBrush(Colors.Black);
            tbGoToNextTab3.Foreground = new SolidColorBrush(Colors.Black);
            btntab.Click += new RoutedEventHandler(btntab_Click);
            btntab.Content = tbGoToNextTab2;
            pnel.Children.Add(tbGoToNextTab1);
            pnel.Children.Add(btntab);
            pnel.Children.Add(tbGoToNextTab3);
            Text112.Children.Add(pnel);
