    <asp:GridView ID="tableResults" runat="server" ID="tableResults"  DataMember="Table"
                EnableModelValidation="True" 
                CssClass = "GridViewStyle" 
                OnRowDeleting = "dataViewRowDeleting" 
                OnRowEditing= "tableResults_RowEditing" 
                OnRowUpdating= "tableResults_RowUpdating" 
                OnRowCancelingEdit= "tableResults_RowCancelingEdit"
                AutoGenerateDeleteButton="true" 
                AutoGenerateEditButton="true" >
                <Columns>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:HyperLink ID="HyperLink1" runat="server" Text="Скачать объект" NavigateUrl='<%#"objects/" + Eval("Идентификатор") %>'></asp:HyperLink>
                    </ItemTemplate>    
                </asp:TemplateField>
               </Columns>          
    </asp:GridView>
