    ObservableCollection<Employee> _employees = ...
    ObservableCollection<Boss> _bosses = ...
    ObservableCollection<Department> _departments = ...
    ObservableCollection<IList> _collections = ...
    _collections.Add(_employees);
    _collections.Add(_bosses);
    _collections.Add(_departments);
