    //...
    DateTime date = DateTime.MinValue;
    DateTime.TryParse(this.txtDateFrom.Text, out date);
    string result = _bllstaff.addInfo(date, _pUser.IDUSER, DateTime.Now, dtCurrentTable);
    //...
