        Process otherProcess = new Process();
        ...
        otherProcess.StartInfo.Arguments = "abc" + foo() + "," + bar();// what we need
        ...
        otherProcess.Start(); // break-point is here
