    PdfPTable table = new PdfPTable(5);
    float[] widths = new float[] { 1f, 2f, 2f, 2f, 1f };
    table.SetWidths(widths);
    PdfPCell cell;
    cell = new PdfPCell(new Phrase("S/N"));
    cell.Rowspan = 2;
    table.AddCell(cell);
    cell = new PdfPCell(new Phrase("Name"));
    cell.Colspan = 3;
    table.AddCell(cell);
    cell = new PdfPCell(new Phrase("Age"));
    cell.Rowspan = 2;
    table.AddCell(cell);
    table.AddCell("SURNAME");
    table.AddCell("FIRST NAME");
    table.AddCell("MIDDLE NAME");
    table.AddCell("1");
    table.AddCell("James");
    table.AddCell("Fish");
    table.AddCell("Stone");
    table.AddCell("17");
