    ...
    XmlSerializer ser = new XmlSerializer(typeof(A), overrides, new[] { typeof(B) }, new XmlRootAttribute("Root"), "defautlNS");
    ...
	public class A { public int a;}
	public class B : A { public int b;}
