        <TableColumns>
          <TableColumn>
            <Width>0.5in</Width>
          </TableColumn>
          <TableColumn>
            <Width>1.125in</Width>
          </TableColumn>
          <TableColumn>
            <Width>1in</Width>
          </TableColumn>
          <TableColumn>
            <Width>1in</Width>
          </TableColumn>
          <TableColumn>
            <Width>0.5in</Width>
          </TableColumn>
          <TableColumn>
            <Width>1.375in</Width>
          </TableColumn>
        </TableColumns>
