     Grid grdbooltype = new Grid();
                grdbooltype.Name = "Grid_" + keybooltype;
                grdbooltype.Margin = new Thickness(0, 20, 20, 0);
                grdbooltype.RowDefinitions.Add(new RowDefinition() { Height = GridLength.Auto });
                grdbooltype.RowDefinitions.Add(new RowDefinition());
                TextBlock objtextblock = new TextBlock();
                objtextblock.Text = "Select Image";
                objtextblock.FontSize = 15;
                grdbooltype.Children.Add(objtextblock);
                Grid.SetRow(objtextblock, 0);
                Grid grdtoggleswitch = new Grid();
                grdtoggleswitch.Name = headername;
                grdtoggleswitch.ColumnDefinitions.Add(new ColumnDefinition() { Width = GridLength.Auto });
                grdtoggleswitch.ColumnDefinitions.Add(new ColumnDefinition());
                TextBlock txtblktoggleswitchleft = new TextBlock();
                txtblktoggleswitchleft.FontSize = 15;
                txtblktoggleswitchleft.VerticalAlignment = VerticalAlignment.Center;
                txtblktoggleswitchleft.Text = headername;
                Grid.SetColumn(txtblktoggleswitchleft, 0);
                ToggleSwitch toggleswitch = new ToggleSwitch();
                toggleswitch.Name = key;
                toggleswitch.HorizontalAlignment = HorizontalAlignment.Right;
                toggleswitch.Padding = new Thickness(0);
                toggleswitch.IsOn = defaultvalue;
                toggleswitch.Margin = new Thickness(0, 0, 0, 0);
                toggleswitch.OnContent = "On";
                toggleswitch.OffContent = "Off";
                Grid.SetColumn(toggleswitch, 1);
                grdtoggleswitch.Children.Add(txtblktoggleswitchleft);
                grdtoggleswitch.Children.Add(toggleswitch);
                Grid.SetRow(grdtoggleswitch, 1);
                grdbooltype.Children.Add(grdtoggleswitch);
