            var stringA = "This contains a {parameter} somewhere!";
            var stringB = "This contains an {argument} instead.";
            var stringC = "No parameters or arguments here!";
            var simpleRegex = new Regex(@"{[a-zA-Z0-9_]+}");
            var groupRegex = new Regex(@"{(?<Parameter>[a-zA-Z0-9_]+)}");
            var simpleMatchA = simpleRegex.Match(stringA);
            var simpleMatchB = simpleRegex.Match(stringB);
            var simpleMatchC = simpleRegex.Match(stringC);
            var groupMatchA = groupRegex.Match(stringA);
            var groupMatchB = groupRegex.Match(stringB);
            var groupMatchC = groupRegex.Match(stringC);
            Console.WriteLine("String A: {0}", stringA);
            Console.WriteLine("String B: {0}", stringB);
            Console.WriteLine("String C: {0}", stringC);
            Console.WriteLine("Does A match? {0}", simpleMatchA.Success);
            Console.WriteLine("Does B match? {0}", simpleMatchB.Success);
            Console.WriteLine("Does C match? {0}", simpleMatchC.Success);
            Console.WriteLine("A value: {0}", groupMatchA.Groups["Parameter"].Value);
            Console.WriteLine("B value: {0}", groupMatchB.Groups["Parameter"].Value);
            Console.WriteLine("C value: {0}", groupMatchC.Groups["Parameter"].Value);
