     int processID = ... 
     // you also can use    Process.GetProcessesByName(....) to find the proicessID - or the batch process
     //Later when you need to kill the process...
     Process pToKill = Process.GetProcessById(processID);
     pToKill.Kill();
