    public interface IRepository<TEntity> where TEntity : BaseClass
    ...
    public class Repository<TEntity> : IRepository<TEntity> where TEntity : BaseClass
    ...
    public virtual IRepository<TEntity> Repository<TEntity>() where TEntity : BaseClass
