    DataTable table = new DataTable();
    table.Columns.Add("ID", typeof(System.Int32));
    table.Columns.Add("column_name_image", typeof(string));
    .....
    .....
    .....
    GridViewProduct.DataSource = table;
    GridViewProduct.DataBind();
