    // The select now builds an anonymous object; You can also create a new class, ExamResultWithDate,
    // for example, that has all fields of ExamResult plus a DateTime field; OR you can just add that 
    // property to the partial class generated by EF or Linq-to-Sql or whatever right on the ExamResult 
    // entity.
    var executionQuery = (from x in db.ExamResult
                         where x.Student.Equals(iStudent)
                         select new { Entity = x, ActualDate = getDate(x.Date) }); // note select * as in your OP doesn't compile :)
    var orderedQuery = executionQuery
        .OrderBy(eq => eq.ActualDate)
        .Select(er => er.Entity); // gets you just the entities in this case and discards the dates
