    SQLiteConnectionStringBuilder conString = new SQLiteConnectionStringBuilder();
    conString.DataSource = databaseFilePath;
    conString.DefaultTimeout = 5000;
    conString.SyncMode = SynchronizationModes.Off;
    conString.JournalMode = SQLiteJournalModeEnum.Memory;
    conString.PageSize = 65536;
    conString.CacheSize = 16777216;
    conString.FailIfMissing = false;
    conString.ReadOnly = false;
