    <Dictionary>
         <Acronyms>
           <CasingExceptions>
              <Acronym>De</Acronym>
              ...
           </CasingExceptions>
           ...
        </Acronyms>
        ...
    </Dictionary>
