    [AutoGenerated(Category = "ARB_shader_objects", Version = "", EntryPoint = "glUniform1ivARB")]
    [CLSCompliant(false)]
    public static void Uniform1(Int32 location, Int32 count, Int32[] value);
    
    [AutoGenerated(Category = "ARB_shader_objects", Version = "", EntryPoint = "glUniform1fvARB")]
    [CLSCompliant(false)]
    public static unsafe void Uniform1(Int32 location, Int32 count, Single* value);
