    delegate void SomeHandler();
    
    // This is the helper class generated by the compiler that allows an anonymous function inside your method access to local variables even after the function or method has returned.
    sealed class SomeHandlerClosure
    {
       public int x;
    
       public void CompilerNamedMethod()
       {
         Console.WriteLine(x);
       }
    }
    
    static SomeHandler GetSomeHandler()
     {
       SomeHandlerClosure closure = new SomeHandlerClosure();
       closure.x = 1;
    
       SomeHandler a = new Action(closure.CompilerNamedMethod);
    
       closure.x = 2;
    
       return a;
     }
    
    static void Main(string[] args)
     {
       SomeHandler a = GetSomeHandler();
    
       a();
     }
