    void Dg_OnAutoGeneratedColumns(object sender, EventArgs e)
    {
    	foreach (var dataGridColumn in dg.Columns)
    	{
    		var textColumn = dataGridColumn as DataGridTextColumn;
    		if (textColumn == null) continue;
    
    		textColumn.ElementStyle = FindResource("ColumnStyle") as Style;
    	}
    }
