    public string ETC(string title)
    {  // english title capitalization
        if (title == null) return "";
        string s = title.Trim().Replace('`', '\'');      // change apo to tick mark
        TextInfo UsaTextInfo = new CultureInfo("en-US", false).TextInfo;
        s = UsaTextInfo.ToTitleCase(s);              // caps for all words
        // a list of exceptions one way or the other..
        s = s.Replace(" A ", " a ");
        s = s.Replace(" also ", " Also ");
        s = s.Replace(" An ", " an ");
        s = s.Replace(" And ", " and ");
        s = s.Replace(" as ", " As ");
        s = s.Replace(" At ", " at ");
        s = s.Replace(" be ", " Be ");
        s = s.Replace(" But ", " But ");
        s = s.Replace(" By ", " by ");
        s = s.Replace(" For ", " for ");
        s = s.Replace(" From ", " from ");
        s = s.Replace(" if ", " If ");
        s = s.Replace(" In ", " in ");
        s = s.Replace(" Into ", " into ");
        s = s.Replace(" he ", " He ");
        s = s.Replace(" has ", " Has ");
        s = s.Replace(" had ", " Had ");
        s = s.Replace(" is ", " Is ");
        s = s.Replace(" my ", " My ");
        s = s.Replace("   ", "  ");                // no triple spaces
        s = s.Replace("'N'", "'n'");          // Rock 'n' Roll
        s = s.Replace("'N'", "'n'");         // Rock 'n Roll
        s = s.Replace(" no ", " No ");
        s = s.Replace(" Nor ", " nor ");
        s = s.Replace(" Not ", " not ");
        s = s.Replace(" Of ", " of ");
        s = s.Replace(" Off ", " off ");
        s = s.Replace(" On ", " on ");
        s = s.Replace(" Onto ", " onto ");
        s = s.Replace(" Or ", " or ");
        s = s.Replace(" O'c ", " O'C ");
        s = s.Replace(" Over ", " over ");
        s = s.Replace(" so ", " So ");
        s = s.Replace(" To ", " to ");
        s = s.Replace(" that ", " That ");
        s = s.Replace(" this ", " This ");
        s = s.Replace(" thus ", " Thus ");
        s = s.Replace(" The ", " the ");
        s = s.Replace(" Too ", " too ");
        s = s.Replace(" when ", " When ");
        s = s.Replace(" With ", " with ");
        s = s.Replace(" Up ", " up ");
        s = s.Replace(" Yet ", " yet ");
        // a few(!) verbal expressions
        s = s.Replace(" Get up ", " Get Up ");
        s = s.Replace(" Give up ", " Give Up ");
        s = s.Replace(" Givin' up ", " Givin' Up ");
        s = s.Replace(" Grow up ", " Grow Up ");
        s = s.Replace(" Hung up ", " Hung Up ");
        s = s.Replace(" Make up ", " Make Up ");
        s = s.Replace(" Wake Me up ", " Wake Me Up ");
        s = s.Replace(" Mixed up ", " Mixed Up ");
        s = s.Replace(" Shut up ", " Shut Up ");
        s = s.Replace(" Stand up ", " Stand Up ");            
        s = s.Replace(" Wind up ", " Wind Up ");
        s = s.Replace(" Wake up ", " Wake Up ");
        s = s.Replace(" Come up ", " Come Up ");
        s = s.Replace(" Working on ", " Working On ");
        s = s.Replace(" Waiting on ", " Waiting On ");
        s = s.Replace(" Turn on ", " Turn On ");
        s = s.Replace(" Move on ", " Move On ");
        s = s.Replace(" Keep on ", " Keep On ");
        s = s.Replace(" Bring It on ", " Bring It On ");
        s = s.Replace(" Hold on ", " Hold On ");
        s = s.Replace(" Hang on ", " Hang On ");
        s = s.Replace(" Go on ", " Go On ");
        s = s.Replace(" Coming on ", " Coming On ");
        s = s.Replace(" Come on ", " Come On ");
        s = s.Replace(" Call on ", " Call On ");
        s = s.Replace(" Trust in ", " Trust In ");
        s = s.Replace(" Fell in ", " Fell In ");
        s = s.Replace(" Falling in ", " Falling In ");
        s = s.Replace(" Fall in ", " Fall In ");
        s = s.Replace(" Faith in ", " Faith In ");
        s = s.Replace(" Come in ", " Come In ");
        s = s.Replace(" Believe in ", " Believe In ");
        return s.Trim();
    }
