    List<Claimant> list = from ...
                          where ...
                          select ...
    foreach (Claimant claimant in list)
    {
        claimant.TaxNumber = NormalizeTaxNumber(claimant.TaxNumber); }
    }
    // ...
    public static string NormalizeTaxNumber(string n)
    {
        return String.IsNullOrEmpty(n) ? "0" : n;
    }
