    PresentationEx pres;
    pres = new PresentationEx();
    SlideEx sld = pres.Slides[0];
    ChartEx chart = sld.Shapes.AddChart(ChartTypeEx.ClusteredColumn, 0, 0, 500, 500);
    chart.ChartTitle.Text.Text = "Sample Title";
    chart.ChartTitle.Text.CenterText = true;
    chart.ChartTitle.Height = 20;
    chart.HasTitle = false;
    chart.HasLegend = false;
    chart.ChartData.Series[0].Labels.ShowValue = true;
    chart.SecondCategoryAxis.IsVisible = true;
    int defaultWorksheetIndex = 0;
    ChartDataCellFactory fact = chart.ChartData.ChartDataCellFactory;
    chart.ChartData.Series.Clear();
    chart.ChartData.Categories.Clear();
    int s = chart.ChartData.Series.Count;
    s = chart.ChartData.Categories.Count;
    chart.ChartData.Series.Add(fact.GetCell(defaultWorksheetIndex, 0, 1, "1"), chart.Type);
    chart.ChartData.Series.Add(fact.GetCell(defaultWorksheetIndex, 0, 2, "2"), chart.Type);
    chart.ChartData.Series.Add(fact.GetCell(defaultWorksheetIndex, 0, 3, "3"), chart.Type);
    chart.ChartData.Categories.Add(fact.GetCell(defaultWorksheetIndex, 1, 0, "Age"));
    chart.ChartData.Categories.Add(fact.GetCell(defaultWorksheetIndex, 2, 0, "Gender"));
    chart.ChartData.Categories.Add(fact.GetCell(defaultWorksheetIndex, 3, 0, "Status"));
    chart.ChartData.Categories.Add(fact.GetCell(defaultWorksheetIndex, 4, 0, "Nationality"));
    chart.GapDepth = 200;
    //chart.GapWidth = 50 I need to be able to do something similar to this code
    ChartSeriesEx series = chart.ChartData.Series[0];
    series.Format.Fill.FillType = FillTypeEx.Solid;
    series.Format.Fill.SolidFillColor.Color = Color.FromArgb(32, 202, 250);
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 1, 1, 40));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 2, 1, 64));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 3, 1, 50));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 4, 1, 1));
    series.PlotOnSecondAxis = true;
    series = chart.ChartData.Series[1];
    series.Format.Fill.FillType = FillTypeEx.Solid;
    series.Format.Fill.SolidFillColor.Color = Color.FromArgb(0, 122, 171);
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 1, 2, 4));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 2, 2, 19));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 3, 2, 50));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 4, 2, 25));
    series.PlotOnSecondAxis = true;
    series = chart.ChartData.Series[2];
    series.Format.Fill.FillType = FillTypeEx.Solid;
    series.Format.Fill.SolidFillColor.Color = Color.FromArgb(0, 136, 188);
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 1, 2, 3));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 2, 2, 17));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 3, 2, 0));
    series.Values.Add(fact.GetCell(defaultWorksheetIndex, 4, 2, 63));
    series.PlotOnSecondAxis = true;
    chart.GapDepth = 80;//Values in percentage
    chart.GapWidth = 250;
    pres.Write("D:\\Aspose Data\\Presentation2.pptx");
