	<LICENSE>
	  <GENERAL_INFO>some Info</GENERAL_INFO>
	  <LICENSE_INFO>
		<LICENSE_NO>1</LICENSE_NO>
		<USER_ID>N/A</USER_ID>
	  </LICENSE_INFO>
	  <LICENCE_CONSTRAINT>
		<MAX_USER>N/A</MAX_USER>
		<MAX_MACHINE>N/A</MAX_MACHINE>
	  </LICENCE_CONSTRAINT>
	  <MACHINE_INFO>
		<MACHINE_IP>1.2.3.4</MACHINE_IP>
		<MACHINE_MAC>N/A</MACHINE_MAC>
	  </MACHINE_INFO>
	</LICENSE>
