    // Arrange
    var entity = new ContactProductLink
    {
        ContactRoleId = // ...
        // ...
    };
    mockDataSupplierService
        .Create<ContactProductLink>(Arg<ContactProductLink>.Invoke(entity));
    // Act
    // ...
    Assert.That(entity.ContactRoleId, Is.EqualTo(2));
    // ...
