    private void MyDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
    {
      var dg = sender as DataGrid;
      dg.Columns.Clear();
      var first = dg.ItemsSource.Cast<object>().FirstOrDefault() as IDictionary<string, object>;
      if (first == null) return;
      var names = first.Keys;
      foreach (var name in names)
      {
        dg.Columns.Add(new DataGridTextColumn { Header = name, Binding = new Binding(name) });
      }
    }
