        //  string appPath = HttpContext.Current.Request.ApplicationPath;
        CheckBox1.Visible = false;
        Response.ContentType = "application/pdf";
        string appPath = HttpContext.Current.Request.ApplicationPath;
       // FileStream file = new FileStream(Server.MapPath("~/save/") + (Convert.ToInt32(ViewState["cust"])) + "_" + (n++) + ".PDF", FileMode.Create, System.IO.FileAccess.Write);
        StringWriter sw = new StringWriter();
        HtmlTextWriter hw = new HtmlTextWriter(sw);
        pnlPerson.RenderControl(hw);
        StringReader sr = new StringReader(sw.ToString());
        Document pdfDoc = new Document(PageSize.A4, 5, 20, 50, 25);
        HTMLWorker htmlparser = new HTMLWorker(pdfDoc);
        //   MemoryStream ms = new MemoryStream();
        PdfWriter.GetInstance(pdfDoc, file);
        PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
        pdfDoc.Open();
        htmlparser.Parse(sr);
        hw.Close();
        sw.Close();
        pdfDoc.Close();
        sr.Close();
        file.Close();
        htmlparser.Close();
