    Sub CreatePublicGet_NoNull_HightlightPropertyNameFirst()
        DTE.ActiveDocument.Selection.CharLeft(False, 2)
        DTE.ActiveDocument.Selection.StartOfLine(vsStartOfLineOptions.vsStartOfLineOptionsFirstText, True)
        DTE.ActiveDocument.Selection.WordRight(True)
        DTE.ActiveDocument.Selection.Copy()
        DTE.ActiveDocument.Selection.LineDown(False, 2)
        DTE.ActiveDocument.Selection.StartOfLine(vsStartOfLineOptions.vsStartOfLineOptionsFirstText)
        DTE.ActiveDocument.Selection.CharRight(False, 4)
        DTE.ActiveDocument.Selection.NewLine()
        DTE.ActiveDocument.Selection.CharRight()
        DTE.ActiveDocument.Selection.NewLine()
        DTE.ActiveDocument.Selection.EndOfLine()
        DTE.ActiveDocument.Selection.CharLeft()
        DTE.ActiveDocument.Selection.NewLine()
        DTE.ActiveDocument.Selection.LineUp(False, 2)
        DTE.ActiveDocument.Selection.EndOfLine()
        DTE.ActiveDocument.Selection.NewLine()
        DTE.ActiveDocument.Selection.Paste()
        DTE.ActiveDocument.Selection.Text = "();"
        DTE.ActiveDocument.Selection.LineDown()
        DTE.ActiveDocument.Selection.WordLeft(True)
        DTE.ActiveDocument.Selection.CharLeft()
        DTE.ActiveDocument.Selection.WordLeft(True)
        DTE.ActiveDocument.Selection.Copy()
        DTE.ActiveDocument.Selection.LineUp(False, 2)
        DTE.ActiveDocument.Selection.NewLine()
        DTE.ActiveDocument.Selection.Text = "if ("
        DTE.ActiveDocument.Selection.Paste()
        DTE.ActiveDocument.Selection.Text = " == null)"
        DTE.ActiveDocument.Selection.NewLine()
        DTE.ActiveDocument.Selection.Text = "{"
        DTE.ActiveDocument.Selection.LineDown()
        DTE.ActiveDocument.Selection.StartOfLine(vsStartOfLineOptions.vsStartOfLineOptionsFirstText)
        DTE.ActiveDocument.Selection.EndOfLine()
        DTE.ActiveDocument.Selection.NewLine()
        DTE.ActiveDocument.Selection.Text = "}"
        DTE.ActiveDocument.Selection.LineUp()
        DTE.ActiveDocument.Selection.StartOfLine(vsStartOfLineOptions.vsStartOfLineOptionsFirstText)
        DTE.ActiveDocument.Selection.Paste()
        DTE.ActiveDocument.Selection.Text = " = new "
        DTE.ActiveDocument.Selection.Collapse()
        DTE.ActiveDocument.Selection.EndOfLine()
        DTE.ActiveDocument.Selection.LineDown(False, 4)
        DTE.ActiveDocument.Selection.EndOfLine()
        DTE.ActiveDocument.Selection.LineUp(True)
        DTE.ActiveDocument.Selection.Delete()
    End Sub
