    public void MethodOne(Boolean value)
    {
        // Process the value...
    }
    public void MethodOne(Int32 value)
    {
        // Process the value...
    }
    public void MethodOne(Int32 value, String text)
    {
        // Process the value and the text...
    }
    // And so on...
