    public class Sale
        {
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]//switch on autogenerated
            public int Id { get; set; }
        
            [Key]//set as Primary key
            [DatabaseGenerated(DatabaseGeneratedOption.None)]// switch off autogenerated PK
            public string TrNo { get; set; }
        
            public DateTime Date { get; set; }
            public int CustomerID { get; set; }
        
            public ObservableCollection<SaleDetail> SaleDetails { get; set; }
    }
