    //------------------------------------------------------------------------------
    // <auto-generated>
    // Well, not really. This is just a trick to get StyleCop off my back.
    // </auto-generated>
    //------------------------------------------------------------------------------
