        column = new DataGridViewTextBoxColumn();
        column.DataPropertyName = "Test1";
        column.Name = "Test1";
        dataGridView1.Columns.Add(column);
        column = new DataGridViewTextBoxColumn();
        column.DataPropertyName = "Test2";
        column.Name = "Test2";
        dataGridView1.Columns.Add(column);
        column = new DataGridViewTextBoxColumn();
        column.DataPropertyName = "Test3";
        column.Name = "Test3";
        dataGridView1.Columns.Add(column);
