     System
     System.Collections
     System.Configuration.Assemblies
     System.Diagnostics
     System.Diagnostics.SymbolStore
     System.Globalization
     System.IO
     System.IO.IsolatedStorage
     System.Reflection
     System.Reflection.Emit
     System.Resources
     System.Runtime.CompilerServices
     System.Runtime.InteropServices
     System.Runtime.InteropServices.Expando
     System.Runtime.Remoting
     System.Runtime.Remoting.Activation
     System.Runtime.Remoting.Channels
     System.Runtime.Remoting.Contexts
     System.Runtime.Remoting.Lifetime
     System.Runtime.Remoting.Messaging
     System.Runtime.Remoting.Metadata
     System.Runtime.Remoting.Metadata.W3cXsd2001
     System.Runtime.Remoting.Proxies
     System.Runtime.Remoting.Services
     System.Runtime.Serialization
     System.Runtime.Serialization.Formatters
     System.Runtime.Serialization.Formatters.Binary
     System.Security
     System.Security.Cryptography
     System.Security.Cryptography.X509Certificates
     System.Security.Permissions
     System.Security.Policy
     System.Security.Principal
     System.Text
     System.Threading
     Microsoft.Win32 
