    LocalBuilder a = ilGen.DeclareLocal(typeof(Int32));
    LocalBuilder b = ilGen.DeclareLocal(typeof(Int32));
    ilGen.Emit(OpCodes.Ldc_I4, 5); // Store "5" ...
    ilGen.Emit(OpCodes.Stloc, a);  // ... in "a".
    ilGen.Emit(OpCodes.Ldc_I4, 6); // Store "6" ...
    ilGen.Emit(OpCodes.Stloc, b);  // ... in "b".
    ilGen.Emit(OpCodes.Ldloc, a);  // Load "a" ...
    ilGen.Emit(OpCodes.Ldloc, b);  // ... and "b".
    ilGen.Emit(OpCodes.Add);       // Sum them ...
    ilGen.Emit(OpCodes.Ret);       // ... and return the result.
