    sqlQuery = "select name, data,data2 from surgicalfiledemo where id = @id";
    SqlCommand cmd = new SqlCommand(sqlQuery, con);
    cmd.Parameters.AddWithValue("@id", surgicalGridView.SelectedRow.Cells[1].Text);
    SqlDataAdapter adapt = new SqlDataAdapter();
    DataTable dt = new DataTable();
    adapt.SelectCommand = cmd;
    adapt.Fill(dt);
    GridView GridView1 = new  GridView();
    GridView1.DataSource = dt;
    GridView1.DataBind();
    Response.Clear();
    Response.Buffer = true;
    string filename="MyExportedData.xls"; 
    Response.AddHeader("content-disposition","attachment;filename="+filename);
    Response.Charset = "";
    Response.ContentType = "application/vnd.ms-excel";
    StringWriter sw = new StringWriter();
    HtmlTextWriter hw = new HtmlTextWriter(sw);
    GridView1.RenderControl(hw);
    Response.Output.Write(sw.ToString());
    Response.Flush();
    Response.End();
