    #pragma warning disable 1591
	//------------------------------------------------------------------------------
	// <auto-generated>
	//     This code was generated by a tool.
	//     Runtime Version:4.0.30319.18033
	//
	//     Changes to this file may cause incorrect behavior and will be lost if
	//     the code is regenerated.
	// </auto-generated>
	//------------------------------------------------------------------------------
	[assembly: Android.Runtime.ResourceDesignerAttribute("Mono.Android.Plugins.Resource", IsApplication=false)]
	namespace Mono.Android.Plugins
	{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_stat_dismiss = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_stat_ic_stat_snooze = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_stat_notification = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ic_stat_snooze = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int monoandroidsplash = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public static int dismiss_button = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int reminder_content = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int reminder_title = 2131099648;
			
			// aapt resource value: 0x7f060003
			public static int snooze_button = 2131099651;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int monoandroidsplash = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int post_reminder = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public static int Hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public static int dismiss = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int snooze = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public static int Mono_Android_Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
	}
	#pragma warning restore 1591
