    ...
                    if (!comboBox8.IsKeyboardFocusWithin)
                    {
                        MessageBox.Show("Error description", "Error!", MessageBoxButton.OK, MessageBoxImage.Information);
                    }
                    ...
