    Int64 ret = 0;
    
    using (var transaction = new TransactionScope(TransactionScopeOption.Suppress))
    {
        try
        {
            using (var context = new MyContext())
            {
                var secondaryEntity = new HOTEL();
                context.HOTELs.Add(secondaryEntity);
    
                // SaveChanges(bool) has been depricated, use SaveOptions.
                // SaveChanges is required to generate the autogenerated Identity HOTEL_ID.
                context.ObjectContext.SaveChanges(SaveOptions.AcceptAllChangesAfterSave);
                primaryEntity.HOTEL_ID = secondaryEntity.HOTEL_ID;
    
                context.OWNERs.Attach(primaryEntity);
                context.Entry(primaryEntity).State = primaryEntity.OWNER_ID == 0 ? EntityState.Added : EntityState.Modified;
    
                context.ObjectContext.SaveChanges(SaveOptions.AcceptAllChangesAfterSave);
                ret = primaryEntity.OWNER_ID;
    
                if (ret != 0)
                {
                    transaction.Complete();
                    context.ObjectContext.AcceptAllChanges();
                }
            }
        }
        catch (Exception ex)
        {
            // Deal with errors.
        }
    }
    return ret;
