    public static Task<bool> ValidateEmail(string email)
    {
        var url = ...
        var queryString = ...
        try {
            return HttpHelper.PostAsync(url, queryString, null).ContinueWith(
            json => { try { ... } catch(Exception) { ... } });
        } catch( ...
