    string myString = ...
    Console.WriteLine(IsNull(myString, "foo"))            // works
    object myObject = ...
    Console.WriteLine(IsNull(myMyObject, new object()))   // works
    DateTime? myDateTime = ...
    Console.WriteLine(IsNull(myDateTme, DateTme.Now))     // works
    int? myInt1 = ...
    Console.WriteLine(IsNull(myInt, DateTme.Now))         // works
    int myInt2 = ...
    Console.WriteLine(IsNull(myInt2, DateTme.Now))        // <-- compiler error
