    It is very simple
    
    I had,
    
    public WMSEntities() : base("name=WMSEntities") //WMSEntities is conection string name in     web.config also the name of Entitiframework
            {
            }
    
    already in autogenerated Model.Context.cs of edmx folder
    
    To connect to multiple database in runtime, I created another constructor that takes connection string as parameter like below in same file Model.Context.cs 
       public WMSEntities(string connStringName)
                : base("name=" + connStringName)
            {
            }
    
    Now, I added other connection string in Web.Config for example
      <add name="WMSEntities31" connectionString="data source=TESTDBSERVER_NAME;initial catalog=TESTDB;userid=TestUser;password=TestUserPW/>
    
    <add name="WMSEntities" connectionString="data source=TESTDBSERVER_NAME12;initial catalog=TESTDB12;userid=TestUser12;password=TestUserPW12/>
    
    Then, when connecting to database I call below method passing connetionString name as parameter
    
      public static List<v_POVendor> GetPOVendorList(string connectionStringName)
            {
    
      using (WMSEntities db = new WMSEntities(connectionStringName))
                {               
                    vendorList = db.v_POVendor.ToList();                 
                    
                }
    }
