    // code generated by tool 
    // Customer.cs
    public partial class Customer // : EntityBaseClasses, interfaces, etc
    {
        public int ID 
        {
            get { /* implementation */ }
            set { /* implementation */ }
        }
    }
