    Microsoft.TeamFoundation.Client.dll                                  
    Microsoft.TeamFoundation.Common.dll                                   
    Microsoft.TeamFoundation.Core.WebApi.dll                              
    Microsoft.TeamFoundation.TestManagement.Client.dll                    
    Microsoft.TeamFoundation.TestManagement.Common.dll                    
    Microsoft.TeamFoundation.Work.WebApi.dll                              
    Microsoft.TeamFoundation.WorkItemTracking.Client.DataStoreLoader.dll  
    Microsoft.TeamFoundation.WorkItemTracking.Client.dll                  
    Microsoft.TeamFoundation.WorkItemTracking.Common.dll                  
    Microsoft.TeamFoundation.WorkItemTracking.Controls.dll                
    Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll                   
    Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll                  
    Microsoft.VisualStudio.Services.Client.Interactive.dll                
    Microsoft.VisualStudio.Services.Common.dll                            
    Microsoft.VisualStudio.Services.WebApi.dll                            
    Microsoft.WITDataStore32.dll                                          
    Microsoft.WITDataStore64.dll                                          
