    static IEnumerable<T> SequenceByExample<T>(T t){ return null; }
    ...
    var query = SequenceByExample(new { ID = 0, CourseName = "" } );
    if (whatever)
        query = ...
    else
        query = ...
