	TextBox txtE, txtM, txtB;
	Button btnAdd, btnDel;
	TableRow trow;
	TableCell tcell;
	foreach(TableRow tr in TableRows)
		tblEduDetails.Controls.Add(tr);
	int count = TableRows.Count + 1;
	txtE = new TextBox();
	txtE.ID = "E" + count.ToString();
	txtE.Visible = true;
	txtE.Text = "E " + count.ToString();
	txtE.BorderWidth = 2;
	txtE.TextMode = TextBoxMode.SingleLine;
	txtE.Height = 30;
	txtM = new TextBox();
	txtM.ID = "M" + count.ToString();
	txtM.Visible = true;
	txtM.Text = "M " + count.ToString();
	txtM.TextMode = TextBoxMode.SingleLine;
	txtM.Height = 30;
	txtB = new TextBox();
	txtB.ID = "E" + count.ToString();
	txtB.Visible = true;
	txtB.Text = "B " + count.ToString();
	txtB.TextMode = TextBoxMode.SingleLine;
	txtB.Height = 30;
	btnAdd = new Button();
	btnAdd.ID = "A" + count.ToString();
	btnDel = new Button();
	btnDel.ID = "D" + count.ToString();
	trow = new TableRow();
	trow.ID = "R" + count.ToString();
	trow.BorderWidth = 1;
	tcell = new TableCell();
	tcell.ID = "E" + count.ToString();
	tcell.Controls.Add(txtE);
	trow.Controls.Add(tcell);
	tcell = new TableCell();
	tcell.ID = "B" + count.ToString();
	tcell.Controls.Add(txtM);
	trow.Controls.Add(tcell);
	tcell = new TableCell();
	tcell.ID = "M" + count.ToString();
	tcell.Controls.Add(txtB);
	trow.Controls.Add(tcell);
	tblEduDetails.Controls.Add(trow);
	TableRows.Add(trow);
