    HtmlGenericControl tabs = new HtmlGenericControl("ul");
                tabs.ID = "myTopnav";
                tabs.Attributes.Add("class", "topnav");
                HtmlGenericControl li = new HtmlGenericControl("li");
                HtmlGenericControl ianchor = new HtmlGenericControl("a");
                li = new HtmlGenericControl("li");
                ianchor = new HtmlGenericControl("a");
                ianchor.ID = "Home";
                ianchor.Attributes.Add("href", "#home");
                ianchor.Attributes.Add("class", "active");
                ianchor.InnerText = "Home";
                li.Controls.Add(ianchor);
                tabs.Controls.Add(li);
                li = new HtmlGenericControl("li");
                ianchor = new HtmlGenericControl("a");
                ianchor.ID = "News";
                ianchor.Attributes.Add("href", "#");
                ianchor.InnerText = "News";
                li.Controls.Add(ianchor);
                tabs.Controls.Add(li);
                ControlContainer.Controls.Add(tabs);
