    using System.Data.SqlClient;
    //
        // First access the connection string, which may be autogenerated in Visual Studio for you.
        //
        string connectionString = "SELECT AVG(age_columnName) FROM TableName"
        //
        // In a using statement, acquire the SqlConnection as a resource.
        //
        using (SqlConnection con = new SqlConnection(connectionString))
        {
            //
            // Open the SqlConnection.
            //
            con.Open();
            //
            // The following code shows how you can use an SqlCommand based on the SqlConnection.
            //
            using (SqlCommand command = new SqlCommand("SELECT TOP 2 * FROM Dogs1", con))
            using (SqlDataReader reader = command.ExecuteReader())
            {
            while (reader.Read())
            {
                // process it
            }
            }
        }
