        string _SmartList,_yaxis,_y1axis,_y2axis,_y3axis,_y4axis,_y5axis;
        ds = GetDataSet("SELECT [Sql_Query],[Y_Axis],[Y1_Axis],[Y2_Axis],[Y3_Axis],[Y4_Axis],[Y5_Axis] FROM [DWH_SmartList] WHERE sys_SmartList_No=" + ddSmartQueryList.SelectedValue)   ;
        _SmartList = Convert.ToString(ds.Tables[0].Rows[0]["Sql_Query"]);
        _yaxis = Convert.ToString(ds.Tables[0].Rows[0]["Y_Axis"]);
        _y1axis= Convert.ToString(ds.Tables[0].Rows[0]["Y1_Axis"]);
        _y2axis = Convert.ToString(ds.Tables[0].Rows[0]["Y2_Axis"]);
        _y3axis = Convert.ToString(ds.Tables[0].Rows[0]["Y4_Axis"]);
        _y4axis = Convert.ToString(ds.Tables[0].Rows[0]["Y4_Axis"]);
        _y5axis = Convert.ToString(ds.Tables[0].Rows[0]["Y5_Axis"]);
        Dd_ListY.SelectedValue = _yaxis ;
        Dd_ListYSec.SelectedValue = _y1axis;
        Dd_List3.SelectedValue = _y2axis;
        Dd_List4.SelectedValue = _y3axis;
        Dd_List5.SelectedValue = _y4axis;
        ds.Tables[0].Dispose();
        ds = new DataSet();
        ds = GetDataSet(_SmartList);
        Chart1.DataSource = ds;
        Chart1.Legends.Add("Inspection_Date").Title = "Inspection_Date";
        Chart1.ChartAreas["ChartArea1"].AxisX.Title = Dd_List.SelectedValue;
        Chart1.ChartAreas["ChartArea1"].AxisX.MajorGrid.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisX.MajorTickMark.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisY.MajorTickMark.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisY.MajorGrid.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisX.MinorGrid.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisX.MinorTickMark.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisY.MinorGrid.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisY.MinorTickMark.Enabled = false;
        Chart1.ChartAreas["ChartArea1"].AxisY.Title = Dd_ListY.SelectedValue;
        Chart1.Series["Series1"].XValueMember = Dd_List.SelectedValue;
        Chart1.Series["Series1"].YValueMembers = Dd_ListY.SelectedValue;
        Chart1.Series["Series1"].LegendText = Dd_ListY.SelectedValue;
        this.GridFormatting();
        Chart1.DataBind();
        //Chart1.BackColor = System.Drawing.Color.White;
        // this.Chart1.ChartAreas["ChartArea1"].AxisY.IsStartedFromZero = false;
        GridView1.SelectedIndex = 0;
        GridView1.DataSource = ds;
        GridView1.DataBind();
    }
