    public class Startup {
        //...
        public void ConfigureServices(IServiceCollection services) {
            //...
            services.AddAutoMapper(cfg => { cfg.CreateMissingTypeMaps = true; });
            //...
        }
        //...
    }
