    [assembly: AssemblyTitle("SampleProject")]
    [assembly: AssemblyDescription("")]
    [assembly: AssemblyConfiguration("")]
    [assembly: AssemblyCompany("Microsoft")]
    [assembly: AssemblyProduct("SampleProject")]
    [assembly: AssemblyCopyright("Copyright © Microsoft 2011")]
    [assembly: AssemblyTrademark("")]
    [assembly: AssemblyCulture("")]
