    // DataTable...
    SkZapDataSet.vdSkZapDocumentDataTable dt
		= args.Row.Table as vdSkZapDocumentDataTable;
    // DataRow...
    SkZapDataSet.vdSkZapDocumentRow dr
		= args.Row as SkZapDataSet.vdSkZapDocumentRow;
    // Value...
    int id = (int)dr[dt.DocumentIdColumn.ColumnName, DataRowVersion.Original];
