    SqlParameter param = new SqlParameter();
    param.ParameterName = "@Login";
    param.Value = user.Login;
    cmd.Parameters.Add(param);
    param = new SqlParameter();
    param.ParameterName = "@Stack";
    param.Value = ex.StackTrace;
    cmd.Parameters.Add(param);
    param = new SqlParameter();
    param.ParameterName = "@Message";
    param.Value = ex.Message;
    cmd.Parameters.Add(param);
    param = new SqlParameter();
    param.ParameterName = "@Txt";
    param.Value = Txt;
    cmd.Parameters.Add(param);
    param = new SqlParameter();
    param.ParameterName = "@Source";
    param.Value = ex.Source;
    cmd.Parameters.Add(param);
    conn.Open();
    return cmd.ExecuteNonQuery();
