    for (int i = 0; i < a.Length; i++)
                {
                    ......
                    if (j <= a.Length)
                    {
                         ......
                    }
                    ......
                }
