    // Gets TestA's properties...
    var prop = typeof(TestA).GetProperties();
    // Then gets TestB's properties...
    var childProp = propertyInfo.PropertyType.GetProperties();
    prop = prop.Union(childProp).ToArray();
