    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            radioButton1.CheckedChanged += radioButton1_CheckedChanged;
            //Triggering the handlers programmatically
            radioButton1_CheckedChanged(null, null);
            radioButton2_CheckedChanged(null, null);
        }
        //this handler is manually added in the constructor
        void radioButton1_CheckedChanged(object sender, EventArgs e)
        {
            Console.WriteLine("Test event 1");
        }
        //This handler is auto-generated by designer, after adding the event in the designer
        private void radioButton2_CheckedChanged(object sender, EventArgs e)
        {
            Console.WriteLine("Test event 2");
        }
    }
