    MailMessage emailMessage = new MailMessage();
            emailMessage.From = new MailAddress("account2@gmail.com", "Account2");
            emailMessage.To.Add(new MailAddress("account1@gmail.com", "Account1"));
            emailMessage.Subject = "SUBJECT";
            emailMessage.Body = "BODY";
            emailMessage.Priority = MailPriority.Normal;
            SmtpClient MailClient = new SmtpClient("smtp.gmail.com", 587);
            MailClient.EnableSsl = true;
            MailClient.Credentials = new System.Net.NetworkCredential("account2@gmail.com", "password");
            MailClient.Send(emailMessage);
