    // generated by VS
    [global::System.Configuration.ApplicationScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
    public global::System.TimeSpan SqlCommandTimeout {
      get {
        return ((global::System.TimeSpan)(this["SqlCommandTimeout"]));
      }
     }
