    DataTable Client = new DataTable();
    Client.Columns.Add("ClientID");
    Client.Columns.Add("CustomerID");
    Client.Columns.Add("Enabled");
    DataRow Client1 = Client.NewRow();
    Client1["ClientID"] = 1;
    Client1["CustomerID"] = 1;
    Client1["Enabled"] = true;
    Client.Rows.Add(Client1);
    DataRow Client2 = Client.NewRow();
    Client2["ClientID"] = 2;
    Client2["CustomerID"] = 2;
    Client2["Enabled"] = true;
    Client.Rows.Add(Client2);
    DataRow Client3 = Client.NewRow();
    Client3["ClientID"] = 3;
    Client3["CustomerID"] = 2;
    Client3["Enabled"] = false;
    Client.Rows.Add(Client3);
    DataRow Client4 = Client.NewRow();
    Client4["ClientID"] = 4;
    Client4["CustomerID"] = 3;
    Client4["Enabled"] = false;
    Client.Rows.Add(Client4);
