    public override UITableViewCell GetCell (UITableView tv)
    {
    ...
    static NSString hkey = new NSString ("WhateverYouWantElement"); //very important to set a unique cell reuse identifier here!
    ...
    cell.Accessory = UITableViewCellAccessory.None;
    ...
    }
