    ...
    [ConfigurationCollection(typeof(LoggerRegistration), AddItemName = "LoggerRegistration")]
    public class LoggerRegistrations : ConfigurationElementCollection
    {
    ...
    .
    ...
    [ConfigurationCollection(typeof(LogMapperElement), AddItemName = "LogMapper")]
    public class LogMappers : ConfigurationElementCollection
    ...
