    //Declaration of the System.Windows.Control.ContentControl class,
    //inside the PresentationFramework.dll assembly
    //...  
    [ContentProperty("Content")]
    public class ContentControl: Control //...
    {
       //...
    }
