    Edm.Binary ==> System.Byte[]
	Edm.Boolean ==> System.Boolean
	Edm.Byte ==> System.Byte
	Edm.DateTime ==> System.DateTime
	Edm.Decimal ==> System.Decimal
	Edm.Double ==> System.Double
	Edm.Guid ==> System.Guid
	Edm.Single ==> System.Single
	Edm.SByte ==> System.SByte
	Edm.Int16 ==> System.Int16
	Edm.Int32 ==> System.Int32
	Edm.Int64 ==> System.Int64
	Edm.String ==> System.String
	Edm.Time ==> System.TimeSpan
	Edm.DateTimeOffset ==> System.DateTimeOffset
	Edm.Geometry ==> System.Data.Spatial.DbGeometry
	Edm.Geography ==> System.Data.Spatial.DbGeography
	Edm.GeometryPoint ==> System.Data.Spatial.DbGeometry
	Edm.GeometryLineString ==> System.Data.Spatial.DbGeometry
	Edm.GeometryPolygon ==> System.Data.Spatial.DbGeometry
	Edm.GeometryMultiPoint ==> System.Data.Spatial.DbGeometry
	Edm.GeometryMultiLineString ==> System.Data.Spatial.DbGeometry
	Edm.GeometryMultiPolygon ==> System.Data.Spatial.DbGeometry
	Edm.GeometryCollection ==> System.Data.Spatial.DbGeometry
	Edm.GeographyPoint ==> System.Data.Spatial.DbGeography
	Edm.GeographyLineString ==> System.Data.Spatial.DbGeography
	Edm.GeographyPolygon ==> System.Data.Spatial.DbGeography
	Edm.GeographyMultiPoint ==> System.Data.Spatial.DbGeography
	Edm.GeographyMultiLineString ==> System.Data.Spatial.DbGeography
	Edm.GeographyMultiPolygon ==> System.Data.Spatial.DbGeography
	Edm.GeographyCollection ==> System.Data.Spatial.DbGeography
