    string connectionString = WebConfigurationManager.ConnectionStrings["myString"].ConnectionString;
    SqlConnection connection = new SqlConnection(connectionString);
    StringBuilder sql = new StringBuilder();
    sql.Append("SELECT topic.topic_ID, topic.topic_title FROM FPL2012_TOPIC as topic WHERE topic.topic_isEnabled = 1;");
    sql.Append("SELECT explain.itemExplanationType_ID, explain.itemExplanationType_type FROM FPL2012_ITEM_EXPLANATION_TYPE as explain;");
    SqlCommand command = new SqlCommand(sql.ToString(), connection);
    connection.Open();
    SqlDataReader reader = command.ExecuteReader();
    topicDropDownList.DataSource = reader;
    topicDropDownList.DataValueField = "topic_ID";
    topicDropDownList.DataTextField = "topic_title";
    topicDropDownList.DataBind();
    reader.NextResult();
    explanationTypeDropDownList.DataSource = reader;
    explanationTypeDropDownList.DataValueField = "itemExplanationType_ID";
    explanationTypeDropDownList.DataTextField = "itemExplanationType_type";
    explanationTypeDropDownList.DataBind();
    reader.Close();
    connection.Close();
