            // creating a driver service
            var driverService = ChromeDriverService.CreateDefaultService();
            _driver = new ChromeDriver(driverService);
            //create list of process id
            var driverProcessIds = new List<int> { driverService.ProcessId };
            //Get all the childs generated by the driver like conhost, chrome.exe...
            var mos = new System.Management.ManagementObjectSearcher($"Select * From Win32_Process Where ParentProcessID={driverService.ProcessId}");
            foreach (var mo in mos.Get())
            {
                var pid = Convert.ToInt32(mo["ProcessID"]);
                driverProcessIds.Add(pid);
            }
            //Kill all
            foreach (var id in driverProcessIds)
            {
                System.Diagnostics.Process.GetProcessById(id).Kill();
            }
