    ...
    this.radioButton1.Click += new System.EventHandler(this.radioButton1_Click);
    ...
    this.button1.Click += new System.EventHandler(this.button1_Click);
    ...
    this.listView1.Click += new System.EventHandler(this.listView1_Click);
    ...
    this.Click += new System.EventHandler(this.UserControl1_Click);
    ...
