    public class Generator
    {
        //...
        public IEnumerable<Instruction> Generate()
        {
            // ...
            yield return new Instruction(...);
            // ...
        }
        //...
    }
