    namespace Dal
    {
        public partial class User
        {
            // This class is auto generated by using EF database-first
            // We can't edit this class to add the inheritance,
            // because it will be overwritten every time
            // we update our model using the database-first tools
        }
    }
