    var identity = new ClaimsIdentity(context.Options.AuthenticationType);
    ...
    // other claims
    ...
    identity.AddClaim(new Claim(ClaimTypes.Role, "admins"));
    ...
    var ticket = new AuthenticationTicket(identity, properties);
    context.Validated(ticket);
