    public class MyJqGridHelper<TModel>: JqGridHelper<TModel>
    {
        public MyJqGridHelper(string id="Grid",string afterInsertRow = null,string afterEditCell = null,string afterRestoreCell = null,string afterSaveCell = null,string afterSubmitCell = null,string altClass = "ui-priority-secondary",bool altRows = false,bool autoEncode = false,bool autoWidth = true,string beforeRequest = null,string beforeSelectRow = null,string beforeEditCell = null,string beforeSaveCell = null,string beforeSubmitCell = null,string caption = null,int cellLayout = 5,bool cellEditingEnabled = false,JqGridCellEditingSubmitModes cellEditingSubmitMode = JqGridCellEditingSubmitModes.Remote,string cellEditingUrl = null,string dataString = null,JqGridDataTypes dataType = JqGridDataTypes.Json,bool deepEmpty = false,JqGridLanguageDirections direction = JqGridLanguageDirections.Ltr,JqGridDynamicScrollingModes dynamicScrollingMode = JqGridDynamicScrollingModes.Disabled,int dynamicScrollingTimeout = 200,string editingUrl = null,string emptyRecords = "No resultes found.",bool expandColumnClick = true,string expandColumn = null,int? height = null,string errorCell = null,string formatCell = null,bool footerEnabled = false,bool gridView = false,bool groupingEnabled = false,JqGridGroupingView groupingView = null,bool headerTitles = false,bool hidden = false,bool hiddenEnabled = true,bool ignoreCase = true,JqGridJsonReader jsonReader = null,string loadBeforeSend = null,string loadError = null,string loadComplete = null,bool loadOnce = true,JqGridMethodTypes methodType = JqGridMethodTypes.Get,JqGridMultiKeys? multiKey = null,bool multiBoxOnly = false,bool multiSelect = false,int multiSelectWidth = 20,bool multiSort = false,string gridComplete = null,string onCellSelect = null,string onDoubleClickRow = null,string onHeaderClick = null,string onInitGrid = null,string onPaging = null,string onRightClickRow = null,string onSelectAll = null,string onSelectCell = null,string onSelectRow = null,string onSortCol = null,bool pager = true,JqGridParametersNames parametersNames = null,object postData = null,string postDataScript = null,string resizeStart = null,string resizeStop = null,string rowAttributes = null,List<int> rowsList = null,int rowsNumber = 20,bool rowsNumbers = false,int rowsNumbersWidth = 25,bool shrinkToFit = true,int scrollOffset = 18,string serializeCellData = null,string serializeGridData = null,string serializeSubGridData = null,bool sortable = false,string sortingName = "",JqGridSortingOrders sortingOrder = JqGridSortingOrders.Asc,bool subgridEnabled = false,JqGridSubgridModel subgridModel = null,object subgridHelper = null,string subgridUrl = null,int subgridColumnWidth = 20,string subGridBeforeExpand = null,string subGridRowColapsed = null,string subGridRowExpanded = null,bool topPager = false,bool treeGridEnabled = false,JqGridTreeGridModels treeGridModel = JqGridTreeGridModels.Nested,string url = null,bool userDataOnFooter = false,bool viewRecords = true,int? width = null)
        : base (id,afterInsertRow,afterEditCell,afterRestoreCell,afterSaveCell,afterSubmitCell,altClass,altRows ,autoEncode,autoWidth,beforeRequest,beforeSelectRow,beforeEditCell,beforeSaveCell,beforeSubmitCell,  caption, cellLayout, cellEditingEnabled, cellEditingSubmitMode,cellEditingUrl,dataString,dataType,deepEmpty,direction,  dynamicScrollingMode, dynamicScrollingTimeout, editingUrl, emptyRecords, expandColumnClick,  expandColumn ,height, errorCell, formatCell, footerEnabled, gridView, groupingEnabled , groupingView, headerTitles , hidden  ,  hiddenEnabled , ignoreCase , jsonReader , loadBeforeSend , loadError , loadComplete , loadOnce , methodType , multiKey , multiBoxOnly, multiSelect , multiSelectWidth , multiSort , gridComplete , onCellSelect , onDoubleClickRow , onHeaderClick , onInitGrid , onPaging , onRightClickRow , onSelectAll , onSelectCell , onSelectRow , onSortCol , pager , parametersNames , postData , postDataScript , resizeStart , resizeStop , rowAttributes , rowsList , rowsNumber , rowsNumbers , rowsNumbersWidth , shrinkToFit , scrollOffset , serializeCellData , serializeGridData , serializeSubGridData , sortable , sortingName , sortingOrder , subgridEnabled , subgridModel , subgridHelper , subgridUrl , subgridColumnWidth , subGridBeforeExpand , subGridRowColapsed , subGridRowExpanded , topPager  , treeGridEnabled , treeGridModel  , url , userDataOnFooter , viewRecords ,  width )
        {
            //other stuff here, if you want to do something different after calling base constructor
        }
    }
    
