    [Fact]
    public void CustomizedAutoFixtureTest()
    {
        var fixture = new Fixture();
        fixture.Customizations.Add(
            new PossibilityCustomization());
        var possibilities = 
            new Generator<Possibility>(fixture).Take(3);
        // 1st iteration
        // -------------------
        // aValue       | null
        // anotherValue | null 
        // 2nd iteration
        // -------------------
        // aValue       | 10
        // anotherValue | 42
        // 3rd iteration
        // -------------------
        // aValue       | 20
        // anotherValue | (Queue is empty, generated by AutoFixture.)
    }
