    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    // Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
        
    // Generated from: my.proto
    namespace my
    {
      [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Foo")]
      public partial class Foo : global::ProtoBuf.IExtensible
      {
        public Foo() {}
        
        private int? _value;
        [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int value
        {
          get { return _value?? (int)123; }
          set { _value = value; }
        }
        [global::System.Xml.Serialization.XmlIgnore]
        [global::System.ComponentModel.Browsable(false)]
        public bool valueSpecified
        {
          get { return this._value != null; }
          set { if (value == (this._value== null)) this._value = value ? this.value : (int?)null; }
        }
        private bool ShouldSerializevalue() { return valueSpecified; }
        private void Resetvalue() { valueSpecified = false; }
        
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
          { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
      }
      
    }
