            protected void gvGridView_RowDataBound(Object sender, GridViewRowEventArgs e)
            {
                DataRowView drv = (DataRowView)e.Row.DataItem;
 
                if (e.Row.RowType == DataControlRowType.DataRow)
                {
    
                    for (int i = 0; i < ct_columns; i++)
                    {
                        DataControlFieldCell dcf = e.Row.Cells[i] as DataControlFieldCell;
    
                        /* default date format: hide 'time' values */
                        if (e.Row.RowIndex == 0 
                            && (dcf.ContainingField.GetType().Name == "BoundField"           // defined columns
                            || dcf.ContainingField.GetType().Name == "AutoGeneratedField"))  // auto-generated columns 
                        {
                            BoundField bf = dcf.ContainingField as BoundField;
    
                            if (bf != null && String.IsNullOrEmpty(bf.DataFormatString))
                            {
                                string col_name = bf.DataField;
    
                                if (!String.IsNullOrEmpty(col_name) && drv[col_name] != null)
                                {
                                    if (drv[col_name].GetType().Name == "DateTime")
                                    {
                                        // set format for first row
                                        string date = drv[col_name].ToString();
                                        if (!String.IsNullOrEmpty(date))
                                            dcf.Text = DateTime.Parse(date).ToShortDateString();
    
                                        // set format for other rows
                                        bf.DataFormatString = "{0:M/dd/yyyy}";  
                                    }
    
                                }
                            }
                        }
                    }
                }
            }
