    public class MyDerivedGridViewColumnsGenerator : GridViewColumnsGenerator
    {
       public override List<AutoGeneratedField> CreateAutoGeneratedFields(
          object dataObject, Control control)
       {
           var list = base.CreatedAutoGeneratedFields(dataObject, control);
           foreach(var field in list)
           {
             if(field.DataType == typeof(DateTime))
                 field.DataFormatString = "dd-MMM-yyyy";
           }
           return list;
       }
    }
