    using System;
    using System.Linq;
    using System.Net;
    using System.Xml;
    using System.Xml.Linq;
    
    public class Program
    {
        public static void Main()
        {
           var result =  WeatherAPI("London");
    
            // loop throw all weather instances... 
            foreach (var w in result.Descendants("weather"))
            {
                Console.WriteLine("Weather");
                Console.WriteLine("=================");
                foreach (var e in w.Elements())
                {
                    Console.WriteLine(string.Format("Key {0} - Value {1}", e.Name, e.Value));
                }
            }
    
            // if you want to select specific element then use this.
            var currentCondition = result.Descendants("current_condition").FirstOrDefault();
            if (currentCondition != null)
            {
                Console.WriteLine("Current Condition");
                Console.WriteLine("=================");
                foreach (var e in currentCondition.Elements())
                {
                    Console.WriteLine(string.Format("Key {0} - Value {1}", e.Name, e.Value));
                }
            }
    
            Console.ReadLine();
        }
    
        public static XDocument WeatherAPI(string sLocation)
        {
            HttpWebRequest webRequest;
            HttpWebResponse webResponse = null;
            XDocument xmlResult = null;
            var apiKey = "Your key"; //The API key generated by World Weather Online
            var apiEndpoint = "http://api.worldweatheronline.com/free/v1/weather.ashx?format=xml&";
    
            try
            {
                //Here we are concatenating the parameters
                webRequest =
                    (HttpWebRequest) WebRequest.Create(string.Format(apiEndpoint + "q=" + sLocation + "&key=" + apiKey));
                webRequest.UserAgent =
                    @"Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.8.1.4) Gecko/20070515 Firefox/2.0.0.4";
                //Making the request
                webResponse = (HttpWebResponse) webRequest.GetResponse();
                xmlResult = XDocument.Load(webResponse.GetResponseStream());
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            finally
            {
                if (webResponse != null)
                {
                    webResponse.Close();
                }
            }
            
    
            return xmlResult;
                // Here we get the five values from the website in xml format. Now I want   those xml values from this "WP_XMLdoc" variable to diplay on textbox or labels.
        }
    }
 
