            List<BO.TestClass> list = new List<BO.TestClass>();
            BO.TestClass c1 = new BO.TestClass();
            c1.Level = 4;
            list.Add(c1);
            BO.TestClass c2 = new BO.TestClass();
            c2.Level = 3;
            list.Add(c2);
            BO.TestClass c3 = new BO.TestClass();
            c3.Level = 9;
            list.Add(c3);
            BO.TestClass c4 = new BO.TestClass();
            c4.Level = 2;
            list.Add(c4);
            BO.TestClass c5 = new BO.TestClass();
            c5.Level = 1;
            list.Add(c5);
            BO.TestClass c6 = new BO.TestClass();
            c6.Level = 8;
            list.Add(c6);
            List<BO.TestClass> test = list.Where(x => x.Level > 3).ToList();
