                DataColumn dc1 = new DataColumn("رقم المتسلسل");
                DataColumn dc2 = new DataColumn("رقم الحساب");
                DataColumn dc3 = new DataColumn("أسم الحساب");
                DataColumn dc4 = new DataColumn("المالك");
                DataColumn dc5 = new DataColumn("تاريخ");
                DataColumn dc6 = new DataColumn("قيمة");
                DataColumn dc7 = new DataColumn("نوع العملة");
                DataColumn dc8 = new DataColumn("البيان");
                DataColumn dc9 = new DataColumn("الدائن");
                DataColumn dc10 = new DataColumn("المدين");
                DataColumn dc11 = new DataColumn(" اجمالي الدائن");
                DataColumn dc12 = new DataColumn("اجمالي المدين");
                DataColumn dc13 = new DataColumn("تفاصيل");
                DataColumn dc14 = new DataColumn("التأكيد");
                dtab.Columns.Add(dc1);
                dtab.Columns.Add(dc2);
                dtab.Columns.Add(dc3);
                dtab.Columns.Add(dc4);
                dtab.Columns.Add(dc5);
                dtab.Columns.Add(dc6);
                dtab.Columns.Add(dc7);
                dtab.Columns.Add(dc8);
                dtab.Columns.Add(dc9);
                dtab.Columns.Add(dc10);
                dtab.Columns.Add(dc11);
                dtab.Columns.Add(dc12);
                dtab.Columns.Add(dc13);
                dtab.Columns.Add(dc14);
