            DropIndex("dbo.UserClaim", new[] { "ApplicationUser_Id" });
            DropIndex("dbo.UserLogin", new[] { "ApplicationUser_Id" });
            DropIndex("dbo.UserRole", new[] { "ApplicationUser_Id" });
            DropIndex("dbo.UserRole", new[] { "IdentityRole_Id" });
            DropForeignKey("FK_dbo_UserClaim_ApplicationUser_Id", "ApplicationUser_Id");
            DropForeignKey("FK_dbo_UserLogin_ApplicationUser_Id", "ApplicationUser_Id");
            DropForeignKey("FK_dbo_UserRole_ApplicationUser_Id", "ApplicationUser_Id");
            DropForeignKey("FK_dbo_UserRole_IdentityRole_Id", "Identity_Id");
            DropColumn("dbo.UserClaim", "ApplicationUser_Id");
            DropColumn("dbo.UserLogin", "ApplicationUser_Id");
            DropColumn("dbo.UserRole", "ApplicationUser_Id");
            DropColumn("dbo.UserRole", "IdentityRole_Id");
            //DropPrimaryKey("dbo.UserLogin");
            //DropPrimaryKey("dbo.UserRole");
            AlterColumn("dbo.User", "Email", c => c.String(maxLength: 256));
            AlterColumn("dbo.User", "UserName", c => c.String(nullable: false, maxLength: 256));
            AlterColumn("dbo.UserClaim", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserClaim", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserLogin", "LoginProvider", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserLogin", "ProviderKey", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserLogin", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserRole", "UserId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.UserRole", "RoleId", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.Role", "Name", c => c.String(nullable: false, maxLength: 256));
            //AddPrimaryKey("dbo.UserLogin", new[] { "LoginProvider", "ProviderKey", "UserId" });
            //AddPrimaryKey("dbo.UserRole", new[] { "UserId", "RoleId" });
            CreateIndex("dbo.User", "UserName", unique: true, name: "UserNameIndex");
            CreateIndex("dbo.UserClaim", "UserId");
            CreateIndex("dbo.UserLogin", "UserId");
            CreateIndex("dbo.UserRole", "UserId");
            CreateIndex("dbo.UserRole", "RoleId");
            CreateIndex("dbo.Role", "Name", unique: true, name: "RoleNameIndex");
