    public static bool IsPropertyChanged(PropertyDescriptor pd, object entity1, object entity2, int depth)
        {
            if (depth > 3) return false;
            ...
            ...
            if (!pd.PropertyInfo.PropertyType.IsPrimitive || !(pd.PropertyInfo.PropertyType == typeof(String)))
            {
                return IsComplexChanged(pd, val1, val2, depth);
            }
            ...
            ...
        }
