        protected void btnAdd_Click(object sender, EventArgs e)
        {
            SqlCommand command = new SqlCommand();
            command.Connection = conn;
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "AddRecord";
            command.Connection.Open();
            SqlParameter pCustID = new SqlParameter();
            pCustID.ParameterName = "@CustID";
            pCustID.SqlDbType = SqlDbType.Int;
            pCustID.Direction = ParameterDirection.Input;
            pCustID.Value = txtCustID.Text;
            command.Parameters.Add(pCustID);
            SqlParameter pFirst = new SqlParameter();
            pFirst.ParameterName = "@First";
            pFirst.SqlDbType = SqlDbType.VarChar;
            pFirst.Direction = ParameterDirection.Input;
            pFirst.Value = txtFirstName.Text;
            command.Parameters.Add(pFirst);
            SqlParameter pSurn = new SqlParameter();
            pSurn.ParameterName = "@Surname";
            pSurn.SqlDbType = SqlDbType.VarChar;
            pSurn.Direction = ParameterDirection.Input;
            pSurn.Value = txtSurname.Text;
            command.Parameters.Add(pSurn);
            SqlParameter pGen = new SqlParameter();
            pGen.ParameterName = "@Gender";
            pGen.SqlDbType = SqlDbType.VarChar;
            pGen.Direction = ParameterDirection.Input;
            pGen.Value = rblGender.SelectedValue;
            command.Parameters.Add(pGen);
            SqlParameter pAge = new SqlParameter();
            pAge.ParameterName = "@Age";
            pAge.SqlDbType = SqlDbType.Int;
            pAge.Direction = ParameterDirection.Input;
            pAge.Value = txtAge.Text;
            command.Parameters.Add(pAge);
            SqlParameter pAdd1 = new SqlParameter();
            pAdd1.ParameterName = "@Address1";
            pAdd1.SqlDbType = SqlDbType.VarChar;
            pAdd1.Direction = ParameterDirection.Input;
            pAdd1.Value = txtAddress1.Text;
            command.Parameters.Add(pAdd1);
            SqlParameter pAdd2 = new SqlParameter();
            pAdd2.ParameterName = "@Address2";
            pAdd2.SqlDbType = SqlDbType.VarChar;
            pAdd2.Direction = ParameterDirection.Input;
            pAdd2.Value = txtAddress2.Text;
            command.Parameters.Add(pAdd2);
            SqlParameter pCity = new SqlParameter();
            pCity.ParameterName = "@City";
            pCity.SqlDbType = SqlDbType.VarChar;
            pCity.Direction = ParameterDirection.Input;
            pCity.Value = txtCity.Text;
            command.Parameters.Add(pCity);
            SqlParameter pPhone = new SqlParameter();
            pPhone.ParameterName = "@Phone";
            pPhone.SqlDbType = SqlDbType.VarChar;
            pPhone.Direction = ParameterDirection.Input;
            pPhone.Value = txtPhone.Text;
            command.Parameters.Add(pPhone);
            SqlParameter pMobile = new SqlParameter();
            pMobile.ParameterName = "@Mobile";
            pMobile.SqlDbType = SqlDbType.VarChar;
            pMobile.Direction = ParameterDirection.Input;
            pMobile.Value = txtMobile.Text;
            command.Parameters.Add(pMobile);
            SqlParameter pEmail = new SqlParameter();
            pEmail.ParameterName = "@Email";
            pEmail.SqlDbType = SqlDbType.VarChar;
            pEmail.Direction = ParameterDirection.Input;
            pEmail.Value = txtEmail1.Text;
            command.Parameters.Add(pEmail);
            SqlDataReader reader = command.ExecuteReader();
            reader.Dispose();
            command.Dispose();
            conn.Dispose();
        }
    }
