    protected virtual void SetProperty(ControllerContext controllerContext, ModelBindingContext bindingContext, PropertyDescriptor propertyDescriptor, object value)
    {
      ...
      if (!propertyDescriptor.IsReadOnly && !isNullValueOnNonNullableType)
      {
        ...
        propertyDescriptor.SetValue(bindingContext.Model, value) // this is where the value is set
        ...
      }
      ...
    }
