    // Original but incorrect sequence
    FileStream fs = File.OpenRead(dlgOpen.FileName); // Open the file
    byte[] picbyte1 = new byte[fs.Length]; // Assign the array
    byte[] picbyte = Compress(picbyte1); // Compress the assigned array, but there is no contents...
    fs.Read(picbyte, 0, System.Convert.ToInt32(picbyte.Length)); // You save the file to the already compressed bytes...
