{
    "UserAccount": "",
    "UserPassword": "",
    "ExtraInfo": ""
}
    // Generated by Xamasoft JSON Class Generator
    // http://www.xamasoft.com/json-class-generator
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json.Linq;
    namespace CommonModels
    {
        public class loginArgs
        {
            public string UserAccount { get; set; }
            public string UserPassword { get; set; }
            public string ExtraInfo { get; set; }
        }
    }
