        void dgUsers_AutoGeneratedColumns(object sender, EventArgs e)
        {
            foreach (var oColumn in dgUsers.Columns)
            {
                // This is how to set the width to auto
                oColumn.Width = DataGridLength.Auto;
                // The header will contain the column name, so you can change it as needed
                switch (oColumn.Header.ToString().ToLowerInvariant())
                {
                    case "id":
                        oColumn.Header = "Identifier";
                        break;
                        // etc.
                }
            }
        }
