    public class Target : ObservableObject
    {
        public Point3D PositionX...
		public Point3D PositionZ...
		
        public double DeltaX...
        public double DeltaZ...
        public Point3D PositionScreen...
        
        public double RectangleSize...
        public Brush RectangleBrush...
    }
