    foreach (DataRow fieldRow in myDataset.Tables["tempTable"].AsEnumerable())
    {
        // ...
        DataTable AItem = new DataTable("AItem");
        // ...
        AllItems.Tables.Add(AItem);
        // ...
    }
