    mscorlib.dll!System.Collections.Concurrent.ConcurrentStack<object>.Push(object item)
    System.dll!System.PinnableBufferCache.Free(object buffer)
    System.dll!System.Net.HttpWebRequest.FreeWriteBuffer()
    System.dll!System.Net.ConnectStream.WriteHeadersCallback(System.IAsyncResult ar)
    System.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken)
    System.dll!System.Net.ContextAwareResult.Complete(System.IntPtr userToken)
    System.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken)
    System.dll!System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped)
    mscorlib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)
