        string[] innerrow1 = new string[] { "50", "60", "70" };
        string[] innerrow2 = new string[] { "a", "b", "c" };
        DataGridViewTextBoxColumn Col1 = new DataGridViewTextBoxColumn();
        Col1.HeaderText = "Product ID";
        dataGridView1.Columns.Add(Col1);
        DataGridViewComboBoxColumn Col2 = new DataGridViewComboBoxColumn();
        Col2.HeaderText = "Product Name";
        Col2.Name = "Product Name";
        Col2.MaxDropDownItems = 3;
        Col2.Items.Add(innerrow1[0]);
        Col2.Items.Add(innerrow1[1]);
        Col2.Items.Add(innerrow1[2]);
        dataGridView1.Columns.Add(Col2);
        DataGridViewTextBoxColumn Col3 = new DataGridViewTextBoxColumn();
        Col3.HeaderText = "Product Price";
        dataGridView1.Columns.Add(Col3);
        dataGridView1.Rows.Add(new object[] { "1", innerrow1[0], "1000" });
        dataGridView1.Rows.Add(new object[] { "2", innerrow1[1], "2000" });
        dataGridView1.Rows.Add(new object[] { "3", innerrow1[2], "3000" });
