    public event EventHandler<MasterSaveEventArgs> Master_Save;
    ...
    { Master_Save(this, new MasterSaveEventArgs(i)); }
    ...
    (this.Page.Master as Pages_MasterPage).Master_Save += ContentPage_Save;
    // notice the shortened syntax here
    ...
    private void ContentPage_Save(object sender, MasterSaveEventArgs e)
