    public event EventHandler<MasterSaveEventArgs> Master_Save;
    ...
    { Master_Save(this, new MasterSaveEventArgs(i)); }
    ...
    private void ContentPage_Save(object sender, MasterSaveEventArgs e)
