        [assembly: PreApplicationStartMethod(typeof(StructuremapMvc), "Start")]
        public static class StructuremapMvc {
           public static void Start() {
                    MiniProfilerEF6.Initialize();
    ...
    ...
