    dataGrid.AutoGeneratedColumns += DataGrid1_AutoGeneratedColumns;
    void DataGrid1_AutoGeneratedColumns(object sender, EventArgs e)
    {
         int columnsCount = DataGrid1.Columns.Count;
         //You can access the columns here.
    }
