    [ controller=CarController action=System.Net.Http.HttpResponseMessage Login()]
    [ controller=CarController action=Void MyCustomGet()]
    [ controller=CarController action=Void MyCustomPost()]
    [ controller=GenericControllerApi action=System.Net.Http.HttpResponseMessage Login()]
    [ controller=ValuesController action=System.String Get()]
    [ controller=ValuesController action=System.String Get(Int32)]
    [ controller=ValuesController action=Void Post(System.String)]
    [ controller=ValuesController action=Void Put(Int32, System.String)]
    [ controller=ValuesController action=Void Delete(Int32)]
    [ controller=ODataMetadataController action=Microsoft.Data.Edm.IEdmModel GetMetadata()]
    [ controller=ODataMetadataController action=Microsoft.Data.OData.ODataWorkspace GetServiceDocument()]
