    Container c = new Container(null,0);
	c.AddChildren("2.2.2");
	Console.WriteLine(c.Containers[0].GetPath());
	Console.WriteLine(c.Containers[1].GetPath());
	Console.WriteLine(c.Containers[2].GetPath());
	Console.WriteLine(c.Containers[2].Containers[0].GetPath());
	Console.WriteLine(c.Containers[2].Containers[1].GetPath());
	Console.WriteLine(c.Containers[2].Containers[2].GetPath());
	Console.WriteLine(c.Containers[2].Containers[2].Containers[0].GetPath());
	Console.WriteLine(c.Containers[2].Containers[2].Containers[1].GetPath());
	Console.WriteLine(c.Containers[2].Containers[2].Containers[2].GetPath());
