    // This line of code is generated by Data Source Configuration Wizard
    // Instantiate a new DBContext
    NorthwindEntities dbContext = new NorthwindEntities();
    // Call the Load method to get the data for the given DbSet from the database.
    dbContext.Orders.Load();
    // This line of code is generated by Data Source Configuration Wizard
    bindingSource.DataSource = dbContext.Orders.Local.ToBindingList();
