        private DataSet m_ds = new DataSet();
        private CurrencyManager m_Currency;
        private void Form8_Load(object sender, EventArgs e)
        {
            DataTable T1 = m_ds.Tables.Add("T1");
            T1.Columns.Add("T"); 
            T1.Columns.Add("V");
            DataRow T1_ROW = T1.NewRow();
            T1_ROW["T"] = "1";
            T1_ROW["V"] = "1";
            T1.Rows.Add(T1_ROW);
            T1_ROW = T1.NewRow();
            T1_ROW["T"] = "2";
            T1_ROW["V"] = "2";
            T1.Rows.Add(T1_ROW);
            T1_ROW = T1.NewRow();
            T1_ROW["T"] = "3";
            T1_ROW["V"] = "3";
            T1.Rows.Add(T1_ROW);
            T1_ROW = T1.NewRow();
            T1_ROW["T"] = "4";
            T1_ROW["V"] = "4";
            T1.Rows.Add(T1_ROW);
            comboBox1.DataSource = T1;
            comboBox1.DisplayMember = "T";
            comboBox1.ValueMember = "V";
            m_Currency = this.BindingContext[m_ds, "T1"] as CurrencyManager;
            DataTable T2 = m_ds.Tables.Add("T2");
            T2.Columns.Add("ID");
            T2.Columns.Add("T");
            T2.Columns.Add("V");
            DataRow T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "1";
            T2_ROW["T"] = "1-1";
            T2_ROW["V"] = "1-1";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "1";
            T2_ROW["T"] = "1-2";
            T2_ROW["V"] = "1-2";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "1";
            T2_ROW["T"] = "1-3";
            T2_ROW["V"] = "1-3";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "1";
            T2_ROW["T"] = "1-4";
            T2_ROW["V"] = "1-4";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "2";
            T2_ROW["T"] = "2-1";
            T2_ROW["V"] = "2-1";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "2";
            T2_ROW["T"] = "2-2";
            T2_ROW["V"] = "2-2";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "2";
            T2_ROW["T"] = "2-3";
            T2_ROW["V"] = "2-3";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "2";
            T2_ROW["T"] = "2-4";
            T2_ROW["V"] = "2-4";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "3";
            T2_ROW["T"] = "3-1";
            T2_ROW["V"] = "3-1";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "3";
            T2_ROW["T"] = "3-2";
            T2_ROW["V"] = "3-2";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "3";
            T2_ROW["T"] = "3-3";
            T2_ROW["V"] = "3-3";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "3";
            T2_ROW["T"] = "3-4";
            T2_ROW["V"] = "3-4";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "4";
            T2_ROW["T"] = "4-1";
            T2_ROW["V"] = "4-1";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "4";
            T2_ROW["T"] = "4-2";
            T2_ROW["V"] = "4-2";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "4";
            T2_ROW["T"] = "4-3";
            T2_ROW["V"] = "4-3";
            T2.Rows.Add(T2_ROW);
            T2_ROW = T2.NewRow();
            T2_ROW["ID"] = "4";
            T2_ROW["T"] = "4-4";
            T2_ROW["V"] = "4-4";
            T2.Rows.Add(T2_ROW);
            System.Data.DataColumn T1_V = null;
            System.Data.DataColumn T2_V = null;
            T1_V = m_ds.Tables["T1"].Columns["V"];
            T2_V = m_ds.Tables["T2"].Columns["ID"];
            System.Data.DataRelation REL = new DataRelation("COM_ID", T1_V, T2_V);
            m_ds.Relations.Add(REL);
            comboBox2.DataSource = m_ds;
            comboBox2.DisplayMember = "T1.COM_ID.T";
            comboBox2.DisplayMember = "T1.COM_ID.V";
        }
        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            DataRow[] Rows = m_ds.Tables["T1"].Select("V = '" + Convert.ToString(comboBox1.SelectedValue) + "'");
            if (Rows.Count() < 1)
                return;
            m_Currency.Position = m_ds.Tables["T1"].Rows.IndexOf(Rows[0]);
        }
