    public class SmartEngine : IEngine
    {
          ...
          public void Start() { Console.WriteLine("SmartEngine"); } 
          ...
    }
  
    public class TurboEngine : IEngine 
    {
          ...
          public void Start() { Console.WriteLine("TurboEngine"); } 
          ...
    }
