    Mock<IIsesServiceChannel> channelMock = new Mock<IIsesServiceChannel>(MockBehavior.Strict);
    ...
    ArticleDataGridViewModel articleDataGridViewModel = new ArticleDataGridViewModel(channelMock.Object);
    ...
    string result = articleDataGridViewModel.IsesService.GetArticleBody(1010000008);
