    items.Add(new ItemManager(0, "Small Health Potion", "Recovers 10% of Health Points", 0, (int)_smallHealth, 0, 0, 50, ItemManager.ItemType.Consumable, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(1, "Medium Health Potion", "Recovers 20% of Health Points", 0, (int)_mediumHealth, 0, 0, 100, ItemManager.ItemType.Consumable, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(2, "Large Health Potion", "Recovers 40% of Health Points", 0, (int)_largeHealth, 0, 0, 200, ItemManager.ItemType.Consumable, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(3, "Small Mana Potion", "Recovers 5% of Mana Points", 0, 0, (int)_smallMana, 0, 50, ItemManager.ItemType.Consumable, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(4, "Medium Mana Potion", "Recovers 10% of Mana Points", 0, 0, (int)_mediumMana, 0, 100, ItemManager.ItemType.Consumable, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(5, "Large Mana Potion", "Recovers 20% of Mana Points", 0, 0, (int)_largeMana, 0, 200, ItemManager.ItemType.Consumable, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(6, "Banana", "Recovers 25% of Health Points and 5% of Mana Points", 0, (int)_bananaHealth, (int)_bananaMana, 0, 225, ItemManager.ItemType.Foods, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(7, "Grape", "Recovers 45% of Health Points and 15% of Mana Points", 0, (int)_grapeHealth, (int)_grapeMana, 0, 350, ItemManager.ItemType.Foods, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(8, "Orange", "Recovers 65% Health Points and 25% of Mana Points", 0, (int)_orangeHealth, (int)_orangeMana, 0, 475, ItemManager.ItemType.Foods, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(9, "Pineapple", "Recovers 100% Health Points and 40% of Mana Points", 0, (int)_pineappleHealth, (int)_pineappleMana, 0, 600, ItemManager.ItemType.Foods, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(10, "Blue Katana", "A blue katana that made by Japanese people", 75, 0, 0, 0, 150, ItemManager.ItemType.Weapon, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(11, "Yellow Katana", "A yellow katana that made by Japanese people", 150, 0, 0, 0, 300, ItemManager.ItemType.Weapon, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(12, "Fire Katana", "A fire katana that made by Japanese people", 200, 0, 0, 0, 400, ItemManager.ItemType.Weapon, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(13, "Dark Katana", "A dark katana that made by Japanese people", 450, 0, 0, 0, 900, ItemManager.ItemType.Weapon, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(14, "Ice Katana", "An ice katana that made by Japanese people", 600, 0, 0, 0, 1200, ItemManager.ItemType.Weapon, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(15, "Silver Katana", "An ultimate silver katana that made by Japanese people", 1000, 0, 0, 0, 2000, ItemManager.ItemType.Weapon, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(16, "Ultimate Head Armor", "An ultimate head armor that protect the user", 100, 0, 0, 0, 1000, ItemManager.ItemType.Armor, ItemManager.ArmorType.Head));
    items.Add(new ItemManager(17, "Ultimate Body Armor", "An ultimate body armor that protect the user", 100, 0, 0, 0, 1000, ItemManager.ItemType.Armor, ItemManager.ArmorType.Body));
    items.Add(new ItemManager(18, "Ultimate Hand Armor", "An ultimate hand armor that protect the user", 100, 0, 0, 0, 1000, ItemManager.ItemType.Armor, ItemManager.ArmorType.Hand));
    items.Add(new ItemManager(19, "Ultimate Leg Armor", "An ultimate leg armor that protect the user", 100, 0, 0, 0, 1000, ItemManager.ItemType.Armor, ItemManager.ArmorType.Leg));
    items.Add(new ItemManager(20, "Wind Ring", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Ring, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(21, "Earth Ring", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Ring, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(22, "Fire Ring", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Ring, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(23, "Ice Ring", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Ring, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(24, "Wind Necklace", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Necklace, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(25, "Earth Necklace", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Necklace, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(26, "Fire Necklace", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Necklace, default(ItemManager.ArmorType)));
    items.Add(new ItemManager(27, "Ice Necklace", "Just an accessory with no effect to your status", 0, 0, 0, 0, 500, ItemManager.ItemType.Necklace, default(ItemManager.ArmorType)));
