    class AccessLevel {
        ...
        public static bool operator <=(AccessLevel x, AccessLevel y) {
            ...
        }
        public static bool operator >(AccessLevel x, AccessLevel y) {
            ...
        }
    }
