    // ...
    log4net.Config.XmlConfigurator.Configure();
    // ...
    iocBuilder.RegisterModule(new LoggingModule());
    iocBuilder.RegisterType<MyComponent>().AsSelf(); 
    // ...
    MyComponent c = iocContainer.Resolve<MyComponent>();
    c.Do(); 
