    private TaskCompletionSource<Something> _tcs = new TaskCompletionSource<Something>();
    public void FinishAwait(Something result) {
        _tcs.SetResult(result);
    }
    public async Task<Something> M() {
        // ...
        // ...
        var result = await _tcs.Task;
        // ...
        // ...
        return result;
    }
