    user.UserName = editUser.Email;
    user.Email = editUser.Email;
    user.Address = editUser.Address;
    user.City = editUser.City;
    user.State = editUser.State;
    user.PostalCode = editUser.PostalCode;
    // add these
    user.FirstName = editUser.FirstName;
    user.LastName = editUser.LastName;
