                Line line = new Line();
                SolidColorBrush brush = new SolidColorBrush();
                brush.Color = colorPicker2.SelectedColor;
                line.Stroke = brush;
                line.StrokeThickness = SliderThickness.Value;
                line.X1 = currentPoint.X;
                line.Y1 = currentPoint.Y;
                line.X2 = e.GetPosition(DrawPanel).X;
                line.Y2 = e.GetPosition(DrawPanel).Y;
                currentPoint = e.GetPosition(DrawPanel);
                DrawPanel.Children.Add(line);
                Point middlePoint = ((line.X1 + line.X2) / 2, (line.Y1 + line.Y2) / 2)
                Line newFirst = new Line();
                newFirst.X1 = line.X1;
                newFirst.Y1 = line.Y1;
                newFirst.X2 = middlePoint.X;
                newFirst.Y2 = middlePoint.Y;
                newFirst.Stroke = brush;
                newFirst.StrokeThickness = SliderThickness.Value;
                Line newSecond = new Line();
                newSecond.X1 = middlePoint.X;
                newSecond.Y1 = middlePoint.Y;
                newSecond.X2 = line.X2;
                newSecond.Y2 = line.Y2;
                newSecond.Stroke = brush;
                newSecond.StrokeThickness = SliderThickness.Value;
                DrawPanel.Children.Remove(line);
                DrawPanel.Children.Add(newFirst);
                DrawPanel.Children.Add(newSecond);
