    public static Font GetFont(string fontname, string encoding, bool embedded, float size, int style, BaseColor color)
    public static Font GetFont(string fontname, string encoding, bool embedded, float size, int style, BaseColor color, bool cached)
    public static Font GetFont(string fontname, string encoding, bool embedded, float size, int style)
    public static Font GetFont(string fontname, string encoding, bool embedded, float size)
    public static Font GetFont(string fontname, string encoding, bool embedded)
    public static Font GetFont(string fontname, string encoding, float size, int style, BaseColor color)
    public static Font GetFont(string fontname, string encoding, float size, int style)
    public static Font GetFont(string fontname, string encoding, float size)
    public static Font GetFont(string fontname, string encoding)
    public static Font GetFont(string fontname, float size, int style, BaseColor color)
    public static Font GetFont(string fontname, float size, BaseColor color)
    public static Font GetFont(string fontname, float size, int style)
    public static Font GetFont(string fontname, float size)
    public static Font GetFont(string fontname)
