    // Class generated by entity framework designer
    partial class User
    {
        // Entity framework designer can be told to declare private properties
        // with custom "Db" names
        private string DbEmail { get; set; }      // Maps to Email column
        private string DbAddress { get; set; }    // Maps to Address column
        private string DbCellPhone { get; set; }  // Maps to CellPhone column
        private string DbHomePhone { get; set; }  // Maps to HomePhone column
    }
    // Class declared in User.cs
    partial class User
    {
        public Email Email
        {
            get { return new Email(DbEmail); }
            set { DbEmail = value.ToString(); }
        }
        public Address Address
        {
            get { return new Address(DbAddress); }
            set { DbAddress = value.ToString(); }
        }
        /* and so on...*/
    }
