    public ViewModelConstructor(...)
    {
        ...
        SelectionChangedCommand = new DelegateCommand<>(SelectionChangedAction);
    }
    ...
    public ICommand SelectionChangedCommand { get; private set; }
    ...
