    <?xml version="1.0" encoding="UTF-8"?>
    <_Document_Definition>
    	<_Regions>
    		<_Region>
    			<_Name>regionStaticTextTerminDii</_Name>
    			<_Coordinates>
    				<_X1>241</_X1>
    				<_Y1>166</_Y1>
    				<_X2>683</_X2>
    				<_Y2>197</_Y2>
    			</_Coordinates>
    			<_BlockTypeEnum>BT_StaticText</_BlockTypeEnum>	
    		</_Region>
    		<_Region>
    			<_Name>regionStaticTextExtension</_Name>
    			<_Coordinates>
    				<_X1>238</_X1>
    				<_Y1>198</_Y1>
    				<_X2>538</_X2>
    				<_Y2>232</_Y2>
    			</_Coordinates>
    			<_BlockTypeEnum>BT_StaticText</_BlockTypeEnum>	
    		</_Region>
    	</_Regions>
    </_Document_Definition>
