       FlowDocument mcFlowDoc = new FlowDocument();
            Hyperlink hyp = new Hyperlink();
            hyp.Foreground = Brushes.Black;
            TextBlock txt = new TextBlock();
            txt.Foreground = Brushes.Black;
            txt.Text = "Friday,April 10";           
            Run rn = new Run("th");
            rn.BaselineAlignment = BaselineAlignment.Superscript;
            txt.Inlines.Add(rn);
            hyp.Inlines.Add(txt);            
            Paragraph para = new Paragraph();
            para.Inlines.Add(new Run("The following zip codes are facing a "));
            para.Inlines.Add(new Underline(new Run("Severe Weather Threat")));
            para.Inlines.Add(new Run(" on "));
            para.Inlines.Add(hyp); 
            mcFlowDoc.Blocks.Add(para);
            RichTextBox mcRTB = new RichTextBox();
            mcRTB.Width = 560;
            mcRTB.Height = 100;
            mcRTB.Document = mcFlowDoc;
