                            item1.Name = "InventoryTest3" ;
                            item1.FullyQualifiedName = "InventoryTest3";
                            item1.Description = "Description";
                            item1.Active = true;
                            item1.ActiveSpecified = true;
                            item1.Taxable = true;
                            item1.TaxableSpecified = true;
                            item1.UnitPrice = 10.00m;
                            item1.Type = ItemTypeEnum.Inventory;
                            item1.IncomeAccountRef = new ReferenceType() { Value="63" };
                            item1.PurchaseCost = 24.00m;
                            item1.PurchaseCostSpecified = true;
                            item1.ExpenseAccountRef = new ReferenceType() { Value = "64" };
                            item1.AssetAccountRef = new ReferenceType() { Value = "65" };
                            item1.TrackQtyOnHand = true;
                            item1.TrackQtyOnHandSpecified = true;
                            item1.QtyOnHand = 90;
                            item1.QtyOnHandSpecified = true;
                            item1.InvStartDate = DateTime.Now.Date;
                            item1.InvStartDateSpecified = true;
                            Item itemAdded = commonServiceQBO.Add<Item>(item1);
