    ...
    GlobalConfiguration.Configure(WebApiConfig.Register);
    ...
    public class WebApiConfig
	{
		public static void Register(HttpConfiguration config)
		{
            ...
			config.Filters.Add(new ModelStateValidationAttribute());
            ...
		}
	}
