    [Test]
    public void TestGetAllClientsDoesNotReturnDisabledUsers()
    {
        var dbReposMock = new Mock<IMyDbRepository>();
        dbReposMock.Setup(r=>r.GetAllClients()).Returns(
                          new []{ new Client { Name="AAA", IsDisabled=true },
                                  new Client { Name="BBB", IsDisabled=false } });
    
        var myTestingService = new MyService(dbReposMock.Object);//You pass here the autogenerated object which follows the described primitive behavior without requiring DB at all.
        var clientNames = myTestingService.GetClientNames();
        Assert.AreEqual(1, clientNames.Length);
        Assert.AreEqual("BBB", clientNames[0]);
    }
