    <NewDataSet>
      <Table1>
        <Column1>Name1</Column1>
        <Column2>Value1</Column2>
      </Table1>
      <Table1>
        <Column1>Name2</Column1>
        <Column2>Value2</Column2>
      </Table1>
      <Table1>
        <Column1>Name3</Column1>
        <Column2>Value3</Column2>
      </Table1>
      <Table1>
        <Column1>Name4</Column1>
        <Column2>Value4</Column2>
      </Table1>
    </NewDataSet>
