    var table = new DataTable();
    table.Columns.Add("id", typeof(int));
    table.Columns.Add("Country", typeof(string));
    table.Columns.Add("Year", typeof(int));
    table.Columns.Add("Population_millions", typeof(int));
    table.Rows.Add(1, "Europe", 2000, 4000);
    table.Rows.Add(2, "America", 2000, 7000);
    table.Rows.Add(3, "Africa", 2000, 1000);
    table.Rows.Add(4, "Africa", 2005, 2000);
    table.Rows.Add(5, "Europe", 2005, 9000);
    table.Rows.Add(6, "America", 2005, 6000);
    table.Rows.Add(7, "America", 2007, 3000);
    table.Rows.Add(8, "Europe", 2007, 1900);
    table.Rows.Add(9, "Africa", 2007, 1500);
    var chart = new ChartControl();
    chart.DataSource = table;
    chart.SeriesDataMember = "Country";
    chart.BindToData(ViewType.Line, table, "Country", "Year", new string[] { "Population_millions" });
    var diagram = (XYDiagram)chart.Diagram;
    diagram.AxisX.VisualRange.Auto = false;
    diagram.AxisX.VisualRange.AutoSideMargins = true;
    diagram.AxisX.VisualRange.MinValue = 2000;
    diagram.AxisX.VisualRange.MaxValue = 2010;
    diagram.AxisX.WholeRange.MinValue = 1990;
    diagram.AxisX.WholeRange.MaxValue = 2014;
    diagram.AxisX.NumericScaleOptions.ScaleMode = ScaleMode.Manual;
    diagram.AxisX.NumericScaleOptions.CustomMeasureUnit = 1;
                
    diagram.EnableAxisXScrolling = true;
    diagram.EnableAxisXZooming = true;
    chart.Dock = DockStyle.Fill;
    Controls.Add(chart);
