    SqlConnection con = new SqlConnection(@"Data Source=.\SQLEXPRESS;AttachDbFilename=" + Application.StartupPath + "\\Login.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True");
     con.Open();
     SqlCommand cmd = new SqlCommand();
     cmd.Connection = con;
     cmd.CommandType = CommandType.Text;
     cmd.CommandText = "SELECT * FROM INFORMATION_SCHEMA.TABLES";
     SqlDataAdapter dbAdapter = new SqlDataAdapter(cmd);
     DataTable dtRecords = new DataTable();
     dbAdapter.Fill(dtRecords);
     comboBox1.DataSource = dtRecords;
     comboBox1.DisplayMember = "TABLE_NAME";
     con.Close();
