    byte[] receivedBytes = new byte[2048];
    //IPHostEntry ipHost = Dns.Resolve("192.168.1.55");
    IPHostEntry ipHost = Dns.Resolve("127.0.0.1");
    IPAddress ipAddress = ipHost.AddressList[0];
    //IPEndPoint ipEndPoint = new IPEndPoint(ipAddress, 8000);
    IPEndPoint ipEndPoint = new IPEndPoint(ipAddress, 2112);
    Console.WriteLine("Starting: Creating Socket object");
    Socket sender = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
    sender.Connect(ipEndPoint);
    Console.WriteLine("Successfully connected to {0}", sender.RemoteEndPoint);
    Console.WriteLine("Enter Client Message :");
    string sendingMessage = Console.ReadLine();
    //string sendingMessage = "Hello World Socket Test";
    Console.WriteLine("Creating message:{0}", sendingMessage);
    byte[] forwardMessage = Encoding.Default.GetBytes(sendingMessage);
    sender.Send(forwardMessage);
    int totalBytesReceived = sender.Receive(receivedBytes);
    Console.WriteLine("Message provided from server: {0}", Encoding.ASCII.GetString(receivedBytes, 0, totalBytesReceived));
    sender.Shutdown(SocketShutdown.Both);
    sender.Close();
    Console.ReadLine();
