    var proxyFuncFactory = new InjectionFactory(CreateProxy);
    private static object CreateProxy(IUnityContainer container, Type interfaceType, string name)
    {
        var proxyGenerator = container.Resolve<Castle.DynamicProxy.ProxyGenerator>();
        return proxyGenerator.CreateInterfaceProxyWithoutTarget(interfaceType, container.Resolve<AutoGeneratedFactoryInterceptor>());
    }
