    public static void TestRNG()
    {
        const int OFFSET = 0;
        const int LIMIT = 200;
        const int RndCount = 50;
        const int FieldsPerLine = 10;
        int Rnd;
        for (int iMaster = 0; iMaster < RndCount; ++iMaster)
        {
            // create master RNG
            var rngMaster = new Random(iMaster + OFFSET);
            // obtain seed from master RNG
            var seed = rngMaster.Next();
            // create main RNG from seed
            var rngMain = new Random(seed);
            // print 3rd number generated by main RNG
            Console.WriteLine();
            for (int Loop = 0; Loop < FieldsPerLine; Loop++)
            {
                Rnd = rngMain.Next(LIMIT);
                Console.Write(Rnd.ToString().PadLeft(3) + " ");
            }
        }
    }
