    var list = new List<Tuple<string>>();
    list.Add(Tuple.Create("String 1"));
    list.Add(Tuple.Create("String 2"));
    list.Add(Tuple.Create("String 3"));
    var itemLabel = new XRLabel();
    itemLabel.DataBindings.Add(new XRBinding("Text", null, "Item1"));
    var parameter = new Parameter();
    parameter.Name = "UserText";
    parameter.Type = typeof(string);
    parameter.Value = "User text";
    parameter.Description = "Enter Text: ";
    parameter.Visible = true;
    var parameterLabel = new XRLabel();
    parameterLabel.DataBindings.Add(new XRBinding(parameter, "Text", ""));
    parameterLabel.TopF = 15;
    var detail = new DetailBand();
    detail.Controls.Add(itemLabel);
    detail.Controls.Add(parameterLabel);
    var report = new XtraReport();
    report.DataSource = list;
    report.Parameters.Add(parameter);
    report.Bands.Add(detail);
    var tool = new ReportPrintTool(report);
    tool.ShowRibbonPreview();
