    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Text;
    using System.Threading.Tasks;
    namespace ConsoleApplication1
    {
      class Program
      {
          static void Main(string[] args)
          {
            HttpClient client = new HttpClient();
                        
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("https://ebanking.bankofmaldives.com.mv/xe/").Result;
            
            
            if (response.IsSuccessStatusCode)
            {
                string JSON = response.Content.ReadAsStringAsync().Result;
                //Deserialize to strongly typed class i.e., RootObject
                RootObject obj = JsonConvert.DeserializeObject<RootObject>(JSON);
                //loop through the list and insert into database
                foreach (CurrencyList currencyItem in obj.CurrencyList)
                {
                Console.WriteLine(currencyItem.Key + "-" + currencyItem.Value.Code + "-" + currencyItem.Value.Description +
                       "-"+ currencyItem.Value.Buy + "-" + currencyItem.Value.Sell);
                    
                }
            }
        }
        **Note: Below classes are generated by utilising http://json2csharp.com/**
        **ofcourse these can be hand coded by looking at the Json response from the service**
        public class Value
        {
            public string Code { get; set; }
            public string Description { get; set; }
            public double Buy { get; set; }
            public double Sell { get; set; }
        }
        public class CurrencyList
        {
            public string Key { get; set; }
            public Value Value { get; set; }
        }
        public class RootObject
        {
            public List<CurrencyList> CurrencyList { get; set; }
        }
        
      }
    } 
