        [HttpPost]
        public virtual ActionResult Index(HttpPostedFileBase file)
        {
        .....
        .....
        byte[] m_Bytes = ReadToEnd (file.InputStream);
        ....
        ...
        }
