    public void RunTheSearch(string id)
    {
        ...
        cmd2.CommandType = CommandType.StoredProcedure;
        cmd2.CommandText = "sp_Search";
        cmd2.Parameters.Add("@param1", SqlDbType.NVarChar, 50).Value = id;
        ...
        ...
