    Series S1 = chart1.Series[0];
    ChartArea CA = chart1.ChartAreas[0];
    S1.ChartType = SeriesChartType.Point;
    S1.MarkerSize = 8;
    S1.Points.AddXY(1, 1);
    S1.Points.AddXY(2, 7);
    S1.Points.AddXY(3, 2);
    S1.Points.AddXY(4, 9);
    S1.Points.AddXY(5, 19);
    S1.Points.AddXY(6, 9);
    S1.ToolTip = "(#VALX{0.##} / #VALY{0.##})";
    S1.Color = Color.SeaGreen;
    CA.AxisX.Minimum = S1.Points.Select(x => x.XValue).Min();
    CA.AxisX.Maximum = S1.Points.Select(x => x.XValue).Max() + 1;
    CA.AxisY.Minimum = S1.Points.Select(x => x.YValues[0]).Min();
    CA.AxisY.Maximum = S1.Points.Select(x => x.YValues[0]).Max() + 1;
    CA.AxisX.Interval = 1;
    CA.AxisY.Interval = 1;
    ca_ = chart1.ChartAreas[0];
    s_ = chart1.Series[0];
