    ...
    var currentDeviceType = DeviceTypes.Switcher;
    ...
    var device = DeviceFactory.GetDevice(currentDeviceType);
    if (device.Connect("1.2.3.4", "user", "pass")) {
      if (device.CanPlay)
        device.Play();
      ...
    }
    ...
