    var body = @"Here is the chart: <br/> <img src=""$CONTENTID1$""/>";
    var CONTENTID1 = Guid.NewGuid().ToString().Replace("-", "");
    body = body.Replace("$CONTENTID1$", "cid:" + CONTENTID1);
    var htmlView = AlternateView.CreateAlternateViewFromString(body, null, "text/html");
    var stream = new MemoryStream();
    this.chart1.SaveImage(stream, System.Drawing.Imaging.ImageFormat.Png);
    stream.Position = 0;
    LinkedResource imagelink1 = new LinkedResource(stream, "image/png");
    imagelink1.ContentId = CONTENTID1;
    imagelink1.TransferEncoding = System.Net.Mime.TransferEncoding.Base64;
    htmlView.LinkedResources.Add(imagelink1);
    MailMessage mail = new MailMessage();
    mail.From = new MailAddress("someone@outlook.com");
    mail.To.Add(new MailAddress("someone@example.com"));
    mail.Subject = "Subject";
    mail.AlternateViews.Add(htmlView);
    SmtpClient client = new SmtpClient();
    client.Host = "smtp-mail.outlook.com";
    client.Port = 587;
    client.EnableSsl = true;
    client.DeliveryMethod = SmtpDeliveryMethod.Network;
    client.UseDefaultCredentials = false;
    client.Credentials = new NetworkCredential("someone@outlook.com", "password");
    client.Send(mail);
