        public PXAction<FuncLocFilter> CreateFuncLoc;
        [PXButton]
        [PXUIField(DisplayName = "Create Functional Location")]
        protected virtual void createFuncLoc()
        {
            FuncLocFilter row = Filter.Current;
            // 1. Create an instance of the BLC (graph)
            FunLocEntry graph = PXGraph.CreateInstance<FunLocEntry>();
            // 2. Create an instance of the BSMTFuncLoc DAC, set key field values (besides the ones whose values are generated by the system), 
            //    and insert the record into the cache
            BSMTFuncLoc FnLc = new BSMTFuncLoc();
            FnLc.FuncLocCD = row.FuncLocCD;
            FnLc = graph.FunLocations.Insert(FnLc);
            // 3. Set non-key field values and update the record in the cache
            FnLc.StructureID = row.StructureID;
            FnLc.HierLevels = row.HierLevels;
            FnLc.EditMask = row.EditMask;
            FnLc = graph.FunLocations.Update(FnLc);
            // 4. Redirect
            if (graph.FunLocations.Current != null)
            {
                throw new PXRedirectRequiredException(graph, true, "Functional Location");
            }
