    <#=codeStringGenerator.EntityClassOpening(entity).Replace(tablePerfix,"")#>
    // ...
    public <#=code.Escape(entity).Replace(tablePerfix,"")#>()
    // ...
    this.<#=code.Escape(navigationProperty).Replace(tablePerfix,"")#> = new HashSet<<#=typeMapper.GetTypeName(navigationProperty.ToEndMember.GetEntityType()).Replace(tablePerfix,"")#>>();
