    var hierarchy = (Hierarchy)log4net.LogManager.GetRepository();
            
    var patternLayout = new PatternLayout();
    patternLayout.ConversionPattern = "%date [%thread] %-5level %logger - %message%newline";
    patternLayout.ActivateOptions();
    var console = new ConsoleAppender();
    console.Layout = patternLayout;
    var roller = new RollingFileAppender();
    roller.AppendToFile = true;
    roller.File = Path.Combine(Logger.LogPath, "log.txt");
    roller.Layout = patternLayout;
    roller.MaxSizeRollBackups = 5;
    roller.MaximumFileSize = "100MB";
    roller.RollingStyle = RollingFileAppender.RollingMode.Size;
    roller.StaticLogFileName = true;
    roller.ActivateOptions();
    hierarchy.Root.AddAppender(console);
    hierarchy.Root.AddAppender(roller);
    MemoryAppender memory = new MemoryAppender();
    memory.ActivateOptions();
    hierarchy.Root.AddAppender(memory);
    hierarchy.Root.Level = Level.Debug;
    hierarchy.Configured = true;
