    private void UpdateExistingBindingRedirects(XElement runtimeNode, IDictionary<AssemblyName, string> redirects)
    {    
        ...
        var publicKeyToken = assemblyIdentity.Attribute("publicKeyToken");
        var publicKeyTokenValue = publicKeyToken.Value;
        ...
