      ...
         cmd.Parameters.Add("@spisanie_id", SqlDbType.BigInt).Value = BigInteger.Parse(IDtextBox.Text);
         cmd.Parameters.Add("@prichanie_spis", SqlDbType.NVarChar).Value = PrichinatextBox.Text;
         cmd.Parameters.Add("@data_spis", SqlDbType.Date).Value = DateTime.Parse(dateEdit.Text);
        ...
