    public void InsertOrUpdateTweak(string recipename, string batchID, DateTime dtpTweak, int tempTweak, double specificGravityTweak, string tweakBox, int r_ID, string arrr)
            {
                 ...
                 string eventItems = GetEvents();
                 ...
                 log.cbEventItems = eventItems;
                 ...
            }
