            // loop through the columns to create parameters...
            for (int i = 1; i < dt.Columns.Count; i++)
            {
                // get the name of the column...
                string factorName = dt.Columns[i].ColumnName;
                // define the new column name...
                string colName = string.Format("Factor_Name_{0}", i);
                // change the column name now we have stored the real name...
                dt.Columns[i].ColumnName = string.Format("Factor{0}", i);
                // generate the parameter...
                var rparam = new ReportParameter(colName, factorName);
                // add it to the parameter set for the control...
                this.reportViewer1.LocalReport.SetParameters(new[] { rparam });
            }
