    using System.Globalization;
    ...
    ...
    ...
    public string CapitalizeEveryWordInMyString(string input)
    {
        return CultureInfo.CurrentCulture.TextInfo.ToTitleCase(input);
    }
