    MailMessage mail = new MailMessage(sender, receiver);
    using(SmtpClient client = new SmtpClient())
    {
        client.Host ...
        client.Port ...
    
        mail.subject ...
        mail.body ...
    
        await client.SendMailAsync(mail);
    }
