    Signer signer = new Signer();
    Guid g = Guid.NewGuid();
    // add radio buttons
    Radio rYes = new Radio();
    rYes.AnchorString = @"\cb_yes\";
    rYes.AnchorXOffset = "0";
    rYes.AnchorYOffset = "-15";
    rYes.TabId = g.ToString(); 
    rYes.Value = "X";
    rYes.Selected = "true";
    Radio rNo = new Radio();
    rNo.AnchorString = @"\cb_no\";
    rNo.AnchorXOffset = "0";
    rNo.AnchorYOffset = "-15";
    rNo.TabId = g.ToString(); 
    List<Radio> radioVals = new List<Radio>();
    radioVals.Add(rYes);
    radioVals.Add(rNo);
    RadioGroup rg = new RadioGroup();
    rg.GroupName = "radioGroup";
    rg.Radios = radioVals;
    List<RadioGroup> radioGroupTabs = new List<RadioGroup>();
    signer.Tabs.RadioGroupTabs = radioGroupTabs;
    signer.Tabs.RadioGroupTabs.Add(rg);
