            public void ConfigureServices(IServiceCollection services)
            {
                ...
                services.AddControllersWithViews().AddJsonOptions(opts => opts.JsonSerializerOptions.PropertyNamingPolicy = null);
                ...
            }
