    [MetadataType(typeof(NotAutoGeneratedClassMD))]
    public partial class AutoGeneratedClass
    {
    }
    public class NotAutoGeneratedClassMD
    {
        [DisplayName("This is some data")]
        public string SomeData { get; set; }
    }
