    <UserControl DataContext="{Binding RelativeSource={RelativeSource Self}}"> ...
    ....
        <TextBox Name="textBox1" IsEnabled="{Binding AreTextBoxesEnabled}" ... />
        <TextBox Name="textBox2" IsEnabled="{Binding AreTextBoxesEnabled}" ... />
        <TextBox Name="textBox3" IsEnabled="{Binding AreTextBoxesEnabled}" ... />
    ...
