    public async Task AttachTypeToMeetingTimeAsync(int meetingTimeId,int meetingTypeId)
        {
            await Task.Run(() =>
            {
                //synchronous method generated by EF.
                //VS warning here
                AttachTypeToMeetingTime(meetingTimeId, meetingTypeId);
            });
        }
