    public class Fish : Animal, ISplashable
    {
        // ...
        public bool CanSplash { get; set; }  // this also implements CanSplash { get; }
        // ...
    }
    public class Elephant : Animal, ISplashable
    {
        // ...
        public bool CanSplash { get { return true; } }
        // ...
    }
