      var allcourse = db.Enrollments
            .Where(e => e.UserID == User.Identity.GetUserId())
            .Select(x => new CourseViewModel { 
            
        CourseID = e.Course_page.CourseID,
        ...
        ...
        Course_section = e.Course_page.course_sections.OrderBy(i => i.Order).FirstOrDefault
        ...
        ...
        ...
            });
