                string header = "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
                   "<!--This file is generated by the program.-->" +
                   "<Folders></Folders>";
                XDocument doc = XDocument.Parse(header);
                XElement folders = doc.Descendants("Folders").FirstOrDefault();
                folders.Add( new[] {
                   new XElement("Amount", amount),
                   new XElement("Date", date),
                   new XElement("Time", time),
                   new XElement("folderPath", folderPath)
                });
