      namespace AnotherNamespace {
        ...
        public class AnotherClass {
          ...
          public enum MyEnum {
            One, 
            Two,
            Three 
         }
        }
        ...
      }
    
      ...
    
      namespace MyNamespace { 
        ...
        AnotherNamespace.AnotherClass.MyEnum v = ...
