    var mongoConnection = //...
    var efConnection = //...
    var otherConnection = //...
    services.AddTransient<IMyFactory>(
                 s => new MyFactoryImpl(
                     mongoConnection, efConnection, otherConnection, 
                     s.GetService<ISomeDependency1>(), s.GetService<ISomeDependency2>())));
