        public void ConfigureServices(IServiceCollection services)
        {
         ...
         services.Configure<ApplicationSettings>(Configuration.GetSection("ApplicationSettings"));
        ...
        }
