            //Get MAD sector
            var setor = mifareCard.GetSector(0);
            //Get Trail data
            await setor.GetData(3);
            //Update chaves. Acess bits are generated by Mirafe API
            await setor.FlushTrailer(
                Extensions.ByteArrayToString(new byte[] { 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5 }),
                Extensions.ByteArrayToString(new byte[] { 0xD3, 0xF7, 0xD3, 0xF7, 0xD3, 0xF7 }
            ));
            //Set others sectors keys for NDEF
            for (var sector = 1; sector < 16; sector++) {
                try {
                    setor = mifareCard.GetSector(sector);
                    await setor.GetData(3);
                    await setor.FlushTrailer(
                        Extensions.ByteArrayToString(new byte[] { 0xD3, 0xF7, 0xD3, 0xF7, 0xD3, 0xF7 }),
                        Extensions.ByteArrayToString(new byte[] { 0xD3, 0xF7, 0xD3, 0xF7, 0xD3, 0xF7 }
                    ));
                } catch (Exception ex) {
                    Debug.Write(ex.Message + "\n");
                }
            }
