    using System.Collections.Generic;
    var queue = new Queue<string>();
    ...
    queue.Enqueue("CMD1");
    queue.Enqueue("CMD2");
    ...
    var nextCommand = queue.Peek(); // will NOT remove the peek item
    ...
    var nextCommandRemoved = queue.Dequeue();
    ...
