            for (int i = 0; i < lights.GetLength(1); i++)
            {
                for (int j = 0; j < lights.GetLength(0); j++)
                {
                    lights[i, j] = new Button();
                    lights[i, j].Size = new System.Drawing.Size(50, 50);
                    lights[i, j].Name = "button" + i.ToString() + j.ToString(); // set name like this
                    lights[i, j].Click += autoGeneratedEventName_Click; //after "+=" hit tab twice visual studio will create event auto;
                    lights[i,j].Location = new Point(40 + (j*70), 20 + (i * 70));
                    lights[i, j].BackColor = Color.Yellow;
                    this.panel1.Controls.Add(lights[i, j]);
                    //MessageBox.Show("I:" + Convert.ToString(i) + "J:" + Convert.ToString(j));
                }
            } 
