            Sales sales = new Sales();
            sales.ChannelName = new Channel { Code = "B" };
            sales.Type = "C";
            list.Add(sales);
            sales = new Sales();
            sales.ChannelName = new Channel { Code = "AB" };
            sales.Type = "C";
            list.Add(sales);
            sales = new Sales();
            sales.ChannelName = new Channel { Code = "A" };
            sales.Type = "A";
            list.Add(sales);
            sales = new Sales();
            sales.ChannelName = new Channel { Code = "C" };
            sales.Type = "B";
            list.Add(sales);
            sales = new Sales();
            sales.ChannelName = new Channel { Code = "D" };
            sales.Type = "D";
            list.Add(sales);
