    DotNetGoat.dll
    DotNetGoat.dll.config
    DotNetGoat.pdb
    EnvDTE.dll
    EnvDTE.xml
    EnvDTE80.dll
    EnvDTE80.xml
    log4net.dll
    log4net.xml
    Microsoft.VisualStudio.OLE.Interop.dll
    Microsoft.VisualStudio.OLE.Interop.xml
    Microsoft.VisualStudio.Shell.Interop.8.0.dll
    Microsoft.VisualStudio.Shell.Interop.8.0.xml
    Microsoft.VisualStudio.Shell.Interop.dll
    Microsoft.VisualStudio.Shell.Interop.xml
    Microsoft.VisualStudio.TextManager.Interop.8.0.dll
    Microsoft.VisualStudio.TextManager.Interop.8.0.xml
    Microsoft.VisualStudio.TextManager.Interop.dll
    Microsoft.VisualStudio.TextManager.Interop.xml
    Microsoft.VisualStudio.VSHelp.dll
    mysql.data.dll
    mysql.data.entity.dll
    mysql.visualstudio.dll
    mysql.web.dll
    stdole.dll
    System.Data.SQLite.dll
    System.Data.SQLite.xml
