    //generated by http://json2csharp.com/
    public class ResponseContainer
    {
        public List<object> Result { get; set; }
        public bool IsLastPage { get; set; }
        public int NextSkip { get; set; }
        public int NextTake { get; set; }
        public int PageCount { get; set; }
        public int TotalCount { get; set; }
        public string QueryResultHash { get; set; }
    }
