    <Platforms>
        <Platform>
            <Name>Standard</Name>
            <Devices>
                <Device>Namespace.of.your.Device.CaptureDevice</Device>
                <Device>Namespace.of.another.Device.AnotherDevice</Device>
            <Devices>
        </Platform>
    </Platforms>
