    var parameter = Expression.Parameter(typeof(object));
    var entity = Expression.Convert(parameter, theEntity.GetType());
    ...
    Expression.Property(entity, theEntity.GetType().GetProperty("Id").Name),
    ...
