    namespace YourNamespace {
        public class MyDataGrid : DataGrid
        {
            protected override void OnAutoGeneratedColumns(EventArgs e)
            {
                DataGrid dg = sender as DataGrid;
                if (dg == null) return;
                dg.Columns.ToList().Select((col, indx) => new {Col = col, Indx = indx}).ToList().ForEach(obj => obj.Col.CanUserSort = obj.Indx == 0);
                base.OnAutoGeneratedColumns(e);
            }
        }
    }
