        YourAutoGeneratedContext ctx = new YourAutoGeneratedContext();
        level = 0;
        foreach (Departments currentHier in ctx.GetDepartmentHierarchy(10))
        {
        	Console.WriteLine(currentHier.ID.ToString() + ", " + currentHier.DepartmentID.ToString() + ", " + currentHier.Name + ", " + (level++).ToString());
        }
