        using System.Collections.Generic;
        using System.Linq;
        
        namespace CustomEF.EFStuff
        {
        
        
            public partial class YourAutoGeneratedContext
            {
                public List<Departments> GetDepartmentHierarchy(int departmentId)
                {
                    Departments tmp = this.Departments.FirstOrDefault(d => d.ID == departmentId);
                    if (tmp == null)
                    {
                        throw new System.Data.Entity.Core.ObjectNotFoundException("There is no department with ID = " + departmentId.ToString());
                    }
                    List<Departments> retVal = new List<Departments>();
                    retVal.Add(tmp);
        
                    while (tmp.DepartmentID != null)
                    {
                        tmp = this.Departments.First(d => d.ID == tmp.DepartmentID);
                        retVal.Add(tmp);
                    }
                    
                    return retVal;
                }
            }
        }
