	public static class PclRestService
	{
		public static T For<T>(string hostUrl)
		{
			var className = "AutoGenerated" + typeof(T).Name;
			var typeName = typeof(T).Namespace + "." + typeof(T).Name.Replace(typeof(T).Name, className);
			var assembly = System.Reflection.Assembly.GetExecutingAssembly();
			var generatedType = assembly.GetType(typeName);
			var requestBuilder = RequestBuilder.ForType<T>();			
			var client = new HttpClient(new HttpClientHandler()) { BaseAddress = new Uri(hostUrl) };
			return (T)Activator.CreateInstance(generatedType, client, requestBuilder);
		}
	}
