    SqlCommand cmd = new SqlCommand();
    cmd.Connection = getcon();
    cmd.CommandType = CommandType.Text;
    cmd.CommandText = String.Format("CREATE TABLE [{0}] (VENDOR varchar(1000), ADDRESS varchar(1000), CONTROL_NO varchar(20), DATE date, TERMS varchar(20), QTY int, ITD varchar(1000), UP int, TP int, ALTOT int, REQUEST_BY varchar(500)) ", BELPur.Title);
    cmd.ExecuteNonQuery();
    SqlCommand cmd2 = new SqlCommand();
    cmd2.Connection = getcon();
    cmd2.CommandType = CommandType.Text;
    cmd2.CommandText = String.Format("INSERT INTO [{0}] VALUES (@Vendor,@Address,@CtrlNo,@Date,@Terms,@Qty1,@ITD1,@UP1,@TP1,@ATT,@REQBY)", BELPur.Title);
    cmd2.Parameters.AddWithValue("@Vendor", BELPur.Vendor);
    cmd2.Parameters.AddWithValue("@Address", BELPur.Address);
    cmd2.Parameters.AddWithValue("@CtrlNo", BELPur.CtrlNo);
    cmd2.Parameters.AddWithValue("@Date", BELPur.Date);
    cmd2.Parameters.AddWithValue("@Terms", BELPur.Terms);
    cmd2.Parameters.AddWithValue("@Qty1", BELPur.Qty1);
    cmd2.Parameters.AddWithValue("@ITD1", BELPur.ItD1);
    cmd2.Parameters.AddWithValue("@UP1", BELPur.UP1);
    cmd2.Parameters.AddWithValue("@TP1", BELPur.TP1);
    cmd2.Parameters.AddWithValue("@ATT", BELPur.AllTot);
    cmd2.Parameters.AddWithValue("@REQBY", BELPur.ReqBy);
    cmd2.ExecuteNonQuery();
