    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Swashbuckle.AspNetCore.Annotations;
    namespace MyExample.Controllers
    {
    /// <summary>
    /// Example of a .NET Core controller based on the controller name
    /// api/[controller] on ValuesController becomes api/values
    /// endpoint: "/Values" from [controller] and name of controller , which is "ValuesController"
    /// </summary>
    [Route("[controller]")]
    [ApiController]
    [SwaggerTag("This is an example controller generated by ASP.NET Core 2.x")]
    public class ValuesController : ControllerBase
    {
    ...
    }
