    Public Class DavisJsonData
    {
         Public Davis_Current_Observation davis_current_observation { set; get; }
    }
    Public class Davis_Current_Observation
    {
    public string davis_current_observation { set; get; }
        public string station_name { set; get; }
        public string observation_age { set; get; }
        public string dewpoint_day_high_time { set; get; }
        public string dewpoint_day_low_f { set; get; }
        public string dewpoint_day_low_time { set; get; }
        public string dewpoint_month_high_f { set; get; }
        public string dewpoint_month_low_f { set; get; }
        public string dewpoint_year_high_f { set; get; }
        public string dewpoint_year_low_f { set; get; }
        public string et_day { set; get; }
        public string et_month { set; get; }
        public string et_year { set; get; }
        public string heat_index_day_high_f { set; get; }
        public string heat_index_day_high_time { set; get; }
        public string heat_index_month_high_f { set; get; }
        public string heat_index_year_high_f { set; get; }
        public string pressure_day_high_in { set; get; }
        public string pressure_day_high_time { set; get; }
        public string pressure_day_low_in { set; get; }
        public string pressure_day_low_time { set; get; }
        public string pressure_month_high_in { set; get; }
        public string pressure_month_low_in { set; get; }
        public string pressure_tendency_string { set; get; }
        public string pressure_year_high_in { set; get; }
        public string pressure_year_low_in { set; get; }
        public string rain_day_in { set; get; }
        public string rain_month_in { set; get; }
        public string rain_rate_day_high_in_per_hr { set; get; }
        public string rain_rate_hour_high_in_per_hr { set; get; }
        public string rain_rate_in_per_hr { set; get; }
        public string rain_rate_month_high_in_per_hr { set; get; }
        public string rain_rate_year_high_in_per_hr { set; get; }
        public string rain_storm_in { set; get; }
        public string rain_year_in { set; get; }
        public string relative_humidity_day_high { set; get; }
        public string relative_humidity_day_high_time { set; get; }
        public string relative_humidity_day_low { set; get; }
        public string relative_humidity_day_low_time { set; get; }
        public string relative_humidity_month_high { set; get; }
        public string relative_humidity_month_low { set; get; }
        public string relative_humidity_year_high { set; get; }
        public string relative_humidity_year_low { set; get; }
        public string relative_humidity_in { set; get; }
        public string relative_humidity_in_day_high { set; get; }
        public string relative_humidity_in_day_high_time { set; get; }
        public string relative_humidity_in_day_low { set; get; }
        public string relative_humidity_in_day_low_time { set; get; }
        public string relative_humidity_in_month_high { set; get; }
        public string relative_humidity_in_month_low { set; get; }
        public string relative_humidity_in_year_high { set; get; }
        public string relative_humidity_in_year_low { set; get; }
        public string relative_humidity_1 { set; get; }
        public string relative_humidity_1_day_high { set; get; }
        public string relative_humidity_1_day_high_time { set; get; }
        public string relative_humidity_1_day_low { set; get; }
        public string relative_humidity_1_day_low_time { set; get; }
        public string relative_humidity_1_month_high { set; get; }
        public string relative_humidity_1_month_low { set; get; }
        public string relative_humidity_1_year_high { set; get; }
        public string relative_humidity_1_year_low { set; get; }
        public string solar_radiation { set; get; }
        public string solar_radiation_day_high { set; get; }
        public string solar_radiation_day_high_time { set; get; }
        public string solar_radiation_month_high { set; get; }
        public string solar_radiation_year_high { set; get; }
        public string sunrise { set; get; }
        public string sunset { set; get; }
        public string temp_day_high_f { set; get; }
        public string temp_day_high_time { set; get; }
        public string temp_day_low_f { set; get; }
        public string temp_day_low_time { set; get; }
        public string temp_month_high_f { set; get; }
        public string temp_month_low_f { set; get; }
        public string temp_year_high_f { set; get; }
        public string temp_year_low_f { set; get; }
        public string temp_extra_1 { set; get; }
        public string temp_extra_1_day_high { set; get; }
        public string temp_extra_1_day_high_time { set; get; }
        public string temp_extra_1_day_low { set; get; }
        public string temp_extra_1_day_low_time { set; get; }
        public string temp_extra_1_month_high { set; get; }
        public string temp_extra_1_month_low { set; get; }
        public string temp_extra_1_year_high { set; get; }
        public string temp_extra_1_year_low { set; get; }
        public string temp_in_day_high_f { set; get; }
        public string temp_in_day_high_time { set; get; }
        public string temp_in_day_low_f { set; get; }
        public string temp_in_day_low_time { set; get; }
        public string temp_in_f { set; get; }
        public string temp_in_month_high_f { set; get; }
        public string temp_in_month_low_f { set; get; }
        public string temp_in_year_high_f { set; get; }
        public string temp_in_year_low_f { set; get; }
        public string uv_index { set; get; }
        public string uv_index_day_high { set; get; }
        public string uv_index_day_high_time { set; get; }
        public string uv_index_month_high { set; get; }
        public string uv_index_year_high { set; get; }
        public string wind_day_high_mph { set; get; }
        public string wind_day_high_time { set; get; }
        public string wind_month_high_mph { set; get; }
        public string wind_ten_min_avg_mph { set; get; }
        public string wind_ten_min_gust_mph { set; get; }
        public string wind_year_high_mph { set; get; }
        public string windchill_day_low_f { set; get; }
        public string windchill_day_low_time { set; get; }
        public string windchill_month_low_f { set; get; }
        public string windchill_year_low_f { set; get; }
    }
