	System.Web.UI.HtmlControls.HtmlGenericControl master_login_trigger = new System.Web.UI.HtmlControls.HtmlGenericControl("A");
	master_login_trigger.ID = "master_login-trigger";
	master_login_trigger.Attributes.Add("href", "#");
	master_login_trigger.InnerHtml = "Log in <span>▼</span>";
	master_login.Controls.Add(master_login_trigger);
	System.Web.UI.HtmlControls.HtmlGenericControl master_login_content = new System.Web.UI.HtmlControls.HtmlGenericControl("DIV");
	master_login_content.ID = "master_login-content";
	System.Web.UI.HtmlControls.HtmlGenericControl master_inputs = new System.Web.UI.HtmlControls.HtmlGenericControl("FIELDSET");
	master_inputs.ID = "master_inputs";
	System.Web.UI.HtmlControls.HtmlGenericControl master_input_username = new System.Web.UI.HtmlControls.HtmlGenericControl("INPUT");
	master_input_username.ID = "master_input_username";
	master_input_username.Attributes.Add("type", "text");
	master_input_username.Attributes.Add("name", "username");
	master_input_username.Attributes.Add("placeholder", "Username");
	master_input_username.Attributes.Add("value", "text");
	master_input_username.Attributes.Add("required", "required");
	master_inputs.Controls.Add(master_input_username);
	System.Web.UI.HtmlControls.HtmlGenericControl master_input_password = new System.Web.UI.HtmlControls.HtmlGenericControl("INPUT");
	master_input_password.ID = "master_input_password";
	master_input_password.Attributes.Add("type", "password");
	master_input_password.Attributes.Add("name", "username");
	master_input_password.Attributes.Add("placeholder", "Enter your Password");
	master_inputs.Controls.Add(master_input_password);
	master_login_content.Controls.Add(master_inputs);
	System.Web.UI.HtmlControls.HtmlGenericControl master_actions = new System.Web.UI.HtmlControls.HtmlGenericControl("FIELDSET");
	master_actions.ID = "master_actions";
	System.Web.UI.HtmlControls.HtmlGenericControl master_sub_login = new System.Web.UI.HtmlControls.HtmlGenericControl("INPUT");
	master_sub_login.ID = "master_sub_login";
	master_sub_login.Attributes.Add("type", "submit");
	master_sub_login.Attributes.Add("value", "Log in");
	master_actions.Controls.Add(master_sub_login);
	System.Web.UI.HtmlControls.HtmlGenericControl master_staylogin_label = new System.Web.UI.HtmlControls.HtmlGenericControl("LABEL");
	master_staylogin_label.ID = "master_staylogin_label";
	master_staylogin_label.InnerText = "Keep me signed in";
	System.Web.UI.HtmlControls.HtmlGenericControl master_staylogin = new System.Web.UI.HtmlControls.HtmlGenericControl("INPUT");
	master_staylogin.ID = "master_staylogin";
	master_sub_login.Attributes.Add("type", "checkbox");
	master_sub_login.Attributes.Add("checked", "checked");
	master_staylogin_label.Controls.Add(master_sub_login);
	master_actions.Controls.Add(master_staylogin_label);
	master_login_content.Controls.Add(master_actions);
	master_login.Controls.Add(master_login_content);
	master_navigation_hori.Controls.Add(master_login);
