    &lt;Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"&gt;
      &lt;Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" /&gt;
      &lt;PropertyGroup&gt;
        &lt;MinimumVisualStudioVersion&gt;14.0&lt;/MinimumVisualStudioVersion&gt;
        &lt;Configuration Condition=" '$(Configuration)' == '' "&gt;Debug&lt;/Configuration&gt;
        &lt;Platform Condition=" '$(Platform)' == '' "&gt;AnyCPU&lt;/Platform&gt;
        &lt;ProjectGuid&gt;{66c3d80b-6265-468a-82e1-b76317f9a9a5}&lt;/ProjectGuid&gt;
        &lt;OutputType&gt;Library&lt;/OutputType&gt;
        &lt;RootNamespace&gt;PCLTest&lt;/RootNamespace&gt;
        &lt;AssemblyName&gt;PCLTest&lt;/AssemblyName&gt;
        &lt;DefaultLanguage&gt;en-US&lt;/DefaultLanguage&gt;
        &lt;FileAlignment&gt;512&lt;/FileAlignment&gt;
        &lt;ProjectTypeGuids&gt;{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&lt;/ProjectTypeGuids&gt;
        &lt;TargetFrameworkProfile&gt;&lt;/TargetFrameworkProfile&gt;
        &lt;TargetFrameworkVersion&gt;v5.0&lt;/TargetFrameworkVersion&gt;
      &lt;/PropertyGroup&gt;
      &lt;PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' "&gt;
        &lt;DebugSymbols&gt;true&lt;/DebugSymbols&gt;
        &lt;DebugType&gt;full&lt;/DebugType&gt;
        &lt;Optimize&gt;false&lt;/Optimize&gt;
        &lt;OutputPath&gt;bin\Debug\&lt;/OutputPath&gt;
        &lt;DefineConstants&gt;DEBUG;TRACE&lt;/DefineConstants&gt;
        &lt;ErrorReport&gt;prompt&lt;/ErrorReport&gt;
        &lt;WarningLevel&gt;4&lt;/WarningLevel&gt;
      &lt;/PropertyGroup&gt;
      &lt;PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' "&gt;
        &lt;DebugType&gt;pdbonly&lt;/DebugType&gt;
        &lt;Optimize&gt;true&lt;/Optimize&gt;
        &lt;OutputPath&gt;bin\Release\&lt;/OutputPath&gt;
        &lt;DefineConstants&gt;TRACE&lt;/DefineConstants&gt;
        &lt;ErrorReport&gt;prompt&lt;/ErrorReport&gt;
        &lt;WarningLevel&gt;4&lt;/WarningLevel&gt;
      &lt;/PropertyGroup&gt;
      &lt;ItemGroup&gt;
        &lt;None Include="project.json" /&gt;
        &lt;!-- A reference to the entire .NET Framework is automatically included --&gt;
      &lt;/ItemGroup&gt;
      &lt;ItemGroup&gt;
        &lt;Compile Include="Class1.cs" /&gt;
        &lt;Compile Include="Properties\AssemblyInfo.cs" /&gt;
      &lt;/ItemGroup&gt;
      &lt;Import Project="$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets" /&gt;
    &lt;/Project&gt;
