            ConditionExpression condition3 = new ConditionExpression();
            ...
            LinkEntity link3 = new LinkEntity();
            ...
            link3.LinkCriteria.Conditions.Add(condition3);
            ConditionExpression condition2 = new ConditionExpression();
            ...
            LinkEntity link2 = new LinkEntity();
            ...
            link2.LinkCriteria.Conditions.Add(condition2);
            LinkEntity link1 = new LinkEntity();
            ...
            link1.LinkEntities.Add(link2);
            link1.LinkEntities.Add(link3);
            QueryExpression query = new QueryExpression("");
            ...
            query.LinkEntities.Add(link1);
            DataCollection<Entity> entities = service.RetrieveMultiple(query).Entities;
