    public abstract class TablePage : Page {
         protected void tableInit(HtmlGenericControl p_head, HtmlGenericControl p_body, delOnGetRecent p_delOnGetRecent) {
          ...
          _button.ServerClick += actionEventHandler;
          ...
          }
          ...
       protected abstract void actionEventHandler(object sender, EventArgs e);
    }
    
    public class _Default : TablePage { ... 
    protected override void actionEventHander(object sender, EventArgs e) {}
    ...
    }
