    public class TransferViewModel
    {
        ......................
        ......................
        public int SelectedDepartment { get; set; }
        public int SelectedSite { get; set; }
        .....................
        .....................
    }
