        HDNHtml hdn = new HDNHtml();
        Random r = new Random();
        HDNData hdnData = new HDNData();
        hdnData.Data = r.Next().ToString();
        hdnData.HexColor = "#FFCCFF";
        hdn.Add(0,hdnData);
        hdnData = new HDNData();
        hdnData.Data = r.Next().ToString();
        hdnData.Hyperlink = "#GTA";
        hdn.Add(0, hdnData);
        hdnData = new HDNData();
        hdnData.Data = r.Next().ToString();
        hdnData.Hyperlink = "#GTA";
        hdn.Add(0, hdnData);
        hdnData = new HDNData();
        hdnData.Data = r.Next().ToString();
        hdnData.Hyperlink = "#GTA";
        hdn.Add(1, hdnData);
        hdnData = new HDNData();
        hdnData.Data = r.Next().ToString();
        hdnData.Hyperlink = "#GTA";
        hdn.Add(1, hdnData);
        string data = hdn.ToString();
        txtWarnings.Text = data;
        Clipboard.SetText(data);
