    public class Addin : Outlook.Tools.COMAddin // this was auto-generated by the NetOffice Developer Toolbox
    {
        FolderEvents m_folderevents = new FolderEvents(); // 'FolderEvents' is my class
    
        // additional auto-generated code removed
    
        private void Addin_OnStartupComplete(ref Array custom)
        {
            m_folderevents.InitFolders(this.Application);
        }
    }
