     //I added this part (XmlWriterSettings):
     XmlWriterSettings mySettings = new XmlWriterSettings();
     mySettings.Indent = true;
     mySettings.IndentChars = ("    ");
     mySettings.CloseOutput = true;
     mySettings.OmitXmlDeclaration = true;
    //Added the settings you intialize and set on your XmlWriter:
     XmlWriter writer = XmlWriter.Create(@"C:\Users\Alek\Dropbox\D\Debug\product.xml", mySettings);
     writer.WriteStartDocument();
     writer.WriteComment("This file is generated by the program.");
     writer.WriteStartElement("root");
     writer.WriteStartElement("OFBM");
     writer.WriteAttributeString("time", "9:15");
     writer.WriteAttributeString("date", "22.06.2016");
     writer.WriteElementString("folder", @"file:///C:/Program Files (x86)/Cisco/Cisco AnyConnect Secure Mobility Client");
     writer.WriteElementString("folder", @"file:///C:/Arduino223");
     writer.WriteEndElement();
     //writer.WriteEndElement();
     //writer.WriteEndDocument();
      writer.Flush();
      writer.Close();
