    Pivot pivot = new Pivot();
            PivotItem pivotItem = new PivotItem();
            pivot.Items.Add(pivotItem);
            ScrollViewer scrollViewer = new ScrollViewer();
            StackPanel stackContent = new StackPanel();
            scrollViewer.Content = stackContent;
            Window.Current.Activate();
            var bounds = ApplicationView.GetForCurrentView().VisibleBounds;
            scrollViewer.Height = bounds.Height;
            pivotItem.Content = scrollViewer;
            stackContent.Children.Add(new Button() { Content = "button 1" });
            stackContent.Children.Add(new Button() { Content = "button 2" });
            stackContent.Children.Add(new Button() { Content = "button 3" });
            stackContent.Children.Add(new Button() { Content = "button 4" });
            stackContent.Children.Add(new Button() { Content = "button 5" });
            stackContent.Children.Add(new Button() { Content = "button 6" });
            stackContent.Children.Add(new Button() { Content = "button 7" });
            stackContent.Children.Add(new Button() { Content = "button 8" });
            stackContent.Children.Add(new Button() { Content = "button 9" });
            stackContent.Children.Add(new Button() { Content = "button 10" });
            stackContent.Children.Add(new Button() { Content = "button 11" });
            stkPanel.Children.Add(pivot);
