    //Model
    class MyModel {
        //...
        public string[] DivOrder { get; set; };
        //...
    }
    //Controller Action
    MyModel model = new MyModel();
    //...
    model.DivOrder = new { "c", "b", "a" };
    //...
