        intNode myIntNode1 = new intNode();
        myIntNode1.Key = 100;
        intNode myIntNode2 = new intNode(777);
        strNode myStrNode1 = new strNode();
        myStrNode1.Key = "hello";
        strNode myStrNode2 = new strNode("string node 2");
        Tree<int> intTree = new Tree<int>();
        intTree.Name = "Tree of Integer";
        Tree<string> strTree = new Tree<string>("Tree of String");
        intTree.Nodes.Add(myIntNode1);
        intTree.Nodes.Add(myIntNode2);
        strTree.Nodes.Add(myStrNode1);
        strTree.Nodes.Add(myStrNode2);
        myIntNode1.Nodes.Add(new intNode(999));
        myStrNode2.Nodes.Add(new strNode("subNode of strNode2"));
        Console.WriteLine(intTree.Nodes.Count);
        Console.WriteLine(intTree.Nodes[0]);
        Console.WriteLine(strTree.Nodes.Count);
        Console.WriteLine(strTree.Nodes[1]);
