    class CustomerDepotAssociation
    {
        public Customer { get; }
        public Depot { get; }
    }
    class CustomerDepotAssociationRepository
    {
        IList<Customer> GetCustomersFor(Depot depot) ...
        IList<Depot> GetDepotsFor(Customer customer) ...
        void Associate(Depot depot, Customer customer) ...
        void DeAssociate(Depot depot, Customer customer) ...
    }
