    using System.Runtime.CompilerServices;
    ...
    class Tool { }
    class Hammer : Tool { }
    ...
    var hammers = new List<Hammer>();
    ...
    var tools = Unsafe.As<List<Tool>>(hammers);
