    <#@ template language="C#" #>
    <#@ output extension=".codegen.cs" #>
    <#@ assembly name="System.dll" #>
    <#@ import namespace="System" #>
    // <auto-generated>
    // This code was generated by a tool. Any changes made manually will be lost
    // the next time this code is regenerated.
    // </auto-generated>
    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    namespace MyStuff
    {
    <# foreach (string classname in classes) {#>
        public class <#= classname #> : IEquatable<ClassName> 
        {
                public <#= classname #>(string description) {
            Description = description;
        }
    
        public override bool Equals(object obj) {
            return obj != null &&
                typeof(<#= classname #>).IsAssignableFrom(obj.GetType()) && 
                Equals((<#= classname #>)obj);
        }
    
        public bool Equals(<#= classname #>other) {
            return other != null && 
                Description.Equals(other.Description);
        }
    
        public override int GetHashCode() {
            return Description.GetHashCode();
        }
    
        public override string ToString() {
            return Description;
        }
    
        public string Description { get; private set; }
        }
        }
        
    <# } #> 
    }
    
    <#+ string[] classes = new string[] {  "Class1",
                                           "Class2" };
    #>
