    using (FileStream fs = File.Open(fileName, FileMode.OpenOrCreate))
    {
        BinaryWriter sw = new System.IO.BinaryWriter(fs);
        sw.Write(Template.TemplateDatabase); // Autogenerated: the Embedded Resource
        fs.Flush();
        fs.Close();
    }
