    Namespace dsMyDatasetTableAdapters
        Partial Public Class Table1TableAdapter
            Public Overridable Overloads Function Fill(ByVal dataset As dsMyDataset, ByVal OrderNumber As String) As Integer
                Me.Adapter.SelectCommand = Me.CommandCollection(0)
                If (RecordID Is Nothing) Then
                    Me.Adapter.SelectCommand.Parameters(0).Value = Global.System.DBNull.Value
                Else
                    Me.Adapter.SelectCommand.Parameters(0).Value = CType(OrderNumber, String)
                End If
               
                'end autogenerated code'
    
                'Start Custom Code'
                Dim dsDump As New Data.DataSet
    
                Me.Adapter.Fill(dsDump)
    
                DatasetAutoMerge(dsDump, dataset)
            End Function
    
        End Class
    End Namespace
