    public static bool MightBeCouldBeMaybeAutoGeneratedInstanceProperty(
        this PropertyInfo info
    ) {
        bool mightBe = info.GetGetMethod()
                           .GetCustomAttributes(
                               typeof(CompilerGeneratedAttribute),
                               true
                           )
                           .Any();
        if (!mightBe) {
            return false;
        }
            
        bool maybe = info.DeclaringType
                         .GetFields(BindingFlags.NonPublic | BindingFlags.Instance)
                         .Where(f => f.Name.Contains(info.Name))
                         .Where(f => f.Name.Contains("BackingField"))
                         .Where(
                             f => f.GetCustomAttributes(
                                 typeof(CompilerGeneratedAttribute),
                                 true
                             ).Any()
                         )
                         .Any();
            return maybe;
        }
