            <XmlDataProvider x:Key="Properties" XPath="/Info" IsAsynchronous="False" IsInitialLoadEnabled="True">
            <x:XData>
                <Info xmlns="">
                    <Property>
                        <Name>Text</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Tooltip</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Enable</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Visible</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Focus</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Selected</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Count</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Item</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>SelectedText</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>SelectedIndex</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                    <Property>
                        <Name>Complete</Name>
                        <Value></Value>
                        <IsEnable>true</IsEnable>
                    </Property>
                </Info>
            </x:XData>
        </XmlDataProvider>
