    <#@ template debug="false" hostspecific="true" language="C#v3.5" #>
    <#@ output extension=".cs" #>
    <#@ assembly name="System.Core" #>
    <#@ import namespace="System.Linq" #>
    <# 
    // You "declare" your classes here, as in these examples:
    var src = @"
    Foo:     string Prop1, 
             int Prop2;
    Bar:     string FirstName,
             string LastName,
             int Age;
    ";
    // Parse the source text into a model of anonymous types
    Func<string, bool> notBlank = str => str.Trim() != string.Empty;
    var classes = src.Split(';').Where(notBlank).Select(c => c.Split(':'))
	    .Select(c => new 
	    {
		    Name = c.First().Trim(),
		    Properties = c.Skip(1).First().Split(',').Select(p => p.Split(' ').Where(notBlank))
					      .Select(p => new { Type = p.First(), Name = p.Skip(1).First() })
	    });
    #>
    // Do not edit this file by hand! It is auto-generated.
    namespace Generated 
    {
    <# foreach (var cls in classes) {#>    class <#= cls.Name #> 
	    {
            public bool IsDirty { get; private set; }
		    <# foreach (var prop in cls.Properties) { #>
    		
            private <#= prop.Type #> _storage<#= prop.Name #>; 
    			
            public <#= prop.Type #> <#= prop.Name #> 
            {
                get { return _storage<#= prop.Name #>; }
                set 
                {
                    IsDirty = true;
                    _storage<#= prop.Name #> = value;
                }
            } <# } #>
        }
        
    <# } #>
    }
