    writer.WriteStartElement("Person");
    writer.WriteAttributeString("Name", "Nick");
    writer.WriteEndElement();
    writer.WriteStartElement("Person");
    writer.WriteStartAttribute("Name");
    writer.WriteValue("Nick");
    writer.WriteEndAttribute();
    writer.WriteEndElement();
    writer.WriteEndElement();
    writer.WriteEndDocument();
    writer.Flush();
