    public class DependencyPropertySynchronizer
    {
      public DispatcherPriority Priority { get; set; }
      public DependencyProperty AutoSyncProperty { get; set; }
      public DependencyProperty Register(...
      public DependencyProperty RegisterAttached(...
      public DependencyPropertyKey RegisterReadOnly(...
      public DependencyPropertyKey RegisterAttachedReadOnly(...
    }
