    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
    <configSections>
    ...
      <sectionGroup name="system.net" type="System.Net.Configuration.NetSectionGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
        ...
        <section name="webRequestModules" type="System.Net.Configuration.WebRequestModulesSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
        ...
      </sectiongroup>
    ...
    </configsection>
    ...
    </configuration>
