    public class Product
    {
        public Product()
        {
            Photos.CollectionChanged += ListCollectionChanged;
        }
    
        public int Id { get; set; }
    
        public string Name { get; set; }
    
        public TrackableCollection<Photo> Photos
        {
            get
            {
                // default code generated by EF4 TT
            }
            set
            {
                // default code generated by EF4 TT
            }
        }
    
        private void ListCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            switch (e.Action)
            {
                // A new item has been added to collection
                case NotifyCollectionChangedAction.Add:
                    {
                        T newItem = (T) e.NewItems[0];
                        // Run custom business logic
                    }
                    break;
                
                // An existing item has been removed
                case NotifyCollectionChangedAction.Remove:
                    {
                        T oldItem = (T) e.OldItems[0];
                        // Run custom business logic
                    }
                    break;
            }
        }
    }
