    public delegate void CustomEventHandler(object sender, CustomEventArgs a);
    
    private CustomEventHandler customEventHandler; // <-- generated by the compiler
    
    public void add_CustomEventHandler(CustomEventHandler handler) {
      System.Delegate.Combine(customEventHandler, handler);
    }
    
    public void remove_CustomEventHandler(CustomEventHandler handler) {
      System.Delegate.Remove(customEventHandler, handler);
    }
    
    public event CustomEventHandler customEventHandler {
      add { add_customEventHandler(value) }
      remove { remove_customEventHandler(value) }
    }
