    <TestGroup>
      <ParallelTests>  
        <ParallelTest>
          <Name>Tests</Name>
            <Tests>
              <TestConf>
                <Name>Test1FF</Name>
                <Assembly>Test.dll</Assembly>
                <TestToRun>Test.Tests.Test1</TestToRun>
                <Machine>localhost:8080</Machine>
                <TestParams>
                  <string>*firefox</string>
                </TestParams>
              </TestConf>
              <TestConf>
                <Name>Test1IE</Name>
                <Assembly>Test.dll</Assembly>
                <TestToRun>Test.Tests.Test1</TestToRun>
                <Machine>localhost:8080</Machine>
                <TestParams>
                  <string>*iexplore</string>
                </TestParams>
              </TestConf>
            </Tests>
          </ParallelTest>
        </ParallelTests>
    </TestGroup>
