        public string Department { get; private set; }
        public string FirstName { get; private set; }
        public string MiddleName { get; private set; }
        public string LastName { get; private set; }
        public string LoginName { get; private set; }
        public string LoginNameWithDomain { get; private set; }
        public string StreetAddress { get; private set; }
        public string City { get; private set; }
        public string State { get; private set; }
        public string PostalCode { get; private set; }
        public string Country { get; private set; }
        public string HomePhone { get; private set; }
        public string Extension { get; private set; }
        public string Mobile { get; private set; }
        public string Fax { get; private set; }
        public string EmailAddress { get; private set; }
        public string Title { get; private set; }
        public string Company { get; private set; }
