    <Reference>
        <Assembly>System</Assembly>
			</Reference>
			<Reference>
				<Assembly>System.Data</Assembly>
			</Reference>
			<Reference>
				<Assembly>System.Xml</Assembly>
			</Reference>
		</References>
