    List<Employee> employees = new List<Employee>();
    employees.Add(new Employee(1, null));
    employees.Add(new Employee(2, null));
    employees.Add(new Employee(3, 1));
    employees.Add(new Employee(4, 1));
    employees.Add(new Employee(5, 3));
    employees.Add(new Employee(6, 2));
    employees.Add(new Employee(7, 3));
    employees.Add(new Employee(8, 4));
    employees.Add(new Employee(9, 2));
    employees.Add(new Employee(10, 6));
