        ...
        new UIPropertyMetadata(
            default(string), 
            new PropertyChangedCallback(TextBox_TextChanged)
        )
        ...
        static void TextBox_TextChanged(DependencyObject sender, DependencyPropertyChangedEventArgs e) {
            ...
        }
