    // Generated by EF4
    public partial class EntityA : EntityObject
    {
        ...
    }
    // Interface defined in another file
    public interface IGClass<T> where T : IGClass<T>
    {
        string GetStr();
    }
    // Automatically generated by T4 template
    public partial class EntityA : IGClass<EntityA>
    {
        public virtual string GetStr()
        {
            return "GClass";
        }
    }
