    using System.Xml;
    //Console.WriteLine("enter coordinate:");
    string coordinate = "32.797821,-96.781720"; //Console.ReadLine();
    XmlDocument xDoc = new XmlDocument();
    xDoc.Load("https://maps.googleapis.com/maps/api/geocode/xml?latlng=" + coordinate);
    XmlNodeList xNodelst = xDoc.GetElementsByTagName("result");
    XmlNode xNode = xNodelst.Item(0);
    string FullAddress = xNode.SelectSingleNode("formatted_address").InnerText;
    string Number = xNode.SelectSingleNode("address_component[1]/long_name").InnerText;
    string Street = xNode.SelectSingleNode("address_component[2]/long_name").InnerText;
    string Village = xNode.SelectSingleNode("address_component[3]/long_name").InnerText;
    string Area = xNode.SelectSingleNode("address_component[4]/long_name").InnerText;
    string County = xNode.SelectSingleNode("address_component[5]/long_name").InnerText;
    string State = xNode.SelectSingleNode("address_component[6]/long_name").InnerText;
    string Zip = xNode.SelectSingleNode("address_component[8]/long_name").InnerText;
    string Country = xNode.SelectSingleNode("address_component[7]/long_name").InnerText;
    Console.WriteLine("Full Address: " + FullAddress);
    Console.WriteLine("Number: " + Number);
    Console.WriteLine("Street: " + Street);
    Console.WriteLine("Village: " + Village);
    Console.WriteLine("Area: " + Area);
    Console.WriteLine("County: " + County);
    Console.WriteLine("State: " + State);
    Console.WriteLine("Zip: " + Zip);
    Console.WriteLine("Country: " + Country);
    Console.ReadLine();
