    private void cboTargetMode_SelectedIndexChanged(object sender, EventArgs e) {
        // need to get the previously selected index and do some handling here...
        // ... some handler code here ...
        // Assuming that the variable PreviousSelectedIndex is declared in the class with value -1.
        if (PreviousSelectedIndex < 0)
            PreviousSelectedIndex = cbo.TargetMode.SelectedIndex;
        else
            // Do some handling here...
        switch (cboTargetMode.SelectedIndex) {
            case 1:  // ..... some code here...
                break;
            case 2:  // ..... some code here...
                break;
            case 3:  // ..... some code here...
                break;
            default: // ..... some code here...
                break;
        }
    }
