    Assert.AreEqual("For You And I", "ForYouAndI".UnPascalCase());
    Assert.AreEqual("For You And The FBI", "ForYouAndTheFBI".UnPascalCase());
    Assert.AreEqual("A Man A Plan A Canal Panama", "AManAPlanACanalPanama".UnPascalCase());
    Assert.AreEqual("DNS Server", "DNSServer".UnPascalCase());
    Assert.AreEqual("For You And I", "For You And I".UnPascalCase());
    Assert.AreEqual("Mount Mᶜ Kinley National Park", "MountMᶜKinleyNationalPark".UnPascalCase());
    Assert.AreEqual("El Álamo Tejano", "ElÁlamoTejano".UnPascalCase());
    Assert.AreEqual("The Ævar Arnfjörð Bjarmason", "TheÆvarArnfjörðBjarmason".UnPascalCase());
    Assert.AreEqual("Il Caffè Macchiato", "IlCaffèMacchiato".UnPascalCase());
    //Assert.AreEqual("Mister ǅenan ǈubović", "Misterǅenanǈubović".UnPascalCase());
    //Assert.AreEqual("Ole King Henry Ⅷ", "OleKingHenryⅧ".UnPascalCase());
    //Assert.AreEqual("Carlos Ⅴº El Emperador", "CarlosⅤºElEmperador".UnPascalCase());
    Assert.AreEqual("For You And The FBI", "For You And The FBI".UnPascalCase());
    Assert.AreEqual("A Man A Plan A Canal Panama", "A Man A Plan A Canal Panama".UnPascalCase());
    Assert.AreEqual("DNS Server", "DNS Server".UnPascalCase());
    Assert.AreEqual("Mount Mᶜ Kinley National Park", "Mount Mᶜ Kinley National Park".UnPascalCase());
