    // <autogenerated/>
    // Last generated <#= DateTime.Now #>
    <#@ template language="C#" hostspecific="true"#>
    <#@ assembly name="System" #>
    <#@ VolatileAssembly processor="T4Toolbox.VolatileAssemblyProcessor" name="bin\debug\FrameworkWpf.dll" #>
    <#@ VolatileAssembly processor="T4Toolbox.VolatileAssemblyProcessor" name="bin\debug\FrameworkTestToolkit.dll" #>
    <#@ VolatileAssembly processor="T4Toolbox.VolatileAssemblyProcessor" name="bin\debug\WpfAppTemplate.exe" #>
    <#@ output extension=".cs" #>
    <#@ import namespace="System" #>
    <#@ import namespace="FrameworkTestToolkit" #>
    namespace WpfAppTemplateTest {
     using System;
     using System.Reflection;
    <# 
        // Add new types into the below array:
        Type[] types = new Type[] { 
     typeof(FrameworkWpf.SafeEvent),
     typeof(FrameworkWpf.Mvvm.ControllerBase),
     typeof(FrameworkTestToolkit.PrivateAccessorGeneratorTestClass),
     typeof(WpfAppTemplate.PostController),
     typeof(WpfAppTemplate.ShellController),
     };
     // Do not modify this code
     foreach (Type type in types) {
     PrivateAccessorGenerator builder = new PrivateAccessorGenerator(type, WriteLine, Error, Warning);
     builder.Generate();
     }
    #>
    }
