    public class MvcApplication : System.Web.HttpApplication
    {
        ...
        protected void Application_Start()
        {
            ...
            ControllerBuilder.Current.SetControllerFactory(typeof(ContextControllerFactory));
            ...
        }
        ...
    }
