    public class WillsQuoteViewModel
    {
        public string Product { get; set; }
        public List<ClaimedFee> ClaimedFees { get; set; }
    }
    
    public partial class ClaimedFee //Generated by EF6
    {
        public long Id { get; set; }
        public long JourneyId { get; set; }
        public string Title { get; set; }
        public decimal Net { get; set; }
        public decimal Vat { get; set; }
        public string Type { get; set; }
    
        public virtual Journey Journey { get; set; }
    }
