	<#@ template language="C#" #>
	<#@ assembly name="System.Core" #>
	<#@ import namespace="System.Linq" #>
	//
	// This code was generated by a tool. Any changes made manually will be lost
	// the next time this code is regenerated.
	//
	using System.Reflection;
	<#
		var date = DateTime.Now;
		int major = 1;
		int minor = date.Year;
		int build = 10000 + int.Parse(date.ToString("MMdd"));
		int revision = 10000 + int.Parse(date.ToString("HHmm"));
	#>
	[assembly: AssemblyVersion("<#= $"{major}.{minor}.{build}.{revision}" #>")]
	[assembly: AssemblyFileVersion("<#= $"{major}.{minor}.{build}.{revision}" #>")]
