    // Not valid in C# - yet!
    public class Foo
    {
        // Autogenerated field would be readonly in IL.
        public string Name { get; readonly set; }
        public Foo (string name)
        {
            this.Name = name;
        }
        public void Bar()
        {
            // This would be invalid
            this.Name = "No!";
        }
    }
