    //MemberServiceClient is the class generated by SvcUtil
    public class MemberServiceManager : ServiceClientBase<MemberServiceClient>
    {
        public User GetUser(int userId)
        {
            return PerformServiceOperation(client => client.GetUser(userId));
        }
        //you can also check if any error occured if you can't throw exceptions       
        public bool TryGetUser(int userId, out User user)
        {
            return TryPerformServiceOperation(c => c.GetUser(userId), out user);
        }
    }
