    System.Object
      System.Drawing.Design.UITypeEditor
        System.ComponentModel.Design.CollectionEditor
          System.ComponentModel.Design.ArrayEditor
          System.Web.UI.Design.CollectionEditorBase
          System.Web.UI.Design.WebControls.WizardStepCollectionEditor
          System.Web.UI.Design.WebControls.EmbeddedMailObjectCollectionEditor
          System.Web.UI.Design.WebControls.HotSpotCollectionEditor
          System.Web.UI.Design.WebControls.ListItemsCollectionEditor
          System.Web.UI.Design.WebControls.MenuItemStyleCollectionEditor
          System.Web.UI.Design.WebControls.RoleGroupCollectionEditor
          System.Web.UI.Design.WebControls.StyleCollectionEditor
          System.Web.UI.Design.WebControls.SubMenuStyleCollectionEditor
          System.Web.UI.Design.WebControls.TableCellsCollectionEditor
          System.Web.UI.Design.WebControls.TableRowsCollectionEditor
        System.ComponentModel.Design.BinaryEditor
        System.ComponentModel.Design.DateTimeEditor
        System.ComponentModel.Design.MultilineStringEditor
        System.ComponentModel.Design.ObjectSelectorEditor
        System.Windows.Forms.Design.AnchorEditor
        System.Windows.Forms.Design.BorderSidesEditor
        System.Windows.Forms.Design.DockEditor
        System.Windows.Forms.Design.FileNameEditor
        System.Windows.Forms.Design.FolderNameEditor
        System.Windows.Forms.Design.ShortcutKeysEditor
        System.Web.UI.Design.ConnectionStringEditor
        System.Web.UI.Design.DataBindingCollectionEditor
        System.Web.UI.Design.ExpressionsCollectionEditor
        System.Web.UI.Design.UrlEditor
        System.Web.UI.Design.XmlFileEditor
        System.Web.UI.Design.WebControls.DataGridColumnCollectionEditor
        System.Web.UI.Design.WebControls.DataControlFieldTypeEditor
        System.Web.UI.Design.WebControls.MenuBindingsEditor
        System.Web.UI.Design.WebControls.MenuItemCollectionEditor
        System.Web.UI.Design.WebControls.ParameterCollectionEditor
        System.Web.UI.Design.WebControls.RegexTypeEditor
        System.Web.UI.Design.WebControls.TreeNodeCollectionEditor
        System.Web.UI.Design.WebControls.TreeViewBindingsEditor
        System.Web.UI.Design.WebControls.DataPagerFieldTypeEditor
        System.Messaging.Design.QueuePathEditor
        System.Drawing.Design.ImageEditor
        System.Drawing.Design.ColorEditor
        System.Drawing.Design.ContentAlignmentEditor
        System.Drawing.Design.CursorEditor
        System.Drawing.Design.FontEditor
        System.Drawing.Design.FontNameEditor
        System.Drawing.Design.IconEditor
        System.Workflow.ComponentModel.Design.TypeBrowserEditor
        System.Workflow.ComponentModel.Design.BindUITypeEditor
