&lt;file&gt;
&lt;copyright&gt;(c) Extreme Designers Inc. 2008.&lt;/copyright&gt;
&lt;datecreated&gt;2008-09-15&lt;/datecreated&gt;
&lt;summary&gt;
Here's my summary
&lt;/summary&gt;
&lt;remarks&gt;
&lt;para&gt;The &lt;see cref="TextReader"/&gt; can be used in the following ways:&lt;/para&gt;
&lt;list type="number"&gt;
&lt;item&gt;first item&lt;/item&gt;
&lt;item&gt;second item&lt;/item&gt;
&lt;/list&gt;
&lt;/remarks&gt;
&lt;example&gt;
&lt;code&gt;
System.Console.WriteLine("Hello, World");
&lt;/code&gt;
&lt;/example&gt;
&lt;param name="aParam"&gt;My first param&lt;/param&gt;
&lt;returns&gt;an object that represents a summary&lt;/returns&gt;
&lt;/file&gt;
