    Microsoft.Practices.CompositeUI.dll
    Microsoft.Practices.CompositeUI.WinForms.dll
    Microsoft.Practices.CompositeUI.WPF.dll
    Microsoft.Practices.EnterpriseLibrary.Common.dll
    Microsoft.Practices.EnterpriseLibrary.Data.dll
    Microsoft.Practices.EnterpriseLibrary.Data.SqlCe.dll
    Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.dll
    Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging.dll
    Microsoft.Practices.EnterpriseLibrary.Logging.dll
    Microsoft.Practices.ObjectBuilder.dll
    Microsoft.Practices.SmartClient.ConnectionMonitor.dll
    Microsoft.Practices.SmartClient.DisconnectedAgent.dll
    Microsoft.Practices.SmartClient.EndpointCatalog.dll
    Microsoft.Practices.SmartClient.EnterpriseLibrary.dll
