    public abstract class SqlDatabaseAdapter : DatabaseAdapter, ISqlDatabaseAdapter
    ...
    public class Sql2000DatabaseAdapter : SqlDatabaseAdapter
    ...
    public class Sql2005DatabaseAdapter : SqlDatabaseAdapter
    ...
