    /// <summary>
    /// Attempts to convert a string to a guid.
    /// </summary>
    /// <param name="s">The string to try to convert</param>
    /// <param name="value">Upon return will contain the Guid</param>
    /// <returns>Returns true if successful, otherwise false</returns>
    public static Boolean TryStrToGuid(String s, out Guid value)
    {
       int hresult = PInvoke.ObjBase.CLSIDFromString(s, out value);
       if (hresult >= 0)
       {
          return true;
       }
       else
       {
          value = Guid.Empty;
          return false;
       }
    }
    namespace PInvoke
    {
    	class ObjBase
    	{
    		/// <summary>
    		/// This function converts a string generated by the StringFromCLSID function back into the original class identifier.
    		/// </summary>
    		/// <param name="sz">String that represents the class identifier</param>
    		/// <param name="clsid">On return will contain the class identifier</param>
    		/// <returns>
    		/// Positive or zero if class identifier was obtained successfully
    		/// Negative if the call failed
    		/// </returns>
    		[DllImport("ole32.dll", CharSet = CharSet.Unicode, ExactSpelling = true, PreserveSig = true)]
    		public static extern int CLSIDFromString(string sz, out Guid clsid);
    	}
    }
