    this.detailTable.ColumnCount = 2;
    this.detailTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
    this.detailTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle());
    this.detailTable.Dock = System.Windows.Forms.DockStyle.Fill;
    this.detailTable.Location = new System.Drawing.Point(0, 0);
    this.detailTable.Name = "detailTable";
    this.detailTable.RowCount = 1;
    this.detailTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
    this.detailTable.Size = new System.Drawing.Size(266, 436);
    this.detailTable.TabIndex = 0;
