    using System;
    using System.Collections.Generic;
    using System.IO.Ports;
    using System.Linq;
      public static readonly List<string> SupportedBaudRates = new List<string>
    {
        "300",
        "600",
        "1200",
        "2400",
        "4800",
        "9600",
        "19200",
        "38400",
        "57600",
        "115200",
        "230400",
        "460800",
        "921600"
    };
    public static int MaxBaudRate(string portName)
    {
        var maxBaudRate = 0;
        SerialPort serialPort = null;
        try
       {
            serialPort = new SerialPort(portName);
           foreach (var baud in SupportedBaudRates)
           {
               var intBaud = Convert.ToInt32(baud);
               serialPort.BaudRate = intBaud;
               serialPort.Open();
               serialPort.Close();
               maxBaudRate = intBaud;
           }
       }
        catch
        {
            // ignored - traps exception generated by
            // baud rate not supported
        }
        finally
        {
            if(serialPort?.IsOpen == true)
                serialPort.Close();
        }
        return maxBaudRate;
    }
   
