    using System;
    using System.Collections.Generic;
    using System.IO.Ports;
    using System.Linq;
      public static readonly List<string> SupportedBaudRates = new List<string>
    {
        "300",
        "600",
        "1200",
        "2400",
        "4800",
        "9600",
        "19200",
        "38400",
        "57600",
        "115200",
        "230400",
        "460800",
        "921600"
    };
        public static int MaxBaudRate(string portName)
        {
            var maxBaudRate = 0;
            try
            {
                //SupportedBaudRates has the commonly used baudRate rates in it
                //flavor to taste
                foreach (var baudRate in ConstantsType.SupportedBaudRates)
                {
                    var intBaud = Convert.ToInt32(baudRate);
                    using (var port = new SerialPort(portName))
                    {
                        port.BaudRate = intBaud;
                        port.Open();
                    }
                    maxBaudRate = intBaud;
                }
            }
            catch
            {
                //ignored - traps exception generated by
                //baudRate rate not supported
            }
            return maxBaudRate;
        }
   
