    System.DateTime Add (System.TimeSpan value)
    System.DateTime AddDays (System.Double value)
    System.DateTime AddHours (System.Double value)
    System.DateTime AddMilliseconds (System.Double value)
    System.DateTime AddMinutes (System.Double value)
    System.DateTime AddMonths (System.Int32 months)
    System.DateTime AddSeconds (System.Double value)
    System.DateTime AddTicks (System.Int64 value)
    System.DateTime AddYears (System.Int32 value)
    System.Int32 Compare (System.DateTime t1, System.DateTime t2)
    System.Int32 CompareTo (System.Object value)
    System.Int32 CompareTo (System.DateTime value)
    System.Int32 DaysInMonth (System.Int32 year, System.Int32 month)
