        Table table = new System.Web.UI.WebControls.Table();
        TableRow tableRow;
        TableCell tableCell;
        tableRow = new TableRow();
        tableRow.TableSection = TableRowSection.TableHeader;
        tableCell = new TableCell();
        tableCell.Text = "HEADER";
        tableRow.Cells.Add(tableCell);
        table.Rows.Add(tableRow);
        tableRow = new TableRow();
        tableRow.TableSection = TableRowSection.TableBody;
        tableCell = new TableCell();
        tableCell.Text = "BODY";
        tableRow.Cells.Add(tableCell);
        table.Rows.Add(tableRow);
        tableRow = new TableRow();
        tableRow.TableSection = TableRowSection.TableFooter;
        tableCell = new TableCell();
        tableCell.Text = "FOOTER";
        tableRow.Cells.Add(tableCell);
        table.Rows.Add(tableRow);
        plhTest.Controls.Add(table);
