    //This class in generated by RIA wizard when you create 
    //your DomainService (based on LinqToSqlDomainService) and you check
    //[x]Generate metadata class in wizard window
    //file: MyService.metadata.cs
    [MetadataTypeAttribute(typeof(RegionCurrentStates.RegionCurrentStatesMetadata))]
    public partial class RegionCurrentStates
    {
        internal sealed class RegionCurrentStatesMetadata
        {      
          [Include]  //Add (only) this line 
          public List<State> States{ get; set; }
        }
    }        
