    // MyServiceClient is the class generated by svcutil.exe which derives from
    // System.ServiceModel.ClientBase<TServiceContract> and which allows you to
    // call the web service methods
    using (var client = new MyServiceClient())
    using (var scope = new OperationContextScope(client.InnerChannel))
    {
        var httpRequestProperty = new HttpRequestMessageProperty();
        // Set the header value
        httpRequestProperty.Headers.Add("JSESSIONID", "XXXXX");
        OperationContext.Current.OutgoingMessageProperties[HttpRequestMessageProperty.Name] = httpRequestProperty;
        // Invoke the method
        client.SomeMethod();
    }
