    public object GetProperty(object Instance, string Property)
    public object InvokeMethod(object Instance, string Method)
    public object InvokeMethod_OneParm(object Instance, string Method, object Parm1)
    public object InvokeMethod_TwoParms(object Instance, string Method, object Parm1, object Parm2)
    public void SetProperty(object Instance, string Property, object Value)
