    DataGridViewCheckBoxCell checkBoxCell = new MyDataGridViewCheckBoxCell();
    ...
    DataGridViewColumn col = new DataGridViewColumn(checkBoxCell);
    ...
    col.Name = "colCheckBox";
    ...
    this.dgItems.Columns.Add(col);
