    public methods
    public events
    public properties
    protected methods
    protected events
    protected properties
    private methods
    private events
    private properties
    private fields
    public delegates
    public interfaces
    public classes
    public structs
    protected delegates
    protected interfaces
    protected classes
    protected structs
    private delegates
    private interfaces
    private classes
    private structs
