    /// <summary>use reflection to serialize all properties and type into an xml string</summary>
    /// <param name="s">shape object to be serialized</param>
    /// <return>the serialized xml string</return>
    public static string SerializeShape(Shape s);
    
    /// <summary>create a new Shape object with given xml data</summary>
    /// <param name="s">xml serialization generated by SerializeShape(Shape s)</param>
    /// <return>the constructed shape</return>
    public static Shape DeserializeShape(string s);
