    private void DataGrid_AutoGeneratedColunns(object sender, EventArgs e)
    {
      if (dataGrid.Columns.Count > 0)
      {
        dataGrid.Columns.Where(a => a.Header.ToString() == "query column name").First().Header = "desired display name";
      }
    }
