    public partial class Startup
    {
        ...
        public void ConfigureAuth(IAppBuilder app)
        {
            ...
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                ...
                CookieName = System.Configuration.ConfigurationManager.AppSettings["OwinCookie"],
        ...
