    class MyModel
    {
       ...
       ...
       public int srfId { get; set;}
       ...
       ...
       public string SrfIdFormatted
       {
         get { srfId.ToString("00"); }
       }
       ...
    }
