    // construct the db connection and command object
    var con = new SqlConnection("Your Connection String");
    using(var cmd = new SqlCommand(con) { CommandType = CommandType.Text })
    {
        // tell the command what SQL query we want to execute
        cmd.CommandText = @"
    
    DECLARE @startnum INT=1
    DECLARE @endnum INT= SELECT TOP 1 Number FROM ValueTable
    ;
    WITH gen AS (
        SELECT @startnum AS num
        UNION ALL
        SELECT num+1 FROM gen WHERE num+1<=@endnum
    )
    SELECT * FROM gen
    option (maxrecursion 100)
    
    ";
    
        // connect to the db and execute the command
        con.Open();
        using(var reader = cmd.ExecuteReader())
        {
            // build the range from the values generated by it
            var range = new List<int>();
            while(reader.Read()) { range.Add(reader.Read()); }
            // bind the results to the drop down on the page   
            DropDownList.DataSource = range
              .Select(i = > new { Key = i, Value = i })
              .ToArray();
            DropDownList.DisplayField = "Key";
            DropDownList.ValueField = "Value";
            DropDownList.DataBind();
        }
        con.Close();
    }
