    public async Task<ActionResult> RunAsync(string a, string b)
    {
      ...
      ...
      ...
      Result obj = new Result();
      ...
      ...
      ...
      return RedirectToActtion("Index", "HomeController",new { resultop =result });
    }
