    public async Task<ActionResult> RunAsync(string a, string b)
    {
      ...
      ...
      ...
      Result obj = new Result();
      obj.loginJsonStringop = "VALUE_OF_FIELD";
      ...
      ...
      ...
      return RedirectToActtion("Index", "HomeController",new { resultop =result });
    }
