    public void ConfigureService(IServiceCollection services)
    {
        ...
        services.AddMvc(options => 
        {
            ...
            options.Filters.Add(typeof(EntityNotFoundExceptionFilter));
            ...
        }
        ...
    }
