      Gridview1.AllowPaging = false;
            ///serch(); or/// bind();
            Response.ClearContent();
            Response.Buffer = true;
           
          
            Response.AddHeader("content-disposition", string.Format("attachment; filename={0}", "Daybook.xls"));
            // Response.ContentType = "application/vnd.ms-excel";
            Response.ContentType = "File/Data.xls";
            this.EnableViewState = false;
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            Gridview1.RenderControl(htw);
            string cell = Gridview1.HeaderRow.Cells.Count.ToString();
            //string headerTable30 = " " + " " + " " + " " + "City  ";
            //string strr30 = headerTable30.Replace(" ", "&nbsp;");
            //string Head30 = "<b style='color: Blue'>" + strr30 + "</b>";
            string headerTable31 = " " + clntname.Text + " ";
            string strr31 = headerTable31.Replace(" ", "&nbsp;");
            string Head31 = "<table align=center><tr><td colspan=" + cell + " style='text-align:center; color: #177FC5;'><h3> " + headerTable31 + "</h3></td></tr></table>";
            string headerTable32 = " " + " Address ";
            string strr32 = headerTable32.Replace(" ", "&nbsp;");
            string Head32 = "<b style='color: Blue'>" + strr32 + "</b>";
            string headerTable33 = " " + add1.Text + " ";
            string strr33 = headerTable33.Replace(" ", "&nbsp;");
            string Head33 = "<b>" + strr33 + "</b>";
            string headerTable34 = " " + add2.Text + " ";
            string strr34 = headerTable34.Replace(" ", "&nbsp;");
            string Head34 = "<b>" + strr34 + "</b>";
            string headerTable35 = " " + add3.Text + " ";
            string strr35 = headerTable35.Replace(" ", "&nbsp;");
            string Head35 = "<b>" + strr35 + "</b>";
            string headerTable36 = " " + " City ";
            string strr36 = headerTable36.Replace(" ", "&nbsp;");
            string Head36 = "<b style='color: Blue'>" + strr36 + "</b>";
            string headerTable37 = " " + city.Text + " ";
            string strr37 = headerTable37.Replace(" ", "&nbsp;");
            string Head37 = "<b>" + strr37 + "</b>";
            string headerTable38 = " " + " Pincode ";
            string strr38 = headerTable38.Replace(" ", "&nbsp;");
            string Head38 = "<b style='color: Blue'>" + strr38 + "</b>";
            string headerTable39 = " " + pincode.Text + " ";
            string strr39 = headerTable39.Replace(" ", "&nbsp;");
            string Head39 = "<b>" + strr39 + "</b>";
            string Head40 = "<table><tr><td colspan=15><b>" + Head32 + "</b><b>" + Head33 + "</b><b>" + Head34 + "</b><b>" + Head35 + "</b></td></tr></table>";
            string Head41 = "<table><tr><td colspan=15><b>" + Head36 + "</b><b>" + Head37 + "</b><b>" + Head38 + "</b><b>" + Head39 + "</b></td></tr></table>";
            // string Head42 = "<table><tr><td colspan=15><b>" + Head35 + "</b><b>" + Head36 + "</b><b>" + Head37 + "</b><b>" + Head38 + "</b></td></tr></table>";
            string headerTable1 = "Day Book";
            string Head1 = "<table align=center><tr><td colspan=" + cell + " style='text-align:center; color: Red;'><h3> " + headerTable1 + "</h3></td></tr></table>";
            string headerTable8 = " " + " " + " " + " From";
            string strr8 = headerTable8.Replace(" ", "&nbsp;");
            string Head8 = "<b style='color: Blue; '>" + strr8 + "</b>";
            string headerTable9 = " " + "  " + txtfrom.Text + " ";
            string strr9 = headerTable9.Replace(" ", "&nbsp;");
            string Head9 = "<b>" + strr9 + "</b>";
            string headerTable10 = " " + " " + " " + " To";
            string strr10 = headerTable10.Replace(" ", "&nbsp;");
            string Head10 = "<b style='color: Blue'>" + strr10 + "</b>";
            string headerTable11 = " " + " " + txtto.Text + "";
            string strr11 = headerTable11.Replace(" ", "&nbsp;");
            string Head11 = "<b>" + strr11 + "</b>";
            string headerTable12 = " " + Label1.Text+" "+" "+Label2.Text;
            string strr12 = headerTable12.Replace(" ", "&nbsp;");
            string Head12 = "<b>" + strr12 + "</b>";
            //string Head20 = "<table><tr><td colspan=15><b>" + Head2 + "</b><b>" + Head3 + "</b><b>" + Head4 + "</b><b>" + Head5 + "</b><b>" + Head6 + "</b><b>" + Head7 + "</b></td></tr></table>";
            string Head21 = "<table><tr><td colspan=10><b>" + Head8 + "</b><b>" + Head9 + "</b><b>" + Head10 + "</b><b>" + Head11 + "</b></td></tr></table>";
            string Head22 = "<table><tr><td colspan=10><b>" + Head12 + "</b></td></tr></table>";
            Response.Write(Head31);
            Response.Write(Head40);
            Response.Write(Head41);
            Response.Write(Head1);
            //Response.Write(Head20);
            Response.Write(Head21);
            Response.Write(Head22);
            Response.Write(sw.ToString());
            Response.Flush();
            Response.End();
