        //public event LowOnFuelHandler LowOnFuel;
        //public delegate void LowOnFuelHandler(byte fuelLevel);
        public event Action<byte> LowOnFuelEvent = delegate { };
        ...
        ...
        LowOnFuelEvent += LowOnFuelHandler;  // the actual method must match the delegate signature
        ...
        ...
        if (mFuelLevel < 30 && mFuelLevel > 0)
        {
            LowOnFuelEvent(mFuelLevel);
        }
