    //------------------------------------------------------------------------------
    // <auto-generated>
    / ....
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    [assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.chemspider.com/", ClrNamespace="www.chemspider.com")]
    
    namespace www.chemspider.com
    {
        using System.Runtime.Serialization;
        
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.chemspider.com/", ItemName="string")]
        public class ArrayOfString : System.Collections.Generic.List<string>
        {
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ECompression", Namespace="http://www.chemspider.com/")]
        public enum ECompression : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            eGzip = 0,
        }
