    public class Startup
    {
        ...
        public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddScoped<IUserSession, UserSession>();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            ...
        }
        ...
    }
