            var plotModel = new PlotModel { Title = "OxyPlot Demo" };
            ///Other code...
            ///...
            ///...
            ///...
            var textAnnotation = new TextAnnotation
            {
                Text = "Text1",
                TextPosition = new DataPoint(1.0, 2.0)
            };
            plotModel.Annotations.Add(textAnnotation);
