    <NewDataSet>
    	<Header>
    		<BankName>SAMA</BankName>
    		<CashCenterName>SAMA Riyadh</CashCenterName>
    	</Header>
    	<DepositorList>
    		<ReferenceNumber>1</ReferenceNumber>
    		<DepositList_Id>0</DepositList_Id>
    		<PreparedBy>FZE</PreparedBy>
    		<TotalContainerCount>2</TotalContainerCount>
    		<ExpectedDate>2018-04-19T09:13:10-05:00</ExpectedDate>
    		<DeclaredAmount>150000</DeclaredAmount>
    		<ContainerList>
    			<ContainerNumber>903000033102</ContainerNumber>
    			<DeclaredAmount>50000</DeclaredAmount>
    			<ContainerContentList>
    				<ContainerContentList_Id>0</ContainerContentList_Id>
    				<TotalRecordCount>1</TotalRecordCount>
    				<ContainerList_Id>0</ContainerList_Id>
    			</ContainerContentList>
    		</ContainerList>
    		<ContainerList>
    			<ContainerNumber>903000033103</ContainerNumber>
    			<ContainerList_Id>1</ContainerList_Id>
    			<DeclaredAmount>100000</DeclaredAmount>
    			<DepositList_Id>0</DepositList_Id>
    		</ContainerList>
    	</DepositorList>
    </NewDataSet>
