    [assembly: AssemblyTitle("Loader")]
    [assembly: AssemblyDescription("")]
    [assembly: AssemblyConfiguration("")]
    [assembly: AssemblyCompany("Microsoft")]
    [assembly: AssemblyProduct("Loader")]
    [assembly: AssemblyCopyright("Copyright © Microsoft 2017")]
    [assembly: AssemblyTrademark("")]
    [assembly: AssemblyCulture("")]
    [assembly: ComVisible(false)]
    [assembly: Guid("f99d6ga6-3b37-43a6-9332-866f8s8g7f9b")]
    [assembly: AssemblyVersion("1.0.0.0")]
    [assembly: AssemblyFileVersion("1.0.0.0")]
