    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    
    using Aspose.Cells;
    
    public partial class _Default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            
        }
    
        protected void btnSaveToXLS_Click(object sender, EventArgs e)
        {
            //Create empty workbook.
            Workbook workbook = new Workbook();
    
            // Access first worksheet
            Worksheet worksheet = workbook.Worksheets[0];
    
            // Put some value in cell C4
            Cell cell = worksheet.Cells["C4"];
            cell.PutValue("This is XLS format generated by Aspose.Cells API.");
    
            // Save file and send to client browser using selected format
            workbook.Save(HttpContext.Current.Response, "outputSaveToXLS.xls", ContentDisposition.Attachment, new XlsSaveOptions(SaveFormat.Excel97To2003));
    
            HttpContext.Current.Response.End();
        }
    
        protected void btnSaveToXLSX_Click(object sender, EventArgs e)
        {
            //Create empty workbook.
            Workbook workbook = new Workbook();
    
            // Access first worksheet
            Worksheet worksheet = workbook.Worksheets[0];
    
            // Put some value in cell C4
            Cell cell = worksheet.Cells["C4"];
            cell.PutValue("This is XLSX format generated by Aspose.Cells API.");
    
            // Save file and send to client browser using selected format
            workbook.Save(HttpContext.Current.Response, "outputSaveToXLSX.xlsx", ContentDisposition.Attachment, new OoxmlSaveOptions(SaveFormat.Xlsx));
    
            HttpContext.Current.Response.End();
        }
    }
