    foreach (var record in AllConditionsByCountry)
    {
      ...
      ...
      ...
      var rList = AllConditionsByCountry.Where(x => x.ConditionID == conditionID).Select(x => x).AsEnumerable();                        
      conditionDescriptionTypeID = item.ConditionDescriptionTypeId;
      id = conditionDescriptionTypeID + "_" + count.ToString();              
      ...
      ...
    }
