    List<Product> list = new List<Product>();
            Product p1 = new Product();
            p1.ID = 1;
            p1.Name = "Mobile";
            p1.Category = "Electronics";
            p1.PriceDollar = "200";
            Product p2 = new Product();
            p2.ID = 2;
            p2.Name = "Mobile";
            p2.Category = "Electronics";
            p2.PriceDollar = "400";
            Product p3 = new Product();
            p3.ID = 3;
            p3.Name = "Chair";
            p3.Category = "Furniture";
            p3.PriceDollar = "100";
            list.Add(p1);
            list.Add(p2);
            list.Add(p3);
