    ...
    var QueryBD = services.LoadDataFormGasoline(1, (int)ETax.Gasoline)
    ...
    loadlist<string>(QueryBD.myListOfStrings, "nameControl");
    loadlist<int>(QueryBD.myListOfInts,"nameControl");
    ...
