    //------------------------------------------------------------------------------
    // <auto-generated>
    //------------------------------------------------------------------------------
    using System.ComponentModel.DataAnnotations;               // THIS ONE
    namespace Rapport_CE_MVC.Models
    {
        using System;
        public partial class ExtractionPourFicheSante_Result
        {
            [Key]                                              // AND THIS ONE
            public string fonds { get; set; }
            /* all the rest of the properties */
        }
    }
