    Events = new Dictionary<short, IAsyncPacket>()
    ... (code to load dictionary) ...
    ...
    if (Events.TryGetValue(packetId, out IAsyncPacket p))
    {
        await p.Handle(session, packet, coreContext);
    }
    ...
