    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Web;
    
    namespace AwesomeCode.Models
    {
        public class WorkExp
        {
            [Key]
            public int Id { get; set; }
            public string JobTitle { get; set; }
            // Foreign key 
            [Display(Name = "UserId")]
            public string UserId { get; set; }
            //Create foreign key with reference to ApplicationUser_Id that was auto-generated by entity framework.
            public virtual ApplicationUser ApplicationUser { get; set; }
        }
    }
