    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        // Enable Cors
        app.UseCors("MyPolicy");
        ...
        ...
        ...
    }
