    /// <summary>
    /// Implements auto generated Id property for CosmosDb Model
    /// </summary>
    public abstract class BaseModel
    {
        /// <summary>
        /// PK for this model. (apart from the ResourceId which is internally generated by CosmoDb)
        /// If the user does not set this, the SDK will set this automatically to a GUID.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public virtual string Id { get; set; }
    
        /// <summary>
        /// Any unmapped properties from the JSON data deserializes into this property.
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, JToken> UnmappedData { get; set; }
    }
