    tl.Arguments.Column = new TextLoaderColumns[numColumns];
    tl.Arguments.Column[0].Name = ...
    tl.Arguments.Column[0].Source = ... // see the docs
    tl.Arguments.Column[0].Type = ...
    // and so on.
