    public FileResult SetDataExcel(object obj)
    {
        GridView grid = new GridView();
        grid.AutoGeneratedColumns = true; // automatically generate all columns from data source
        grid.DataSource = result;
        StringWriter strwritter = new StringWriter();
        HtmlTextWriter htmltextwrtter = new HtmlTextWriter(strwritter);
        grid.RenderControl(htmltextwrtter);
        string path = Server.MapPath("~/path/to/filename.xls");
        using (var sw = new StreamWriter(path))
        {
            sw.Write(strwriter.ToString());
        }
        var savedFile = new FileStream(path, FileMode.Open);
        return File(savedFile, "application/ms-excel");
    }
