    static async Task Main(string[] args)
    {
        await Task.Delay(1);
        Console.ReadLine();
    }
    // This gets generated by the compiler.
    static void Main(string[] args)
    {
        Main(args).GetAwaiter.GetResult();
    }
