            List<string> colNames = new List<string>();
            colNames.Add("Desc");
            colNames.Add("Freq");
            colNames.Add("Date");
            colNames.Add("Amount");
            colNames.Add("Pay From");
            dgv_SetHeaderNames(dgvDebits, colNames);
            dgvDebits.ColumnCount = colNames.Count;
            colNames[4] = "Type";
            dgv_SetHeaderNames(dgvIncome, colNames);
            dgvIncome.ColumnCount = colNames.Count;
            colNames.Clear();
            colNames.Add("Key");
            colNames.Add("Description");
            colNames.Add("Date");
            colNames.Add("Freq");
            colNames.Add("Amount");
            colNames.Add("Pay From");
            colNames.Add("USAA Checking");
            colNames.Add("Amazon VISA");
            dgv_SetHeaderNames(dgvWorking, colNames);
