    void TestMethod()
    {
        UnspeackableClosureClass closure = new UnspeackableClosureClass(10);
        List<long> list1 = new List<long>();
        for (int i = 0; i < 5; i++)
            list1.Add(i);
    
        ThreadPool.QueueUserWorkItem(closure.AutoGeneratedMethod);
        closure.closureVar = 56;
    }
    public class UnspeackableClosureClass
    {
       public int closureVar;
       UnspeackableClosureClass(int val){closureVar=val}
       
       public void AutoGeneratedMethod(){
       int var2 = closureVar;
       Thread.Sleep(1000);
       list1.Clear();
       MessageBox.Show(var2.ToString());
      }
    }
