    // ...
    // ...
    cls_test testnum = null; // <= Leave as NULL at the beginning
    str_listcmd listcmd = new str_listcmd();
    
    foreach (string line in lines)
    {
    	if (line.Contains("Test"))
    	{
    		testnum = new cls_test(); // <= Init object for each Test line
    		// ...
    		// ...
