    Session.Initialize("1234567890");
    Session.ConvertMime = false;
    MailServer = Session.GetEnvironmentString("MailServer", true);
    MailFile = Session.GetEnvironmentString("Mailfile", true);
    MailDb = Session.GetDatabase(MailServer.ToString(), MailFile.ToString(), false);
    MailDoc = MailDb.CreateDocument();
    MailDoc.ReplaceItemValue("Form", "Memo");
    MailDoc.ReplaceItemValue("SendTo", "XXXXXX");
    MailDoc.ReplaceItemValue("subject", "Test test");
    MailDoc.AppendItemValue("Principal", "HIHIHi");
    object obAttachment;
    AttachmentPath = "C:\\Users\\Documents\\";
    AttachmentFile = "310143-001_1125_20181016.pdf";
    mailBody = "<html><head></head><body>Hello There.</body></html>";
    Mime = MailDoc.CreateMIMEEntity("Body");
    MimeHeader = Mime.CreateHeader("MIME-Version");
    MimeHeader.SetHeaderVal("1.0");
    MimeHeader= Mime.CreateHeader("Content-Type");
    MimeHeader.setHeaderValAndParams( "multipart/alternative;boundary=\"=NextPart_=\"");
    MimeChild = Mime.createChildEntity();
    HtmlBody = Session.CreateStream();
    HtmlBody.WriteText(mailBody, Stream.EOL_CR);
    MimeChild.SetContentFromText(HtmlBody, "text/html;charset=\"iso-8859-1\"", Domino.MIME_ENCODING.ENC_NONE);
    MimeChild = Mime.CreateChildEntity();
    HtmlBody = Session.CreateStream();
    HtmlBody.Open(AttachmentPath + AttachmentFile, "");   
    MimeHeader = MimeChild.CreateHeader("Content-Disposition");
    MimeHeader.SetHeaderVal("attachment; filename=\""+AttachmentFile+"\"");
    
    MimeChild.SetContentFromBytes(HtmlBody, "application/octet-stream; name=\""+AttachmentFile+"\"", Domino.MIME_ENCODING.ENC_IDENTITY_BINARY); 
    MailDoc.CloseMIMEEntities(true);
    Session.ConvertMime = true;
    Object obj = MailDoc.GetItemValue("SendTo");
    MailDoc.SaveMessageOnSend = true;
    MailDoc.Send(false, ref obj);
