    public static GRBackendRenderTargetDesc CreateRenderTarget() {
        ...
        return new GRBackendRenderTargetDesc {
            ...
            StencilBits = 1,
            ...
        };
    }
