    ... 
    public async Task<IEnumerable<FoodDto>> SelectFood(string rule, string query){
        return await selectInfo.FirstOrDefault(x=>x.Rule(rule)).Select(x=>x.ReturnSearchResult(query));
    }
    ...
