    public async Task<IActionResult> OnPostAsync(Guid id, string password, string passwordCheck) {
        //...
        var hashedPassword = new VPV.Helpers.Strings.Encrypt(password, salt);
        //...
    }
