    Person person = new Person
                {
                    Id = 2,
                    Name = "FIO FIO IFO",
                    Address = new Address { Street = "Golden Gate" }
                };
    
                XmlSerializer serializer = new XmlSerializer(person.GetType());
                using (StreamWriter writer = new StreamWriter(@"Path to xml file"))
                {
                    serializer.Serialize(writer, person);
                }
    
    
                using (StringReader stringReader = new StringReader(File.ReadAllText(@"Path to same xml file that generated by above serializer")))
                {
                    person = (Person)serializer.Deserialize(stringReader);
                }
