    Person person = new Person
    {
        Id = 2,
        Name = "FIO FIO IFO",
        Address = new Address { Street = "Golden Gate" }
    };
    //--------------------Serialization----------------------------
    XmlSerializer serializer = new XmlSerializer(person.GetType());
    using (StreamWriter writer = new StreamWriter(@"Path to xml file"))
    {
        serializer.Serialize(writer, person);
    }
    
    //--------------------Deserialization----------------------------
    using (StringReader stringReader = new StringReader(File.ReadAllText(@"Path to same xml file that generated by above serializer")))
    {
        person = (Person)serializer.Deserialize(stringReader);
    
        Console.WriteLine("Id: " + person.Id);
        Console.WriteLine("Name: " + person.Name);
        Console.WriteLine("Street: " + person.Address.Street);
        Console.ReadLine();
    }
