            var a = 2;   //int
            var b = 2.0; //double
            var c = 2d;  //double
            var d = 2f;  //float (alias of System.Single)
            var e = 2m;  //decimal
            var f = 2l;  //long
            var g = 2ul; //ulong
            var h = 2.0m; //decimal
            var t = 1 / 2.0; //double
            var u = 1 / 2; //int!
