    class Phone {...}
    class Q {
    ...
      [XmlElement("phone")]
      Phone Phone {get;set;}
    ...
    }
    class QCalls{
    ...
      [XmlElement("Q")]
      List<Q> QItems {get;set;}
    ...
    }
