    public override void Up()
    {
    	DropForeignKey(...)
    	// ...
    	DropIndex(...) 
    	// ... 
    	DropPrimaryKey(...)
    	// ...
    	AlterColumn(...)
    	// ...
    	AddPrimaryKey(...)
    	// ...
    	CreateIndex(...)
    	// ...
    	AddForeignKey) 
    	// ...
    }
