    // ...
    .AddSingleton<IEntityPolicy<BaseEntity>, BaseEntityPolicy>()
    .AddSingleton<IEntityPolicy<GrandChildAEntity>, GrandChildAEntityPolicy>()
    .AddSingleton<IEntityPolicy<ChildBEntity>, ChildBEntityPolicy>()
    // ...
