    if (PersonEnum.HasFlag(PersonEnum.Name)) // Name is set. HasFlag is equivalent to (PersonEnum & PersonEnum.Name) != 0
    {
        person.Name = ...
    }
    else if (PersonEnum.HasFlag(PersonEnum.Age)) // Age is set
    {
        person.Age = ...
    }
    ...
