    <NuspecFile>package.nuspec</NuspecFile>
    <NuspecProperties>$(NuspecProperties);configuration=$(Configuration)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);version=$(Version)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);id=$(PackageId)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);author=$(Authors)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);PackageProjectUrl=$(PackageProjectUrl)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);Description=$(Description)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);PackageReleaseNotes=$(PackageReleaseNotes)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);Copyright=$(Copyright)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);PackageTags=$(PackageTags)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);RepositoryType=$(RepositoryType)</NuspecProperties>
    <NuspecProperties>$(NuspecProperties);RepositoryUrl=$(RepositoryUrl)</NuspecProperties>
