     string lineToBeAdded = string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"{6}\",\"{7}\",\"{8}\",\"{9}\",\"{10}\"", 
    CompanyName.Replace("\"","\"\""),
     Website.Replace("\"","\"\""),
     FirsttName.Replace("\"","\"\""),
     LastName.Replace("\"","\"\""),
     JobTitle.Replace("\"","\"\""),
     Phone.Replace("\"","\"\""),
     Email.Replace("\"","\"\""),
     Solution.Replace("\"","\"\""),
     Notes.Replace("\"","\"\""),
     ContactOwner.Replace("\"","\"\""),
     EventName.Replace("\"","\"\""));
