    public CustomerReceiptRepository : IReceiptRepository {
        public Receipt Get(int id) {
                var rec = DbContext.Table.Receipt.FirstOrDefault(r => r.id = id);
                if(rec.DiscriminatorField == 1) //CustomerReceipt
                {
                    return new CustomerReceipt
                    {
                         ID = ...
                         ReceiptNumber = ...
                         CustomerNumber = ...
                         CustomerEmail = ...
                         CustomerOption = ...
                     }
                  }
                  //all other cases are InternalReceipts
                  return new InternalReceipt
                  {
                       ID = ...
                       ReceiptNumber = ...
                       InternalNumber  = ...
                       InternalEmail = ... 
                       InternalOption = ...
                  }
        }
    }
