csharp
void Main()
{
   var userFaker = new Faker<User>()
            .RuleFor( u => u.FirstName, f => f.Name.FirstName())
            .RuleFor( u => u.LastName, f => f.Name.LastName().OrNull(f, .2f) );
            
   userFaker.Generate(10).Dump();
}
public class User{
   public string FirstName{get;set;}
   public string LastName{get;set;}
}
[![][1]][1]
You can also remove the `ReturnGenderType` helper method and use the `f => f.Person` property instead. Summing it all up, here's how your code cleans up:
csharp
void Main()
{
   var userFaker = new Faker<User>()
    .RuleFor(u => u.Gender,     f => f.Person.Gender.ToString())
    .RuleFor(u => u.BirthDate,  f => f.Date.PastOffset(60, DateTime.Now.AddYears(-18)).Date.ToShortDateString())
    .RuleFor(u => u.FirstName,  f => f.Person.FirstName)
    .RuleFor(u => u.MiddleName, f => f.Name.FirstName(f.Person.Gender).OrNull(f, .2f))
    .RuleFor(u => u.LastName,   f => f.Person.LastName)
    .RuleFor(u => u.Salutation, f => f.Name.Prefix(f.Person.Gender));
    
   userFaker.Generate(10).Dump();
}
public class User
{
   public string Gender { get; set; }
   public string BirthDate { get; set; }
   public string FirstName { get; set; }
   public string MiddleName { get; set; }
   public string LastName { get; set; }
   public string Salutation { get; set; }
}
[![][2]][2]
BTW, the **Salutation** generated by `f.Name.Prefix(Gender)` is sometimes not right because gender prefixes are not separated in the `en` locale. If this is a concern, you can extend **Bogus** a tiny bit more with an extension method that fixes your locale:
csharp
public static class MyExtensionsForBogus{
   public static string Prefix2(this Bogus.DataSets.Name name, Gender gender)
   {
      if (gender == Gender.Male)
      {
         return name.Random.ArrayElement(new[] { "Mr.", "Dr." });
      }
      return name.Random.ArrayElement(new[]{"Miss", "Ms.", "Mrs."});
   }
}
Then, the new **Salutation** rule becomes:
csharp
    .RuleFor(u => u.Salutation, f => f.Name.Prefix2(f.Person.Gender));
And now ya got some nice looking data there:
[![][3]][3]
Hope that helps! =)
  [1]: https://i.stack.imgur.com/vvucM.png
  [2]: https://i.stack.imgur.com/YS5AL.png
  [3]: https://i.stack.imgur.com/PQqwT.png
