    TypeManager.SubstTypeCore(type, pctx)
    TypeManager.SubstTypeArray(taSrc, pctx)
    TypeManager.SubstTypeCore(type, pctx)
    AggregateType.GetBaseClass()
    TypeManager.GetAggregate(agg, atsOuter, typeArgs)
    TypeManager.GetAggregate(agg, typeArgsAll)
    SymbolTable.GetConstructedType(type, agg)
    SymbolTable.LoadSymbolsFromType(originalType)
    TypeManager.GetAggregate(agg, atsOuter, typeArgs)
    TypeManager.GetAggregate(agg, typeArgsAll)
    TypeManager.SubstTypeCore(type, pctx)
    TypeManager.SubstTypeArray(taSrc, pctx)
    TypeManager.SubstTypeCore(type, pctx)
    AggregateType.GetBaseClass()
    TypeManager.GetAggregate(agg, atsOuter, typeArgs)
    TypeManager.GetAggregate(agg, typeArgsAll)
    SymbolTable.GetConstructedType(type, agg)
    SymbolTable.LoadSymbolsFromType(originalType)
    TypeManager.GetAggregate(agg, atsOuter, typeArgs)
    TypeManager.GetAggregate(agg, typeArgsAll)
    TypeManager.SubstTypeCore(type, pctx)
    TypeManager.SubstTypeArray(taSrc, pctx)
    TypeManager.SubstTypeCore(type, pctx)
    AggregateType.GetBaseClass()
    TypeManager.GetAggregate(agg, atsOuter, typeArgs)
    TypeManager.GetAggregate(agg, typeArgsAll)
    SymbolTable.GetConstructedType(type, agg)
    SymbolTable.LoadSymbolsFromType(originalType)
    TypeManager.GetAggregate(agg, atsOuter, typeArgs)
    AggregateSymbol.getThisType()
    SymbolTable.AddAggregateToSymbolTable(parent, type)
    SymbolTable.LoadSymbolsFromType(originalType)
    SymbolTable.GetConstructedType(type, agg)
    SymbolTable.LoadSymbolsFromType(originalType)
    SymbolTable.GetConstructedType(type, agg)
    SymbolTable.LoadSymbolsFromType(originalType)
    SymbolTable.CreateInheritanceHierarchyList(type)
    SymbolTable.PopulateSymbolTableWithName(name, typeArguments, callingType)
    PopulateSymbolTableWithPayloadInformation(payload, callingType, arguments)
    BindCore(payload, parameters, args, deferredBinding)
    Bind(payload, parameters, args, deferredBinding)
    BinderHelper.Bind(action, binder, args, arginfos, onBindingError)
    CSharpInvokeMemberBinder.FallbackInvokeMember(target, args, errorSuggestion)
    DynamicMetaObject.BindInvokeMember(binder, args)
    InvokeMemberBinder.Bind(target, args)
    DynamicMetaObjectBinder.Bind(args, parameters, returnLabel)
    CallSiteBinder.BindCore<System.Action<System.Runtime.CompilerServices.CallSite, Program.TemplateDataProcessor<string>, object>>(site, args)
    UpdateDelegates.UpdateAndExecuteVoid2<Program.TemplateDataProcessor<string>, object>(site, arg0, arg1)
    Program.Main(args)
